    .global Unk_08210764
Unk_08210764:
    .string "{END}"

    .global Unk_08210765
Unk_08210765:
    .string "Dogen{END}"

    .global Unk_0821076B
Unk_0821076B:
    .string "Nanai{END}"

    .global Unk_08210771
Unk_08210771:
    .string "Winlan{END}"

    .global Unk_08210778
Unk_08210778:
    .string "Romero{END}"

    .global Unk_0821077F
Unk_0821077F:
    .string "Gust{END}"

    .global Unk_08210784
Unk_08210784:
    .string "Camlon{END}"

    .global Unk_0821078B
Unk_0821078B:
    .string "Nada{END}"

    .global Unk_08210790
Unk_08210790:
    .string "Tantar{END}"

    .global Unk_08210797
Unk_08210797:
    .string "Tuntar{END}"

    .global Unk_0821079E
Unk_0821079E:
    .string "Agua{END}"

    .global Unk_082107A3
Unk_082107A3:
    .string "Auria{END}"

    .global Unk_082107A9
Unk_082107A9:
    .string "Bleak{END}"

    .global Unk_082107AF
Unk_082107AF:
    .string "Arad{END}"

    .global Unk_082107B4
Unk_082107B4:
    .string "Spring{END}"

    .global Unk_082107BB
Unk_082107BB:
    .string "Tunlan{END}"

    .global Unk_082107C2
Unk_082107C2:
    .string "Gant{END}"

    .global Unk_082107C7
Unk_082107C7:
    .string "Scande{END}"

    .global Unk_082107CE
Unk_082107CE:
    .string "Carmen{END}"

    .global Unk_082107D5
Unk_082107D5:
    .string "Gramor{END}"

    .global Unk_082107DC
Unk_082107DC:
    .string "Wisdon{END}"

    .global Unk_082107E3
Unk_082107E3:
    .string "Karma{END}"

    .global Unk_082107E9
Unk_082107E9:
    .string "Prima{END}"

    .global Unk_082107EF
Unk_082107EF:
    .string "Krypt{END}"

    .global Unk_082107F5
Unk_082107F5:
    .string "Nabal{END}"

    .global Unk_082107FB
Unk_082107FB:
    .string "Tock{END}"

    .global Unk_08210800
Unk_08210800:
    .string "Spyre{END}"

    .global Unk_08210806
Unk_08210806:
    .string "Obelisk{END}"

    .global Unk_0821080E
Unk_0821080E:
    .string "Pagoda{END}"

