    .global Unk_08210363
Unk_08210363:
    .string "Robe{END}"

    .global Unk_08210368
Unk_08210368:
    .string "WLdrCP{END}"

    .global Unk_0821036F
Unk_0821036F:
    .string "Kleid{END}"

    .global Unk_08210375
Unk_08210375:
    .string "MetlRÜ{END}"

    .global Unk_0821037C
Unk_0821037C:
    .string "SeidHS{END}"

    .global Unk_08210383
Unk_08210383:
    .string "Kldng{END}"

    .global Unk_08210389
Unk_08210389:
    .string "LichtKL{END}"

    .global Unk_08210391
Unk_08210391:
    .string "Talar{END}"

    .global Unk_08210397
Unk_08210397:
    .string "ArmSchtz{END}"

    .global Unk_082103A0
Unk_082103A0:
    .string "Wolffell{END}"

    .global Unk_082103A9
Unk_082103A9:
    .string "RangerVT{END}"

    .global Unk_082103B2
Unk_082103B2:
    .string "BronzRÜ{END}"

    .global Unk_082103BA
Unk_082103BA:
    .string "PnzerRÜ{END}"

    .global Unk_082103C2
Unk_082103C2:
    .string "Dummy{END}"

    .global Unk_082103C8
Unk_082103C8:
    .string "FlammRÜ{END}"

    .global Unk_082103D0
Unk_082103D0:
    .string "KerkrKL{END}"

    .global Unk_082103D8
Unk_082103D8:
    .string "SRüstng{END}"

    .global Unk_082103E0
Unk_082103E0:
    .string "EisRÜ{END}"

    .global Unk_082103E6
Unk_082103E6:
    .string "WeltHR{END}"

    .global Unk_082103ED
Unk_082103ED:
    .string "Dummy{END}"

    .global Unk_082103F3
Unk_082103F3:
    .string "StchlKL{END}"

    .global Unk_082103FB
Unk_082103FB:
    .string "HeldRÜ{END}"

    .global Unk_08210402
Unk_08210402:
    .string "TeuflRB{END}"

    .global Unk_0821040A
Unk_0821040A:
    .string "WLedrGN{END}"

    .global Unk_08210412
Unk_08210412:
    .string "WLedrRÜ{END}"

    .global Unk_0821041A
Unk_0821041A:
    .string "KettnHD{END}"

    .global Unk_08210422
Unk_08210422:
    .string "EisnHR{END}"

    .global Unk_08210429
Unk_08210429:
    .string "WollRB{END}"

    .global Unk_08210430
Unk_08210430:
    .string "WLedrRB{END}"

    .global Unk_08210438
Unk_08210438:
    .string "LebensRÜ{END}"

    .global Unk_08210441
Unk_08210441:
    .string "PowerRÜ{END}"

    .global Unk_08210449
Unk_08210449:
    .string "QuartzRÜ{END}"

    .global Unk_08210452
Unk_08210452:
    .string "EngelsRÜ{END}"

    .global Unk_0821045B
Unk_0821045B:
    .string "Dummy{END}"

    .global Unk_08210461
Unk_08210461:
    .string "GuruCT{END}"

    .global Unk_08210468
Unk_08210468:
    .string "Dummy{END}"

    .global Unk_0821046E
Unk_0821046E:
    .string "Dummy{END}"

    .global Unk_08210474
Unk_08210474:
    .string "WeltRÜ{END}"

    .global Unk_0821047B
Unk_0821047B:
    .string "SagenHR{END}"

    .global Unk_08210483
Unk_08210483:
    .string "Dummy{END}"

    .global Unk_08210489
Unk_08210489:
    .string "MystRB{END}"

    .global Unk_08210490
Unk_08210490:
    .string "ErdRB{END}"

    .global Unk_08210496
Unk_08210496:
    .string "Dummy{END}"

    .global Unk_0821049C
Unk_0821049C:
    .string "AgileRÜ{END}"

    .global Unk_082104A4
Unk_082104A4:
    .string "Dummy{END}"

    .global Unk_082104AA
Unk_082104AA:
    .string "JagdKL{END}"

    .global Unk_082104B1
Unk_082104B1:
    .string "GltteKL{END}"

    .global Unk_082104B9
Unk_082104B9:
    .string "Dummy{END}"

    .global Unk_082104BF
Unk_082104BF:
    .string "HolzSH{END}"

    .global Unk_082104C6
Unk_082104C6:
    .string "PzHdsch{END}"

    .global Unk_082104CE
Unk_082104CE:
    .string "WLedrSH{END}"

    .global Unk_082104D6
Unk_082104D6:
    .string "WachSH{END}"

    .global Unk_082104DD
Unk_082104DD:
    .string "Armband{END}"

    .global Unk_082104E5
Unk_082104E5:
    .string "EisnSH{END}"

    .global Unk_082104EC
Unk_082104EC:
    .string "BronzSH{END}"

    .global Unk_082104F4
Unk_082104F4:
    .string "MetllSH{END}"

    .global Unk_082104FC
Unk_082104FC:
    .string "FlammSH{END}"

    .global Unk_08210504
Unk_08210504:
    .string "Dummy{END}"

    .global Unk_0821050A
Unk_0821050A:
    .string "SSchld{END}"

    .global Unk_08210511
Unk_08210511:
    .string "EisnSL{END}"

    .global Unk_08210518
Unk_08210518:
    .string "MetllSL{END}"

    .global Unk_08210520
Unk_08210520:
    .string "Dummy{END}"

    .global Unk_08210526
Unk_08210526:
    .string "Armband{END}"

    .global Unk_0821052E
Unk_0821052E:
    .string "EisSH{END}"

    .global Unk_08210534
Unk_08210534:
    .string "ProSH{END}"

    .global Unk_0821053A
Unk_0821053A:
    .string "LiebeAB{END}"

    .global Unk_08210542
Unk_08210542:
    .string "WindAB{END}"

    .global Unk_08210549
Unk_08210549:
    .string "RubinRG{END}"

    .global Unk_08210551
Unk_08210551:
    .string "Dummy{END}"

    .global Unk_08210557
Unk_08210557:
    .string "DnklAB{END}"

    .global Unk_0821055E
Unk_0821055E:
    .string "Dummy{END}"

    .global Unk_08210564
Unk_08210564:
    .string "MystSH{END}"

    .global Unk_0821056B
Unk_0821056B:
    .string "Hndschuh{END}"

    .global Unk_08210574
Unk_08210574:
    .string "Dummy{END}"

    .global Unk_0821057A
Unk_0821057A:
    .string "FllSchtz{END}"

    .global Unk_08210583
Unk_08210583:
    .string "LichtSH{END}"

    .global Unk_0821058B
Unk_0821058B:
    .string "MagieRG{END}"

    .global Unk_08210593
Unk_08210593:
    .string "Bandage{END}"

    .global Unk_0821059B
Unk_0821059B:
    .string "Dummy{END}"

    .global Unk_082105A1
Unk_082105A1:
    .string "SilberAB{END}"

    .global Unk_082105AA
Unk_082105AA:
    .string "Dummy{END}"

    .global Unk_082105B0
Unk_082105B0:
    .string "KaltSH{END}"

    .global Unk_082105B7
Unk_082105B7:
    .string "JagdHS{END}"

    .global Unk_082105BE
Unk_082105BE:
    .string "MaskenSH{END}"

    .global Unk_082105C7
Unk_082105C7:
    .string "DrachnSH{END}"

    .global Unk_082105D0
Unk_082105D0:
    .string "Dummy{END}"

    .global Unk_082105D6
Unk_082105D6:
    .string "LavaSH{END}"

    .global Unk_082105DD
Unk_082105DD:
    .string "Dummy{END}"

    .global Unk_082105E3
Unk_082105E3:
    .string "WLdrHM{END}"

    .global Unk_082105EA
Unk_082105EA:
    .string "Visier{END}"

    .global Unk_082105F1
Unk_082105F1:
    .string "HaarBand{END}"

    .global Unk_082105FA
Unk_082105FA:
    .string "Diadem{END}"

    .global Unk_08210601
Unk_08210601:
    .string "KttnHM{END}"

    .global Unk_08210608
Unk_08210608:
    .string "GDiadm{END}"

    .global Unk_0821060F
Unk_0821060F:
    .string "EchoHM{END}"

    .global Unk_08210616
Unk_08210616:
    .string "EisnMask{END}"

    .global Unk_0821061F
Unk_0821061F:
    .string "Dummy{END}"

    .global Unk_08210625
Unk_08210625:
    .string "Dummy{END}"

    .global Unk_0821062B
Unk_0821062B:
    .string "SteinHM{END}"

    .global Unk_08210633
Unk_08210633:
    .string "GoldHM{END}"

    .global Unk_0821063A
Unk_0821063A:
    .string "GesMask{END}"

    .global Unk_08210642
Unk_08210642:
    .string "AgilHM{END}"

    .global Unk_08210649
Unk_08210649:
    .string "SchönHM{END}"

    .global Unk_08210651
Unk_08210651:
    .string "MystAM{END}"

    .global Unk_08210658
Unk_08210658:
    .string "TauchHM{END}"

    .global Unk_08210660
Unk_08210660:
    .string "GaiaMask{END}"

    .global Unk_08210669
Unk_08210669:
    .string "Helm{END}"

    .global Unk_0821066E
Unk_0821066E:
    .string "VerflHM{END}"

    .global Unk_08210676
Unk_08210676:
    .string "MschlHM{END}"

    .global Unk_0821067E
Unk_0821067E:
    .string "StrohHM{END}"

    .global Unk_08210686
Unk_08210686:
    .string "EisnHM{END}"

    .global Unk_0821068D
Unk_0821068D:
    .string "Dummy{END}"

    .global Unk_08210693
Unk_08210693:
    .string "TideHM{END}"

    .global Unk_0821069A
Unk_0821069A:
    .string "SchdlHM{END}"

    .global Unk_082106A2
Unk_082106A2:
    .string "PowerHM{END}"

    .global Unk_082106AA
Unk_082106AA:
    .string "Domino{END}"

    .global Unk_082106B1
Unk_082106B1:
    .string "HornHM{END}"

    .global Unk_082106B8
Unk_082106B8:
    .string "BTuch{END}"

    .global Unk_082106BE
Unk_082106BE:
    .string "Turban{END}"

    .global Unk_082106C5
Unk_082106C5:
    .string "Dummy{END}"

    .global Unk_082106CB
Unk_082106CB:
    .string "LiebeHM{END}"

    .global Unk_082106D3
Unk_082106D3:
    .string "Dummy{END}"

    .global Unk_082106D9
Unk_082106D9:
    .string "Dummy{END}"

    .global Unk_082106DF
Unk_082106DF:
    .string "Dummy{END}"

    .global Unk_082106E5
Unk_082106E5:
    .string "BronzHM{END}"

    .global Unk_082106ED
Unk_082106ED:
    .string "SHelm{END}"

    .global Unk_082106F3
Unk_082106F3:
    .string "SonnHM{END}"

    .global Unk_082106FA
Unk_082106FA:
    .string "WolfHM{END}"

    .global Unk_08210701
Unk_08210701:
    .string "EisHM{END}"

    .global Unk_08210707
Unk_08210707:
    .string "Dummy{END}"

    .global Unk_0821070D
Unk_0821070D:
    .string "Dummy{END}"

    .global Unk_08210713
Unk_08210713:
    .string "Dummy{END}"

    .global Unk_08210719
Unk_08210719:
    .string "SternSH{END}"

    .global Unk_08210721
Unk_08210721:
    .string "Dummy{END}"

    .global Unk_08210727
Unk_08210727:
    .string "SchdlRG{END}"

    .global Unk_0821072F
Unk_0821072F:
    .string "HimmlSH{END}"

    .global Unk_08210737
Unk_08210737:
    .string "Dummy{END}"

    .global Unk_0821073D
Unk_0821073D:
    .string "Dummy{END}"

    .global Unk_08210743
Unk_08210743:
    .string "DrachnHM{END}"

    .global Unk_0821074C
Unk_0821074C:
    .string "DrachnRÜ{END}"

    .global Unk_08210755
Unk_08210755:
    .string "ClvrRG{END}"

    .global Unk_0821075C
Unk_0821075C:
    .string "TraumRG{END}"

