    .global Unk_0820F0C8
Unk_0820F0C8:
    .string "Frosch{END}"

    .global Unk_0820F0CF
Unk_0820F0CF:
    .string "Ritter{END}"

    .global Unk_0820F0D6
Unk_0820F0D6:
    .string "Zaubr {END}"

    .global Unk_0820F0DD
Unk_0820F0DD:
    .string "Zaubr{END}"

    .global Unk_0820F0E3
Unk_0820F0E3:
    .string "Zaubr{END}"

    .global Unk_0820F0E9
Unk_0820F0E9:
    .string "Floh{END}"

    .global Unk_0820F0EE
Unk_0820F0EE:
    .string "EisGrm{END}"

    .global Unk_0820F0F5
Unk_0820F0F5:
    .string "Stumpf{END}"

    .global Unk_0820F0FC
Unk_0820F0FC:
    .string "Schädel{END}"

    .global Unk_0820F104
Unk_0820F104:
    .string "Schnabl{END}"

    .global Unk_0820F10C
Unk_0820F10C:
    .string "Blop{END}"

    .global Unk_0820F111
Unk_0820F111:
    .string "Lurch{END}"

    .global Unk_0820F117
Unk_0820F117:
    .string "Morte{END}"

    .global Unk_0820F11D
Unk_0820F11D:
    .string "Mortea{END}"

    .global Unk_0820F124
Unk_0820F124:
    .string "Kralle{END}"

    .global Unk_0820F12B
Unk_0820F12B:
    .string "Wut{END}"

    .global Unk_0820F12F
Unk_0820F12F:
    .string "General{END}"

    .global Unk_0820F137
Unk_0820F137:
    .string "Gremlin{END}"

    .global Unk_0820F13F
Unk_0820F13F:
    .string "Fetz{END}"

    .global Unk_0820F144
Unk_0820F144:
    .string "Pog{END}"

    .global Unk_0820F148
Unk_0820F148:
    .string "Zombie{END}"

    .global Unk_0820F14F
Unk_0820F14F:
    .string "Schleim{END}"

    .global Unk_0820F157
Unk_0820F157:
    .string "SReiter{END}"

    .global Unk_0820F15F
Unk_0820F15F:
    .string "Blurb{END}"

    .global Unk_0820F165
Unk_0820F165:
    .string "Pikenier{END}"

    .global Unk_0820F16E
Unk_0820F16E:
    .string "Schütze{END}"

    .global Unk_0820F176
Unk_0820F176:
    .string "Ruga{END}"

    .global Unk_0820F17B
Unk_0820F17B:
    .string "KSchwein{END}"

    .global Unk_0820F184
Unk_0820F184:
    .string "Amöblob{END}"

    .global Unk_0820F18C
Unk_0820F18C:
    .string "Bulla{END}"

    .global Unk_0820F192
Unk_0820F192:
    .string "Schabe{END}"

    .global Unk_0820F199
Unk_0820F199:
    .string "GFliege{END}"

    .global Unk_0820F1A1
Unk_0820F1A1:
    .string "AugApf{END}"

    .global Unk_0820F1A8
Unk_0820F1A8:
    .string "Okto{END}"

    .global Unk_0820F1AD
Unk_0820F1AD:
    .string "Krake{END}"

    .global Unk_0820F1B3
Unk_0820F1B3:
    .string "SandWurm{END}"

    .global Unk_0820F1BC
Unk_0820F1BC:
    .string "TGeist{END}"

    .global Unk_0820F1C3
Unk_0820F1C3:
    .string "SSkorp{END}"

    .global Unk_0820F1CA
Unk_0820F1CA:
    .string "Magier{END}"

    .global Unk_0820F1D1
Unk_0820F1D1:
    .string "Stachel{END}"

    .global Unk_0820F1D9
Unk_0820F1D9:
    .string "BSchütz{END}"

    .global Unk_0820F1E1
Unk_0820F1E1:
    .string "Fliege{END}"

    .global Unk_0820F1E8
Unk_0820F1E8:
    .string "LTraeger{END}"

    .global Unk_0820F1F1
Unk_0820F1F1:
    .string "Kreon{END}"

    .global Unk_0820F1F7
Unk_0820F1F7:
    .string "Ritter{END}"

    .global Unk_0820F1FE
Unk_0820F1FE:
    .string "Mothro{END}"

    .global Unk_0820F205
Unk_0820F205:
    .string "Mote{END}"

    .global Unk_0820F20A
Unk_0820F20A:
    .string "Soldat{END}"

    .global Unk_0820F211
Unk_0820F211:
    .string "GrimFlgl{END}"

    .global Unk_0820F21A
Unk_0820F21A:
    .string "Krabbe{END}"

    .global Unk_0820F221
Unk_0820F221:
    .string "SchleimX{END}"

    .global Unk_0820F22A
Unk_0820F22A:
    .string "Myst{END}"

    .global Unk_0820F22F
Unk_0820F22F:
    .string "RSchleim{END}"

    .global Unk_0820F238
Unk_0820F238:
    .string "Fisch{END}"

    .global Unk_0820F23E
Unk_0820F23E:
    .string "ZcknBrsch{END}"

    .global Unk_0820F248
Unk_0820F248:
    .string "Zwerg{END}"

    .global Unk_0820F24E
Unk_0820F24E:
    .string "Tronk{END}"

    .global Unk_0820F254
Unk_0820F254:
    .string "SandBlp{END}"

    .global Unk_0820F25C
Unk_0820F25C:
    .string "Tentakel{END}"

    .global Unk_0820F265
Unk_0820F265:
    .string "MSkorp{END}"

    .global Unk_0820F26C
Unk_0820F26C:
    .string "RugaX{END}"

    .global Unk_0820F272
Unk_0820F272:
    .string "PikenierX{END}"

    .global Unk_0820F27C
Unk_0820F27C:
    .string "SchützeX{END}"

    .global Unk_0820F285
Unk_0820F285:
    .string "Geist{END}"

    .global Unk_0820F28B
Unk_0820F28B:
    .string "RugaX{END}"

    .global Unk_0820F291
Unk_0820F291:
    .string "BlumeX{END}"

    .global Unk_0820F298
Unk_0820F298:
    .string "HornKröte{END}"

    .global Unk_0820F2A2
Unk_0820F2A2:
    .string "Mote{END}"

    .global Unk_0820F2A7
Unk_0820F2A7:
    .string "Zerl{END}"

    .global Unk_0820F2AC
Unk_0820F2AC:
    .string "Mothro{END}"

    .global Unk_0820F2B3
Unk_0820F2B3:
    .string "PKäfer{END}"

    .global Unk_0820F2BA
Unk_0820F2BA:
    .string "Chimäre{END}"

    .global Unk_0820F2C2
Unk_0820F2C2:
    .string "Fungus{END}"

    .global Unk_0820F2C9
Unk_0820F2C9:
    .string "G-Zwerg{END}"

    .global Unk_0820F2D1
Unk_0820F2D1:
    .string "KSchabe{END}"

    .global Unk_0820F2D9
Unk_0820F2D9:
    .string "Phoenix{END}"

    .global Unk_0820F2E1
Unk_0820F2E1:
    .string "Snsnmann{END}"

    .global Unk_0820F2EA
Unk_0820F2EA:
    .string "Zauberer{END}"

    .global Unk_0820F2F3
Unk_0820F2F3:
    .string "Kröte{END}"

    .global Unk_0820F2F9
Unk_0820F2F9:
    .string "Schrat{END}"

    .global Unk_0820F300
Unk_0820F300:
    .string "Goda{END}"

    .global Unk_0820F305
Unk_0820F305:
    .string "Zog{END}"

    .global Unk_0820F309
Unk_0820F309:
    .string "Jade{END}"

    .global Unk_0820F30E
Unk_0820F30E:
    .string "Göttin{END}"

    .global Unk_0820F315
Unk_0820F315:
    .string "Göttin{END}"

    .global Unk_0820F31C
Unk_0820F31C:
    .string "Sara{END}"

    .global Unk_0820F321
Unk_0820F321:
    .string "Zaubr{END}"

    .global Unk_0820F327
Unk_0820F327:
    .string "Zoom{END}"

    .global Unk_0820F32C
Unk_0820F32C:
    .string "Gargyl{END}"

    .global Unk_0820F333
Unk_0820F333:
    .string "GRitter{END}"

    .global Unk_0820F33B
Unk_0820F33B:
    .string "Schatten{END}"

    .global Unk_0820F344
Unk_0820F344:
    .string "GeistX{END}"

    .global Unk_0820F34B
Unk_0820F34B:
    .string "Spinne{END}"

    .global Unk_0820F352
Unk_0820F352:
    .string "Lodern{END}"

    .global Unk_0820F359
Unk_0820F359:
    .string "GGesp{END}"

    .global Unk_0820F35F
Unk_0820F35F:
    .string "EKiste{END}"

    .global Unk_0820F366
Unk_0820F366:
    .string "Göttin{END}"

    .global Unk_0820F36D
Unk_0820F36D:
    .string "DFloh{END}"

    .global Unk_0820F373
Unk_0820F373:
    .string "Krabbe{END}"

    .global Unk_0820F37A
Unk_0820F37A:
    .string "Blume{END}"

    .global Unk_0820F380
Unk_0820F380:
    .string "GSchleim{END}"

    .global Unk_0820F389
Unk_0820F389:
    .string "MSchleim{END}"

    .global Unk_0820F392
Unk_0820F392:
    .string "Buzzer{END}"

    .global Unk_0820F399
Unk_0820F399:
    .string "Krcher{END}"

    .global Unk_0820F3A0
Unk_0820F3A0:
    .string "Ruga{END}"

    .global Unk_0820F3A5
Unk_0820F3A5:
    .string "Ronk{END}"

    .global Unk_0820F3AA
Unk_0820F3AA:
    .string "HundshaiX{END}"

    .global Unk_0820F3B4
Unk_0820F3B4:
    .string "LodernX{END}"

    .global Unk_0820F3BC
Unk_0820F3BC:
    .string "AmeblobX{END}"

    .global Unk_0820F3C5
Unk_0820F3C5:
    .string "Nautulis{END}"

    .global Unk_0820F3CE
Unk_0820F3CE:
    .string "Witwe{END}"

    .global Unk_0820F3D4
Unk_0820F3D4:
    .string "MFloh{END}"

    .global Unk_0820F3DA
Unk_0820F3DA:
    .string "KrcherX{END}"

    .global Unk_0820F3E2
Unk_0820F3E2:
    .string "Mimikri{END}"

    .global Unk_0820F3EA
Unk_0820F3EA:
    .string "KSchweinX{END}"

    .global Unk_0820F3F4
Unk_0820F3F4:
    .string "FeuerKopf{END}"

    .global Unk_0820F3FE
Unk_0820F3FE:
    .string "Bully{END}"

    .global Unk_0820F404
Unk_0820F404:
    .string "Klaue{END}"

    .global Unk_0820F40A
Unk_0820F40A:
    .string "KrabbeX{END}"

    .global Unk_0820F412
Unk_0820F412:
    .string "KreonX{END}"

    .global Unk_0820F419
Unk_0820F419:
    .string "Bain{END}"

    .global Unk_0820F41E
Unk_0820F41E:
    .string "DReiter{END}"

    .global Unk_0820F426
Unk_0820F426:
    .string "Ghul{END}"

    .global Unk_0820F42B
Unk_0820F42B:
    .string "Kaktus{END}"

    .global Unk_0820F432
Unk_0820F432:
    .string "KaktusX{END}"

    .global Unk_0820F43A
Unk_0820F43A:
    .string "ICU{END}"

    .global Unk_0820F43E
Unk_0820F43E:
    .string "Wesen{END}"

    .global Unk_0820F444
Unk_0820F444:
    .string "DRitter{END}"

