    .global Unk_0820EA00
Unk_0820EA00:
    .string "Auf dem Höhepunkt der Macht\n"
    .string "des Drachenclans erschien\n"
    .string "eine Schicksalsgöttin.\n"
    .string "\n"
    .string "Die Göttin Milia konnte\n"
    .string "Wünsche erfüllen. Und die\n"
    .string "Drachen kämpften gegen-\n"
    .string "einander um ihre Gunst.{END}"

    .global Unk_0820EAB0
Unk_0820EAB0:
    .string "Milia schürte die Kämpfe\n"
    .string "noch und sah den Krieg der\n"
    .string "Drachen eskalieren.\n"
    .string "\n"
    .string "Als die Welt am Rand der\n"
    .string "Zerstörung stand, erschien\n"
    .string "ein legendärer Held.{END}"

    .global Unk_0820EB42
Unk_0820EB42:
    .string "Der Held und seine Gefährten\n"
    .string "nahmen Milia mit Hilfe von\n"
    .string "6 Schlüsseln gefangen.\n"
    .string "\n"
    .string "Diese “Göttlichen Schlüssel“\n"
    .string "wurden über die ganze Welt\n"
    .string "verstreut und versteckt.{END}"

    .global Unk_0820EBE3
Unk_0820EBE3:
    .string "Die Lichtdrachen stellten\n"
    .string "das Machtgleichgewicht wieder\n"
    .string "her und es herrschte Frieden.{END}"

    .global Unk_0820EC39
Unk_0820EC39:
    .string "Menschen leben und sterben\n"
    .string "so zahllos wie die\n"
    .string "Sterne am Himmel,\n"
    .string "sie treiben wie\n"
    .string "Schaum auf dem Wasser.{END}"

    .global Unk_0820ECA0
Unk_0820ECA0:
    .string "Warum werden wir in diese\n"
    .string "Welt geboren, nur um\n"
    .string "so schnell wieder zu\n"
    .string "verschwinden?{END}"

    .global Unk_0820ECF2
Unk_0820ECF2:
    .string "Im kosmischen Maßstab ist\n"
    .string "unser Leben ein Funken,\n"
    .string "der innerhalb eines\n"
    .string "Augenblicks verlischt.{END}"

    .global Unk_0820ED4F
Unk_0820ED4F:
    .string "Der Drachen-Clan hatte\n"
    .string "ein mächtiges Imperium\n"
    .string "und verschwand dann schnell,\n"
    .string "wie ein fallender Stern.{END}"

    .global Unk_0820EDB3
Unk_0820EDB3:
    .string "Während ihrer kurzen\n"
    .string "Herrschaft haben die\n"
    .string "Drachen sinnlose Kriege\n"
    .string "geführt um falschen\n"
    .string "Träumen zu folgen.{END}"

    .global Unk_0820EE1C
Unk_0820EE1C:
    .string "Jetzt taucht eine unheil-\n"
    .string "volle Macht auf, um den\n"
    .string "Kreislauf zu wiederholen.{END}"

    .global Unk_0820EE68
Unk_0820EE68:
    .string "Diese neue Bedrohung ist der\n"
    .string "Clan der Dunklen Drachen.{END}"

    .global Unk_0820EE9F
Unk_0820EE9F:
    .string "Sie vergessen, dass die\n"
    .string "Drachen das Land schon\n"
    .string "ein Mal verwüstet haben.{END}"

    .global Unk_0820EEE7
Unk_0820EEE7:
    .string "Der Clan der Dunklen\n"
    .string "Drachen macht sich bereit,\n"
    .string "die Welt wieder ins\n"
    .string "Chaos zu stürzen.{END}"

    .global Unk_0820EF3D
Unk_0820EF3D:
    .string "Mit neuen Kräften, die\n"
    .string "von einer mysteriösen\n"
    .string "Göttin stammen, beginnen\n"
    .string "die Drachen ihren neuen\n"
    .string "Feldzug.{END}"

    .global Unk_0820EFA4
Unk_0820EFA4:
    .string "Wer ist diese teuflische\n"
    .string "Macht, die teuflische\n"
    .string "Wünsche erfüllt?{END}"

    .global Unk_0820EFE4
Unk_0820EFE4:
    .string "Werden die Lichtdrachen\n"
    .string "sich erheben und der Welt\n"
    .string "den Frieden bringen?{END}"

    .global Unk_0820F02B
Unk_0820F02B:
    .string "Die Dunklen Drachen\n"
    .string "dringen weiter vor.{END}"

    .global Unk_0820F053
Unk_0820F053:
    .string "Bevor die Welt ihnen\n"
    .string "gehört...{END}"

    .global Unk_0820F072
Unk_0820F072:
    .string "...bevor die Göttin\n"
    .string "wiedererweckt wird...{END}"

    .global Unk_0820F09C
Unk_0820F09C:
    .string "...müssen die Lichtdrachen\n"
    .string "zurück schlagen!{END}"

