    .global Unk_0820FD96
Unk_0820FD96:
    .string "70G{END}"

    .global Unk_0820FD9A
Unk_0820FD9A:
    .string "150G{END}"

    .global Unk_0820FD9F
Unk_0820FD9F:
    .string "300G{END}"

    .global Unk_0820FDA4
Unk_0820FDA4:
    .string "650G{END}"

    .global Unk_0820FDA9
Unk_0820FDA9:
    .string "900G{END}"

    .global Unk_0820FDAE
Unk_0820FDAE:
    .string "1200G{END}"

    .global Unk_0820FDB4
Unk_0820FDB4:
    .string "2000G{END}"

    .global Unk_0820FDBA
Unk_0820FDBA:
    .string "3000G{END}"

    .global Unk_0820FDC0
Unk_0820FDC0:
    .string "Kraut{END}"

    .global Unk_0820FDC6
Unk_0820FDC6:
    .string "Heil{END}"

    .global Unk_0820FDCB
Unk_0820FDCB:
    .string "Ggngft{END}"

    .global Unk_0820FDD2
Unk_0820FDD2:
    .string "Eichel{END}"

    .global Unk_0820FDD9
Unk_0820FDD9:
    .string "MTraen{END}"

    .global Unk_0820FDE0
Unk_0820FDE0:
    .string "VTraen{END}"

    .global Unk_0820FDE7
Unk_0820FDE7:
    .string "Charm{END}"

    .global Unk_0820FDED
Unk_0820FDED:
    .string "Lebn2{END}"

    .global Unk_0820FDF3
Unk_0820FDF3:
    .string "TTref1{END}"

    .global Unk_0820FDFA
Unk_0820FDFA:
    .string "TTref2{END}"

    .global Unk_0820FE01
Unk_0820FE01:
    .string "Nebel{END}"

    .global Unk_0820FE07
Unk_0820FE07:
    .string "Whskrs{END}"

    .global Unk_0820FE0E
Unk_0820FE0E:
    .string "Wurm{END}"

    .global Unk_0820FE13
Unk_0820FE13:
    .string "Wurm2{END}"

    .global Unk_0820FE19
Unk_0820FE19:
    .string "Schrmp{END}"

    .global Unk_0820FE20
Unk_0820FE20:
    .string "SIgel{END}"

    .global Unk_0820FE26
Unk_0820FE26:
    .string "Mschl{END}"

    .global Unk_0820FE2C
Unk_0820FE2C:
    .string "Apfel{END}"

    .global Unk_0820FE32
Unk_0820FE32:
    .string "ProtnA{END}"

    .global Unk_0820FE39
Unk_0820FE39:
    .string "Geweih{END}"

    .global Unk_0820FE40
Unk_0820FE40:
    .string "WFlsch{END}"

    .global Unk_0820FE47
Unk_0820FE47:
    .string "Leben{END}"

    .global Unk_0820FE4D
Unk_0820FE4D:
    .string "Nägel{END}"

    .global Unk_0820FE53
Unk_0820FE53:
    .string "Flsch{END}"

    .global Unk_0820FE59
Unk_0820FE59:
    .string "BStn{END}"

    .global Unk_0820FE5E
Unk_0820FE5E:
    .string "FStn{END}"

    .global Unk_0820FE63
Unk_0820FE63:
    .string "CStn{END}"

    .global Unk_0820FE68
Unk_0820FE68:
    .string "Rauch{END}"

    .global Unk_0820FE6E
Unk_0820FE6E:
    .string "TdKuss{END}"

    .global Unk_0820FE75
Unk_0820FE75:
    .string "Heil2{END}"

    .global Unk_0820FE7B
Unk_0820FE7B:
    .string "ProtnB{END}"

    .global Unk_0820FE82
Unk_0820FE82:
    .string "Schrp{END}"

    .global Unk_0820FE88
Unk_0820FE88:
    .string "WTrnk{END}"

    .global Unk_0820FE8E
Unk_0820FE8E:
    .string "STrnk{END}"

    .global Unk_0820FE94
Unk_0820FE94:
    .string "StGlas{END}"

    .global Unk_0820FE9B
Unk_0820FE9B:
    .string "ExpKfr{END}"

    .global Unk_0820FEA2
Unk_0820FEA2:
    .string "Slab{END}"

    .global Unk_0820FEA7
Unk_0820FEA7:
    .string "LFnger{END}"

    .global Unk_0820FEAE
Unk_0820FEAE:
    .string "ESchl{END}"

    .global Unk_0820FEB4
Unk_0820FEB4:
    .string "RWssr{END}"

    .global Unk_0820FEBA
Unk_0820FEBA:
    .string "Kutsch{END}"

    .global Unk_0820FEC1
Unk_0820FEC1:
    .string "HSchuh{END}"

    .global Unk_0820FEC8
Unk_0820FEC8:
    .string "ATrnk{END}"

    .global Unk_0820FECE
Unk_0820FECE:
    .string "GTrnk{END}"

    .global Unk_0820FED4
Unk_0820FED4:
    .string "ETrnk{END}"

    .global Unk_0820FEDA
Unk_0820FEDA:
    .string "DrSoul{END}"

    .global Unk_0820FEE1
Unk_0820FEE1:
    .string "DrWarp{END}"

    .global Unk_0820FEE8
Unk_0820FEE8:
    .string "PlceBo{END}"

    .global Unk_0820FEEF
Unk_0820FEEF:
    .string "Ggmttl{END}"

    .global Unk_0820FEF6
Unk_0820FEF6:
    .string "WsKrg{END}"

    .global Unk_0820FEFC
Unk_0820FEFC:
    .string "Säge{END}"

    .global Unk_0820FF01
Unk_0820FF01:
    .string "Tafel{END}"

    .global Unk_0820FF07
Unk_0820FF07:
    .string "Ring{END}"

    .global Unk_0820FF0C
Unk_0820FF0C:
    .string "WsKrg{END}"

    .global Unk_0820FF12
Unk_0820FF12:
    .string "RSSchl{END}"

    .global Unk_0820FF19
Unk_0820FF19:
    .string "Papier{END}"

    .global Unk_0820FF20
Unk_0820FF20:
    .string "Schwur{END}"

    .global Unk_0820FF27
Unk_0820FF27:
    .string "GBeutl{END}"

    .global Unk_0820FF2E
Unk_0820FF2E:
    .string "SwPlvr{END}"

    .global Unk_0820FF35
Unk_0820FF35:
    .string "LSchl{END}"

    .global Unk_0820FF3B
Unk_0820FF3B:
    .string "DkSchl{END}"

    .global Unk_0820FF42
Unk_0820FF42:
    .string "Spiegl{END}"

    .global Unk_0820FF49
Unk_0820FF49:
    .string "Buch{END}"

    .global Unk_0820FF4E
Unk_0820FF4E:
    .string "Srdine{END}"

    .global Unk_0820FF55
Unk_0820FF55:
    .string "Makrl{END}"

    .global Unk_0820FF5B
Unk_0820FF5B:
    .string "SeeZng{END}"

    .global Unk_0820FF62
Unk_0820FF62:
    .string "Forlle{END}"

    .global Unk_0820FF69
Unk_0820FF69:
    .string "KFsch{END}"

    .global Unk_0820FF6F
Unk_0820FF6F:
    .string "Schnp{END}"

    .global Unk_0820FF75
Unk_0820FF75:
    .string "Thunf{END}"

    .global Unk_0820FF7B
Unk_0820FF7B:
    .string "Puffer{END}"

    .global Unk_0820FF82
Unk_0820FF82:
    .string "Rute1{END}"

    .global Unk_0820FF88
Unk_0820FF88:
    .string "Rute2{END}"

    .global Unk_0820FF8E
Unk_0820FF8E:
    .string "Rute3{END}"

    .global Unk_0820FF94
Unk_0820FF94:
    .string "Rute4{END}"

    .global Unk_0820FF9A
Unk_0820FF9A:
    .string "Rute5{END}"

    .global Unk_0820FFA0
Unk_0820FFA0:
    .string "EErz{END}"

    .global Unk_0820FFA5
Unk_0820FFA5:
    .string "Shlssl{END}"

    .global Unk_0820FFAC
Unk_0820FFAC:
    .string "Vitamn{END}"

    .global Unk_0820FFB3
Unk_0820FFB3:
    .string "Statue{END}"

    .global Unk_0820FFBA
Unk_0820FFBA:
    .string "AltEi{END}"

    .global Unk_0820FFC0
Unk_0820FFC0:
    .string "Güter{END}"

    .global Unk_0820FFC6
Unk_0820FFC6:
    .string "Ei{END}"

    .global Unk_0820FFC9
Unk_0820FFC9:
    .string "Sphäre{END}"

    .global Unk_0820FFD0
Unk_0820FFD0:
    .string "Kiemen{END}"

    .global Unk_0820FFD7
Unk_0820FFD7:
    .string "GBar{END}"

    .global Unk_0820FFDC
Unk_0820FFDC:
    .string "Eiszpf{END}"

    .global Unk_0820FFE3
Unk_0820FFE3:
    .string "Flöte{END}"

    .global Unk_0820FFE9
Unk_0820FFE9:
    .string "Pass{END}"

    .global Unk_0820FFEE
Unk_0820FFEE:
    .string "KTeile{END}"

    .global Unk_0820FFF5
Unk_0820FFF5:
    .string "Teile{END}"

    .global Unk_0820FFFB
Unk_0820FFFB:
    .string "DHrz{END}"

    .global Unk_08210000
Unk_08210000:
    .string "Karte{END}"

    .global Unk_08210006
Unk_08210006:
    .string "Liste{END}"

    .global Unk_0821000C
Unk_0821000C:
    .string "Wasnds{END}"

    .global Unk_08210013
Unk_08210013:
    .string "Notiz1{END}"

    .global Unk_0821001A
Unk_0821001A:
    .string "Notiz2{END}"

    .global Unk_08210021
Unk_08210021:
    .string "EKlaue{END}"

    .global Unk_08210028
Unk_08210028:
    .string "ZSchl{END}"

    .global Unk_0821002E
Unk_0821002E:
    .string "BRang{END}"

    .global Unk_08210034
Unk_08210034:
    .string "HmSchl{END}"

    .global Unk_0821003B
Unk_0821003B:
    .string "Bblfsh{END}"

    .global Unk_08210042
Unk_08210042:
    .string "Kissen{END}"

    .global Unk_08210049
Unk_08210049:
    .string "Maestro{END}"

    .global Unk_08210051
Unk_08210051:
    .string "GFlge{END}"

    .global Unk_08210057
Unk_08210057:
    .string "Öl{END}"

    .global Unk_0821005A
Unk_0821005A:
    .string "MHeil{END}"

    .global Unk_08210060
Unk_08210060:
    .string "Melone{END}"

    .global Unk_08210067
Unk_08210067:
    .string "Früchte{END}"

    .global Unk_0821006F
Unk_0821006F:
    .string "PFisch{END}"

    .global Unk_08210076
Unk_08210076:
    .string "Wurzel{END}"

    .global Unk_0821007D
Unk_0821007D:
    .string "KNuss{END}"

    .global Unk_08210083
Unk_08210083:
    .string "WGew{END}"

    .global Unk_08210088
Unk_08210088:
    .string "Elixier{END}"

    .global Unk_08210090
Unk_08210090:
    .string "Kraut  X9{END}"

    .global Unk_0821009A
Unk_0821009A:
    .string "Ggift  X9{END}"

    .global Unk_082100A4
Unk_082100A4:
    .string "Tropf  X9{END}"

    .global Unk_082100AE
Unk_082100AE:
    .string "Chrm   X9{END}"

    .global Unk_082100B8
Unk_082100B8:
    .string "Heil   X9{END}"

    .global Unk_082100C2
Unk_082100C2:
    .string "Eichl  X9{END}"

