    .global Unk_0820FB58
Unk_0820FB58:
    .string "Wo?{END}"

    .global Unk_0820FB5C
Unk_0820FB5C:
    .string "Dogen{END}"

    .global Unk_0820FB62
Unk_0820FB62:
    .string "Nanai{END}"

    .global Unk_0820FB68
Unk_0820FB68:
    .string "Winlan{END}"

    .global Unk_0820FB6F
Unk_0820FB6F:
    .string "Romero{END}"

    .global Unk_0820FB76
Unk_0820FB76:
    .string "Gust{END}"

    .global Unk_0820FB7B
Unk_0820FB7B:
    .string "Camlon{END}"

    .global Unk_0820FB82
Unk_0820FB82:
    .string "Nada{END}"

    .global Unk_0820FB87
Unk_0820FB87:
    .string "Tantar{END}"

    .global Unk_0820FB8E
Unk_0820FB8E:
    .string "Tuntar{END}"

    .global Unk_0820FB95
Unk_0820FB95:
    .string "Agua{END}"

    .global Unk_0820FB9A
Unk_0820FB9A:
    .string "Auria{END}"

    .global Unk_0820FBA0
Unk_0820FBA0:
    .string "Bleak{END}"

    .global Unk_0820FBA6
Unk_0820FBA6:
    .string "Arad{END}"

    .global Unk_0820FBAB
Unk_0820FBAB:
    .string "Spring{END}"

    .global Unk_0820FBB2
Unk_0820FBB2:
    .string "Tunlan{END}"

    .global Unk_0820FBB9
Unk_0820FBB9:
    .string "Gant{END}"

    .global Unk_0820FBBE
Unk_0820FBBE:
    .string "Scande{END}"

    .global Unk_0820FBC5
Unk_0820FBC5:
    .string "Carmen{END}"

    .global Unk_0820FBCC
Unk_0820FBCC:
    .string "Gramor{END}"

    .global Unk_0820FBD3
Unk_0820FBD3:
    .string "Wisdon{END}"

    .global Unk_0820FBDA
Unk_0820FBDA:
    .string "Karma{END}"

    .global Unk_0820FBE0
Unk_0820FBE0:
    .string "Prima{END}"

    .global Unk_0820FBE6
Unk_0820FBE6:
    .string "Krypt{END}"

    .global Unk_0820FBEC
Unk_0820FBEC:
    .string "Nabal{END}"

    .global Unk_0820FBF2
Unk_0820FBF2:
    .string "Tock{END}"

    .global Unk_0820FBF7
Unk_0820FBF7:
    .string "Spyre{END}"

    .global Unk_0820FBFD
Unk_0820FBFD:
    .string "Obelisk{END}"

    .global Unk_0820FC05
Unk_0820FC05:
    .string "Pagode{END}"

    .global Unk_0820FC0C
Unk_0820FC0C:
    .string "DrachnPalast{END}"

    .global Unk_0820FC19
Unk_0820FC19:
    .string "DrachenTmpl{END}"

    .global Unk_0820FC25
Unk_0820FC25:
    .string "Ramui-Wald{END}"

    .global Unk_0820FC30
Unk_0820FC30:
    .string "Aura-Höhle{END}"

    .global Unk_0820FC3B
Unk_0820FC3B:
    .string "Lament-Wald{END}"

    .global Unk_0820FC47
Unk_0820FC47:
    .string "Gaia-Tempel{END}"

    .global Unk_0820FC53
Unk_0820FC53:
    .string "Höhlen-See{END}"

    .global Unk_0820FC5E
Unk_0820FC5E:
    .string "Schrein-See{END}"

    .global Unk_0820FC6A
Unk_0820FC6A:
    .string "Höhlenkap{END}"

    .global Unk_0820FC74
Unk_0820FC74:
    .string "Ruhige Höhle{END}"

    .global Unk_0820FC81
Unk_0820FC81:
    .string "GrimFowl Wld{END}"

    .global Unk_0820FC8E
Unk_0820FC8E:
    .string "DunkleD Fort{END}"

    .global Unk_0820FC9B
Unk_0820FC9B:
    .string "Geheimbasis{END}"

    .global Unk_0820FCA7
Unk_0820FCA7:
    .string "Stein-Robot{END}"

    .global Unk_0820FCB3
Unk_0820FCB3:
    .string "DunkleD Schf{END}"

    .global Unk_0820FCC0
Unk_0820FCC0:
    .string "L & D Höhle{END}"

    .global Unk_0820FCCC
Unk_0820FCCC:
    .string "Verst. Fort{END}"

    .global Unk_0820FCD8
Unk_0820FCD8:
    .string "L & D Turm{END}"

    .global Unk_0820FCE3
Unk_0820FCE3:
    .string "Meeresvulkan{END}"

    .global Unk_0820FCF0
Unk_0820FCF0:
    .string "Teufelsturm{END}"

    .global Unk_0820FCFC
Unk_0820FCFC:
    .string "Wildnis{END}"

    .global Unk_0820FD04
Unk_0820FD04:
    .string "AmazonDung{END}"

    .global Unk_0820FD0F
Unk_0820FD0F:
    .string "Feenwald{END}"

    .global Unk_0820FD18
Unk_0820FD18:
    .string "AmazonStadt{END}"

    .global Unk_0820FD24
Unk_0820FD24:
    .string "Lab{END}"

    .global Unk_0820FD28
Unk_0820FD28:
    .string "Mauseloch{END}"

    .global Unk_0820FD32
Unk_0820FD32:
    .string "Froschhöhle{END}"

    .global Unk_0820FD3E
Unk_0820FD3E:
    .string "Südhöhle{END}"

    .global Unk_0820FD47
Unk_0820FD47:
    .string "Südl. Burg{END}"

    .global Unk_0820FD52
Unk_0820FD52:
    .string "Traumstadt{END}"

    .global Unk_0820FD5D
Unk_0820FD5D:
    .string "W-Sammler{END}"

    .global Unk_0820FD67
Unk_0820FD67:
    .string "W-Sammlerin{END}"

    .global Unk_0820FD73
Unk_0820FD73:
    .string "Wüstenhöhle{END}"

    .global Unk_0820FD7F
Unk_0820FD7F:
    .string "Winterhöhle{END}"

    .global Unk_0820FD8B
Unk_0820FD8B:
    .string "Geheimraum{END}"

