    .global Unk_08210815
Unk_08210815:
    .string "Cura1{END}"

    .global Unk_0821081B
Unk_0821081B:
    .string "Vert{END}"

    .global Unk_08210820
Unk_08210820:
    .string "Inakt{END}"

    .global Unk_08210826
Unk_08210826:
    .string "PlGl{END}"

    .global Unk_0821082B
Unk_0821082B:
    .string "PlAng{END}"

    .global Unk_08210831
Unk_08210831:
    .string "Cura2{END}"

    .global Unk_08210837
Unk_08210837:
    .string "Halt{END}"

    .global Unk_0821083C
Unk_0821083C:
    .string "PlAgi{END}"

    .global Unk_08210842
Unk_08210842:
    .string "TEng1{END}"

    .global Unk_08210848
Unk_08210848:
    .string "Cura3{END}"

    .global Unk_0821084E
Unk_0821084E:
    .string "Erwach{END}"

    .global Unk_08210855
Unk_08210855:
    .string "Heil{END}"

    .global Unk_0821085A
Unk_0821085A:
    .string "Schild{END}"

    .global Unk_08210861
Unk_08210861:
    .string "Cura4{END}"

    .global Unk_08210867
Unk_08210867:
    .string "TEng2{END}"

    .global Unk_0821086D
Unk_0821086D:
    .string "VertX{END}"

    .global Unk_08210873
Unk_08210873:
    .string "ZBann{END}"

    .global Unk_08210879
Unk_08210879:
    .string "Entzau{END}"

    .global Unk_08210880
Unk_08210880:
    .string "ErwchX{END}"

    .global Unk_08210887
Unk_08210887:
    .string "CuraX{END}"

    .global Unk_0821088D
Unk_0821088D:
    .string "Wand{END}"

    .global Unk_08210892
Unk_08210892:
    .string "TEngX{END}"

    .global Unk_08210898
Unk_08210898:
    .string "Licht{END}"

    .global Unk_0821089E
Unk_0821089E:
    .string "Funke{END}"

    .global Unk_082108A4
Unk_082108A4:
    .string "Kälte{END}"

    .global Unk_082108AA
Unk_082108AA:
    .string "35{END}"

    .global Unk_082108AD
Unk_082108AD:
    .string "Para{END}"

    .global Unk_082108B2
Unk_082108B2:
    .string "TSaug{END}"

    .global Unk_082108B8
Unk_082108B8:
    .string "TStrf{END}"

    .global Unk_082108BE
Unk_082108BE:
    .string "Flamm{END}"

    .global Unk_082108C4
Unk_082108C4:
    .string "Röst{END}"

    .global Unk_082108C9
Unk_082108C9:
    .string "Frost{END}"

    .global Unk_082108CF
Unk_082108CF:
    .string "55{END}"

    .global Unk_082108D2
Unk_082108D2:
    .string "FBall{END}"

    .global Unk_082108D8
Unk_082108D8:
    .string "LSturm{END}"

    .global Unk_082108DF
Unk_082108DF:
    .string "Chill{END}"

    .global Unk_082108E5
Unk_082108E5:
    .string "95{END}"

    .global Unk_082108E8
Unk_082108E8:
    .string "DSturm{END}"

    .global Unk_082108EF
Unk_082108EF:
    .string "Eis{END}"

    .global Unk_082108F3
Unk_082108F3:
    .string "FDra{END}"

    .global Unk_082108F8
Unk_082108F8:
    .string "EisX{END}"

    .global Unk_082108FD
Unk_082108FD:
    .string "FeuerX{END}"

    .global Unk_08210904
Unk_08210904:
    .string "BolzX{END}"

    .global Unk_0821090A
Unk_0821090A:
    .string "ASaug{END}"

    .global Unk_08210910
Unk_08210910:
    .string "???1{END}"

    .global Unk_08210915
Unk_08210915:
    .string "Komet{END}"

    .global Unk_0821091B
Unk_0821091B:
    .string "???2{END}"

    .global Unk_08210920
Unk_08210920:
    .string "???3{END}"

    .global Unk_08210925
Unk_08210925:
    .string "???4{END}"

    .global Unk_0821092A
Unk_0821092A:
    .string "???5{END}"

    .global Unk_0821092F
Unk_0821092F:
    .string "???6{END}"

    .global Unk_08210934
Unk_08210934:
    .string "???7{END}"

    .global Unk_08210939
Unk_08210939:
    .string "Cura1{END}"

    .global Unk_0821093F
Unk_0821093F:
    .string "ErwchX{END}"

    .global Unk_08210946
Unk_08210946:
    .string "Edd{END}"

    .global Unk_0821094A
Unk_0821094A:
    .string "EddX{END}"

    .global Unk_0821094F
Unk_0821094F:
    .string "Eco{END}"

    .global Unk_08210953
Unk_08210953:
    .string "EcoX{END}"

    .global Unk_08210958
Unk_08210958:
    .string "???8{END}"

    .global Unk_0821095D
Unk_0821095D:
    .string "???9{END}"

    .global Unk_08210962
Unk_08210962:
    .string "???10{END}"

    .global Unk_08210968
Unk_08210968:
    .string "???12{END}"

    .global Unk_0821096E
Unk_0821096E:
    .string "???13{END}"

    .global Unk_08210974
Unk_08210974:
    .string "???14{END}"

    .global Unk_0821097A
Unk_0821097A:
    .string "???15{END}"

    .global Unk_08210980
Unk_08210980:
    .string "???16{END}"

    .global Unk_08210986
Unk_08210986:
    .string "???17{END}"

    .global Unk_0821098C
Unk_0821098C:
    .string "TEngX{END}"

    .global Unk_08210992
Unk_08210992:
    .string "???18{END}"

    .global Unk_08210998
Unk_08210998:
    .string "???19{END}"

    .global Unk_0821099E
Unk_0821099E:
    .string "Bomb{END}"

    .global Unk_082109A3
Unk_082109A3:
    .string "Boom{END}"

    .global Unk_082109A8
Unk_082109A8:
    .string "Warp{END}"

    .global Unk_082109AD
Unk_082109AD:
    .string "Flucht{END}"

    .global Unk_082109B4
Unk_082109B4:
    .string "Blast{END}"

    .global Unk_082109BA
Unk_082109BA:
    .string "Ausg{END}"

    .global Unk_082109BF
Unk_082109BF:
    .string "Nova{END}"

    .global Unk_082109C4
Unk_082109C4:
    .string "NovaX{END}"

    .global Unk_082109CA
Unk_082109CA:
    .string "???20{END}"

    .global Unk_082109D0
Unk_082109D0:
    .string "???21{END}"

