    .global Unk_0820F44C
Unk_0820F44C:
    .string "Stellt 50 HP wieder her{END}"

    .global Unk_0820F464
Unk_0820F464:
    .string "Kurz bessere Verteidigung{END}"

    .global Unk_0820F47E
Unk_0820F47E:
    .string "Verlangsamt Gegner{END}"

    .global Unk_0820F491
Unk_0820F491:
    .string "Kurz mehr Glück{END}"

    .global Unk_0820F4A1
Unk_0820F4A1:
    .string "Kurz mehr Angriffskraft{END}"

    .global Unk_0820F4B9
Unk_0820F4B9:
    .string "Stellt 100 HP wieder her{END}"

    .global Unk_0820F4D2
Unk_0820F4D2:
    .string "Hält Gegnerbewegung an{END}"

    .global Unk_0820F4E9
Unk_0820F4E9:
    .string "Kurz bessere Agilität{END}"

    .global Unk_0820F4FF
Unk_0820F4FF:
    .string "T-Engel LV1 Einzelner Feind{END}"

    .global Unk_0820F51B
Unk_0820F51B:
    .string "Stellt 250 HP wieder her{END}"

    .global Unk_0820F534
Unk_0820F534:
    .string "Heilt Status “Btbt“ HP1{END}"

    .global Unk_0820F54C
Unk_0820F54C:
    .string "Heilt jeden abnormen Status{END}"

    .global Unk_0820F568
Unk_0820F568:
    .string "Weniger Schaden durch Magie{END}"

    .global Unk_0820F584
Unk_0820F584:
    .string "Heilt HP vollständig{END}"

    .global Unk_0820F599
Unk_0820F599:
    .string "T-Engel LV2 Einzelner Feind{END}"

    .global Unk_0820F5B5
Unk_0820F5B5:
    .string "Bessere Verteidigung Gruppe{END}"

    .global Unk_0820F5D1
Unk_0820F5D1:
    .string "Versiegelt kurz GegnerMagie{END}"

    .global Unk_0820F5ED
Unk_0820F5ED:
    .string "Verhindert 1 Mal Gegnermagie{END}"

    .global Unk_0820F60A
Unk_0820F60A:
    .string "Heilt Status “Btbt“ vollständig{END}"

    .global Unk_0820F62A
Unk_0820F62A:
    .string "Heilt Gruppen-HP um 250 Pkte{END}"

    .global Unk_0820F647
Unk_0820F647:
    .string "Reflektiert Gegnermagie 1 Mal{END}"

    .global Unk_0820F665
Unk_0820F665:
    .string "T-Engel LV3 Gegnergruppe{END}"

    .global Unk_0820F67E
Unk_0820F67E:
    .string "Feuer LV1 Einzelner Feind{END}"

    .global Unk_0820F698
Unk_0820F698:
    .string "Blitz LV1 Einzelner Feind{END}"

    .global Unk_0820F6B2
Unk_0820F6B2:
    .string "Eis LV1 Einzelner Feind{END}"

    .global Unk_0820F6CA
Unk_0820F6CA:
    .string "Beben LV1 Gegnergruppe{END}"

    .global Unk_0820F6E1
Unk_0820F6E1:
    .string "Stoppt Zeit des Gegners{END}"

    .global Unk_0820F6F9
Unk_0820F6F9:
    .string "Absorbiert HP vom Gegner{END}"

    .global Unk_0820F712
Unk_0820F712:
    .string "Todesstrafe Einzelner Feind{END}"

    .global Unk_0820F72E
Unk_0820F72E:
    .string "Feuer LV2 Einzelner Feind{END}"

    .global Unk_0820F748
Unk_0820F748:
    .string "Blitz LV2 Einzelner Feind{END}"

    .global Unk_0820F762
Unk_0820F762:
    .string "Eis LV2 Einzelner Feind{END}"

    .global Unk_0820F77A
Unk_0820F77A:
    .string "Beben LV2 Gegnergruppe{END}"

    .global Unk_0820F791
Unk_0820F791:
    .string "Feuer LV3 Einzelner Feind{END}"

    .global Unk_0820F7AB
Unk_0820F7AB:
    .string "Blitz LV4 Gegnergruppe{END}"

    .global Unk_0820F7C2
Unk_0820F7C2:
    .string "Eis LV3 Gegnergruppe{END}"

    .global Unk_0820F7D7
Unk_0820F7D7:
    .string "Beben LV3 Gegnergruppe{END}"

    .global Unk_0820F7EE
Unk_0820F7EE:
    .string "Blitz LV5 Gegnergruppe{END}"

    .global Unk_0820F805
Unk_0820F805:
    .string "Eis LV4 Gegnergruppe{END}"

    .global Unk_0820F81A
Unk_0820F81A:
    .string "Feuer LV5 Gegnergruppe{END}"

    .global Unk_0820F831
Unk_0820F831:
    .string "Eis LV5 Einzelner Feind{END}"

    .global Unk_0820F849
Unk_0820F849:
    .string "Feuer LV4 Einzelner Feind{END}"

    .global Unk_0820F863
Unk_0820F863:
    .string "Blitz LV3 Einzelner Feind{END}"

    .global Unk_0820F87D
Unk_0820F87D:
    .string "Absorbiert AP vom Gegner{END}"

    .global Unk_0820F896
Unk_0820F896:
    .string "Dummy{END}"

    .global Unk_0820F89C
Unk_0820F89C:
    .string "Meteoritensturm Gegnergruppe{END}"

    .global Unk_0820F8B9
Unk_0820F8B9:
    .string "Dummy{END}"

    .global Unk_0820F8BF
Unk_0820F8BF:
    .string "Dummy{END}"

    .global Unk_0820F8C5
Unk_0820F8C5:
    .string "Dummy{END}"

    .global Unk_0820F8CB
Unk_0820F8CB:
    .string "Dummy{END}"

    .global Unk_0820F8D1
Unk_0820F8D1:
    .string "Dummy{END}"

    .global Unk_0820F8D7
Unk_0820F8D7:
    .string "Dummy{END}"

    .global Unk_0820F8DD
Unk_0820F8DD:
    .string "Dummy{END}"

    .global Unk_0820F8E3
Unk_0820F8E3:
    .string "Heilt Status “Btbt“ vollständig{END}"

    .global Unk_0820F903
Unk_0820F903:
    .string "Unter Wasser im Kampf benutzt{END}"

    .global Unk_0820F921
Unk_0820F921:
    .string "Unter Wasser im Kampf benutzt{END}"

    .global Unk_0820F93F
Unk_0820F93F:
    .string "Unter Wasser im Kampf benutzt{END}"

    .global Unk_0820F95D
Unk_0820F95D:
    .string "Unter Wasser im Kampf benutzt{END}"

    .global Unk_0820F97B
Unk_0820F97B:
    .string "Dummy{END}"

    .global Unk_0820F981
Unk_0820F981:
    .string "Dummy{END}"

    .global Unk_0820F987
Unk_0820F987:
    .string "Dummy{END}"

    .global Unk_0820F98D
Unk_0820F98D:
    .string "Dummy{END}"

    .global Unk_0820F993
Unk_0820F993:
    .string "Dummy{END}"

    .global Unk_0820F999
Unk_0820F999:
    .string "Dummy{END}"

    .global Unk_0820F99F
Unk_0820F99F:
    .string "Dummy{END}"

    .global Unk_0820F9A5
Unk_0820F9A5:
    .string "Dummy{END}"

    .global Unk_0820F9AB
Unk_0820F9AB:
    .string "Dummy{END}"

    .global Unk_0820F9B1
Unk_0820F9B1:
    .string "Engel LV3 Gegnergruppe{END}"

    .global Unk_0820F9C8
Unk_0820F9C8:
    .string "Dummy{END}"

    .global Unk_0820F9CE
Unk_0820F9CE:
    .string "Dummy{END}"

    .global Unk_0820F9D4
Unk_0820F9D4:
    .string "Explosion LV1 Einzelner Feind{END}"

    .global Unk_0820F9F2
Unk_0820F9F2:
    .string "Explosion LV2 Gegnergruppe{END}"

    .global Unk_0820FA0D
Unk_0820FA0D:
    .string "Zu einer Stadt warpen{END}"

    .global Unk_0820FA23
Unk_0820FA23:
    .string "Aus dem Kampf fliehen{END}"

    .global Unk_0820FA39
Unk_0820FA39:
    .string "Explosion LV3 Einzelner Feind{END}"

    .global Unk_0820FA57
Unk_0820FA57:
    .string "Aus einem Dungeon fliehen{END}"

    .global Unk_0820FA71
Unk_0820FA71:
    .string "Explosion LV4 Gegnergruppe{END}"

    .global Unk_0820FA8C
Unk_0820FA8C:
    .string "Explosion LV5 Einzelner Feind{END}"

    .global Unk_0820FAAA
Unk_0820FAAA:
    .string "Dummy{END}"

    .global Unk_0820FAB0
Unk_0820FAB0:
    .string "Dummy{END}"

    .global Unk_0820FAB6
Unk_0820FAB6:
    .string "Gräbt Tunnel aus Kampf{END}"

    .global Unk_0820FACD
Unk_0820FACD:
    .string "Im Kampf benutzt{END}"

    .global Unk_0820FADE
Unk_0820FADE:
    .string "Charaktere fusionieren{END}"

    .global Unk_0820FAF5
Unk_0820FAF5:
    .string "Verfügbar unter Wasser{END}"

    .global Unk_0820FB0C
Unk_0820FB0C:
    .string "Verfügbar auf dem Land{END}"

    .global Unk_0820FB23
Unk_0820FB23:
    .string "Charaktere fusionieren{END}"

    .global Unk_0820FB3A
Unk_0820FB3A:
    .string "Fusion aufheben{END}"

    .global Unk_0820FB4A
Unk_0820FB4A:
    .string "Wieder Mensch{END}"

