    .global Unk_082100CC
Unk_082100CC:
    .string "Dolch{END}"

    .global Unk_082100D2
Unk_082100D2:
    .string "BronzSW{END}"

    .global Unk_082100DA
Unk_082100DA:
    .string "Säbel{END}"

    .global Unk_082100E0
Unk_082100E0:
    .string "Sense{END}"

    .global Unk_082100E6
Unk_082100E6:
    .string "LangSW{END}"

    .global Unk_082100ED
Unk_082100ED:
    .string "DrchnSW{END}"

    .global Unk_082100F5
Unk_082100F5:
    .string "PowerSW{END}"

    .global Unk_082100FD
Unk_082100FD:
    .string "FlügelSW{END}"

    .global Unk_08210106
Unk_08210106:
    .string "ImperSW{END}"

    .global Unk_0821010E
Unk_0821010E:
    .string "ZerbrSW{END}"

    .global Unk_08210116
Unk_08210116:
    .string "Dummy{END}"

    .global Unk_0821011C
Unk_0821011C:
    .string "FlammSW{END}"

    .global Unk_08210124
Unk_08210124:
    .string "Sichel{END}"

    .global Unk_0821012B
Unk_0821012B:
    .string "BreitSW{END}"

    .global Unk_08210133
Unk_08210133:
    .string "MystSW{END}"

    .global Unk_0821013A
Unk_0821013A:
    .string "SWaff{END}"

    .global Unk_08210140
Unk_08210140:
    .string "KurzRP{END}"

    .global Unk_08210147
Unk_08210147:
    .string "Rapier{END}"

    .global Unk_0821014E
Unk_0821014E:
    .string "EisnRP{END}"

    .global Unk_08210155
Unk_08210155:
    .string "GiftRP{END}"

    .global Unk_0821015C
Unk_0821015C:
    .string "LichtRP{END}"

    .global Unk_08210164
Unk_08210164:
    .string "Dummy{END}"

    .global Unk_0821016A
Unk_0821016A:
    .string "FlammRP{END}"

    .global Unk_08210172
Unk_08210172:
    .string "FlüglRP{END}"

    .global Unk_0821017A
Unk_0821017A:
    .string "BronzRP{END}"

    .global Unk_08210182
Unk_08210182:
    .string "TeuflRP{END}"

    .global Unk_0821018A
Unk_0821018A:
    .string "BlitzRP{END}"

    .global Unk_08210192
Unk_08210192:
    .string "Dummy{END}"

    .global Unk_08210198
Unk_08210198:
    .string "LoyalRP{END}"

    .global Unk_082101A0
Unk_082101A0:
    .string "PowerRP{END}"

    .global Unk_082101A8
Unk_082101A8:
    .string "EisnHR{END}"

    .global Unk_082101AF
Unk_082101AF:
    .string "StchlHR{END}"

    .global Unk_082101B7
Unk_082101B7:
    .string "Keule{END}"

    .global Unk_082101BD
Unk_082101BD:
    .string "RiesnHR{END}"

    .global Unk_082101C5
Unk_082101C5:
    .string "FlammHR{END}"

    .global Unk_082101CD
Unk_082101CD:
    .string "Dummy{END}"

    .global Unk_082101D3
Unk_082101D3:
    .string "WutHR{END}"

    .global Unk_082101D9
Unk_082101D9:
    .string "Dummy{END}"

    .global Unk_082101DF
Unk_082101DF:
    .string "Hammer{END}"

    .global Unk_082101E6
Unk_082101E6:
    .string "StrnHR{END}"

    .global Unk_082101ED
Unk_082101ED:
    .string "Stock{END}"

    .global Unk_082101F3
Unk_082101F3:
    .string "Prügel{END}"

    .global Unk_082101FA
Unk_082101FA:
    .string "KnchnPR{END}"

    .global Unk_08210202
Unk_08210202:
    .string "TeuflPR{END}"

    .global Unk_0821020A
Unk_0821020A:
    .string "Dummy{END}"

    .global Unk_08210210
Unk_08210210:
    .string "EisPR{END}"

    .global Unk_08210216
Unk_08210216:
    .string "Dummy{END}"

    .global Unk_0821021C
Unk_0821021C:
    .string "GlutPR{END}"

    .global Unk_08210223
Unk_08210223:
    .string "Dummy{END}"

    .global Unk_08210229
Unk_08210229:
    .string "Stab{END}"

    .global Unk_0821022E
Unk_0821022E:
    .string "Spieß{END}"

    .global Unk_08210234
Unk_08210234:
    .string "Speer{END}"

    .global Unk_0821023A
Unk_0821023A:
    .string "AltSP{END}"

    .global Unk_08210240
Unk_08210240:
    .string "HeldSP{END}"

    .global Unk_08210247
Unk_08210247:
    .string "Drzck{END}"

    .global Unk_0821024D
Unk_0821024D:
    .string "Dummy{END}"

    .global Unk_08210253
Unk_08210253:
    .string "Schlfr{END}"

    .global Unk_0821025A
Unk_0821025A:
    .string "Dummy{END}"

    .global Unk_08210260
Unk_08210260:
    .string "GrabKR{END}"

    .global Unk_08210267
Unk_08210267:
    .string "RostKR{END}"

    .global Unk_0821026E
Unk_0821026E:
    .string "EisnKR{END}"

    .global Unk_08210275
Unk_08210275:
    .string "EisKR{END}"

    .global Unk_0821027B
Unk_0821027B:
    .string "Dummy{END}"

    .global Unk_08210281
Unk_08210281:
    .string "MystKR{END}"

    .global Unk_08210288
Unk_08210288:
    .string "Dummy{END}"

    .global Unk_0821028E
Unk_0821028E:
    .string "WurfDL{END}"

    .global Unk_08210295
Unk_08210295:
    .string "Dolch{END}"

    .global Unk_0821029B
Unk_0821029B:
    .string "WSpieß{END}"

    .global Unk_082102A2
Unk_082102A2:
    .string "DrzkDL{END}"

    .global Unk_082102A9
Unk_082102A9:
    .string "PowerDL{END}"

    .global Unk_082102B1
Unk_082102B1:
    .string "FlammDL{END}"

    .global Unk_082102B9
Unk_082102B9:
    .string "SilberDL{END}"

    .global Unk_082102C2
Unk_082102C2:
    .string "Dummy{END}"

    .global Unk_082102C8
Unk_082102C8:
    .string "Dummy{END}"

    .global Unk_082102CE
Unk_082102CE:
    .string "EisDL{END}"

    .global Unk_082102D4
Unk_082102D4:
    .string "Dummy{END}"

    .global Unk_082102DA
Unk_082102DA:
    .string "DnklDL{END}"

    .global Unk_082102E1
Unk_082102E1:
    .string "Dummy{END}"

    .global Unk_082102E7
Unk_082102E7:
    .string "BronzBG{END}"

    .global Unk_082102EF
Unk_082102EF:
    .string "KurzBG{END}"

    .global Unk_082102F6
Unk_082102F6:
    .string "LangBG{END}"

    .global Unk_082102FD
Unk_082102FD:
    .string "StahlBG{END}"

    .global Unk_08210305
Unk_08210305:
    .string "GiftBG{END}"

    .global Unk_0821030C
Unk_0821030C:
    .string "SharfBG{END}"

    .global Unk_08210314
Unk_08210314:
    .string "MondBG{END}"

    .global Unk_0821031B
Unk_0821031B:
    .string "JadeBG{END}"

    .global Unk_08210322
Unk_08210322:
    .string "DrzkBG{END}"

    .global Unk_08210329
Unk_08210329:
    .string "Dummy{END}"

    .global Unk_0821032F
Unk_0821032F:
    .string "Dummy{END}"

    .global Unk_08210335
Unk_08210335:
    .string "Dummy{END}"

    .global Unk_0821033B
Unk_0821033B:
    .string "ZwrgBG{END}"

    .global Unk_08210342
Unk_08210342:
    .string "HeldBG{END}"

    .global Unk_08210349
Unk_08210349:
    .string "Dummy{END}"

    .global Unk_0821034F
Unk_0821034F:
    .string "BRang{END}"

    .global Unk_08210355
Unk_08210355:
    .string "WurfKl{END}"

    .global Unk_0821035C
Unk_0821035C:
    .string "DrRang{END}"

