    .global Unk_0820E76E
Unk_0820E76E:
    .string "{END}"

    .global Unk_0820E76F
Unk_0820E76F:
    .string "Drogen{END}"

    .global Unk_0820E776
Unk_0820E776:
    .string "Nanaï{END}"

    .global Unk_0820E77C
Unk_0820E77C:
    .string "Winlan{END}"

    .global Unk_0820E783
Unk_0820E783:
    .string "Roméro{END}"

    .global Unk_0820E78A
Unk_0820E78A:
    .string "Gust{END}"

    .global Unk_0820E78F
Unk_0820E78F:
    .string "Camlon{END}"

    .global Unk_0820E796
Unk_0820E796:
    .string "Nada{END}"

    .global Unk_0820E79B
Unk_0820E79B:
    .string "Tantar{END}"

    .global Unk_0820E7A2
Unk_0820E7A2:
    .string "Tuntar{END}"

    .global Unk_0820E7A9
Unk_0820E7A9:
    .string "Agua{END}"

    .global Unk_0820E7AE
Unk_0820E7AE:
    .string "Auria{END}"

    .global Unk_0820E7B4
Unk_0820E7B4:
    .string "Tryste{END}"

    .global Unk_0820E7BB
Unk_0820E7BB:
    .string "Arad{END}"

    .global Unk_0820E7C0
Unk_0820E7C0:
    .string "Prntemps{END}"

    .global Unk_0820E7C9
Unk_0820E7C9:
    .string "Tunlan{END}"

    .global Unk_0820E7D0
Unk_0820E7D0:
    .string "Gant{END}"

    .global Unk_0820E7D5
Unk_0820E7D5:
    .string "Scande{END}"

    .global Unk_0820E7DC
Unk_0820E7DC:
    .string "Carmen{END}"

    .global Unk_0820E7E3
Unk_0820E7E3:
    .string "Gramor{END}"

    .global Unk_0820E7EA
Unk_0820E7EA:
    .string "Wisdon{END}"

    .global Unk_0820E7F1
Unk_0820E7F1:
    .string "Karma{END}"

    .global Unk_0820E7F7
Unk_0820E7F7:
    .string "Prima{END}"

    .global Unk_0820E7FD
Unk_0820E7FD:
    .string "Crypte{END}"

    .global Unk_0820E804
Unk_0820E804:
    .string "Nabal{END}"

    .global Unk_0820E80A
Unk_0820E80A:
    .string "Tock{END}"

    .global Unk_0820E80F
Unk_0820E80F:
    .string "Cyme{END}"

    .global Unk_0820E814
Unk_0820E814:
    .string "Obélisq{END}"

    .global Unk_0820E81C
Unk_0820E81C:
    .string "Pagode{END}"

