    .global Unk_0820E34A
Unk_0820E34A:
    .string "Robe{END}"

    .global Unk_0820E34F
Unk_0820E34F:
    .string "CqDaim{END}"

    .global Unk_0820E356
Unk_0820E356:
    .string "RobeLèg{END}"

    .global Unk_0820E35E
Unk_0820E35E:
    .string "ArmMét{END}"

    .global Unk_0820E365
Unk_0820E365:
    .string "RobeSoie{END}"

    .global Unk_0820E36E
Unk_0820E36E:
    .string "Habits{END}"

    .global Unk_0820E375
Unk_0820E375:
    .string "HabLèg{END}"

    .global Unk_0820E37C
Unk_0820E37C:
    .string "RobeSoir{END}"

    .global Unk_0820E385
Unk_0820E385:
    .string "ArmPad{END}"

    .global Unk_0820E38C
Unk_0820E38C:
    .string "PeauLoup{END}"

    .global Unk_0820E395
Unk_0820E395:
    .string "ArmRôdr{END}"

    .global Unk_0820E39D
Unk_0820E39D:
    .string "ArmBronz{END}"

    .global Unk_0820E3A6
Unk_0820E3A6:
    .string "ArmPlaqu{END}"

    .global Unk_0820E3AF
Unk_0820E3AF:
    .string "Faux{END}"

    .global Unk_0820E3B4
Unk_0820E3B4:
    .string "ArmFeu{END}"

    .global Unk_0820E3BB
Unk_0820E3BB:
    .string "HabImmac{END}"

    .global Unk_0820E3C4
Unk_0820E3C4:
    .string "ArmuSp{END}"

    .global Unk_0820E3CB
Unk_0820E3CB:
    .string "ArmGl{END}"

    .global Unk_0820E3D1
Unk_0820E3D1:
    .string "MaillM{END}"

    .global Unk_0820E3D8
Unk_0820E3D8:
    .string "Faux{END}"

    .global Unk_0820E3DD
Unk_0820E3DD:
    .string "CapEp{END}"

    .global Unk_0820E3E3
Unk_0820E3E3:
    .string "CapVol{END}"

    .global Unk_0820E3EA
Unk_0820E3EA:
    .string "RobeMal{END}"

    .global Unk_0820E3F2
Unk_0820E3F2:
    .string "RobeVel{END}"

    .global Unk_0820E3FA
Unk_0820E3FA:
    .string "ArmDaim{END}"

    .global Unk_0820E402
Unk_0820E402:
    .string "CottMail{END}"

    .global Unk_0820E40B
Unk_0820E40B:
    .string "MaillFer{END}"

    .global Unk_0820E414
Unk_0820E414:
    .string "RobLaine{END}"

    .global Unk_0820E41D
Unk_0820E41D:
    .string "RobeDaim{END}"

    .global Unk_0820E426
Unk_0820E426:
    .string "ArmVie{END}"

    .global Unk_0820E42D
Unk_0820E42D:
    .string "ArmPuis{END}"

    .global Unk_0820E435
Unk_0820E435:
    .string "ArmQrtz{END}"

    .global Unk_0820E43D
Unk_0820E43D:
    .string "ArmAngle{END}"

    .global Unk_0820E446
Unk_0820E446:
    .string "Faux{END}"

    .global Unk_0820E44B
Unk_0820E44B:
    .string "MantGour{END}"

    .global Unk_0820E454
Unk_0820E454:
    .string "Faux{END}"

    .global Unk_0820E459
Unk_0820E459:
    .string "Faux{END}"

    .global Unk_0820E45E
Unk_0820E45E:
    .string "ArmMond{END}"

    .global Unk_0820E466
Unk_0820E466:
    .string "ArmSage{END}"

    .global Unk_0820E46E
Unk_0820E46E:
    .string "Faux{END}"

    .global Unk_0820E473
Unk_0820E473:
    .string "RobeMyst{END}"

    .global Unk_0820E47C
Unk_0820E47C:
    .string "RobeTer{END}"

    .global Unk_0820E484
Unk_0820E484:
    .string "Faux{END}"

    .global Unk_0820E489
Unk_0820E489:
    .string "ArmAg{END}"

    .global Unk_0820E48F
Unk_0820E48F:
    .string "Faux{END}"

    .global Unk_0820E494
Unk_0820E494:
    .string "CapChass{END}"

    .global Unk_0820E49D
Unk_0820E49D:
    .string "CapClair{END}"

    .global Unk_0820E4A6
Unk_0820E4A6:
    .string "Faux{END}"

    .global Unk_0820E4AB
Unk_0820E4AB:
    .string "BoucBois{END}"

    .global Unk_0820E4B4
Unk_0820E4B4:
    .string "Gantelet{END}"

    .global Unk_0820E4BD
Unk_0820E4BD:
    .string "BoucDaim{END}"

    .global Unk_0820E4C6
Unk_0820E4C6:
    .string "BoucGard{END}"

    .global Unk_0820E4CF
Unk_0820E4CF:
    .string "Bracelet{END}"

    .global Unk_0820E4D8
Unk_0820E4D8:
    .string "BoucFer{END}"

    .global Unk_0820E4E0
Unk_0820E4E0:
    .string "BoucBrnz{END}"

    .global Unk_0820E4E9
Unk_0820E4E9:
    .string "BoucMét{END}"

    .global Unk_0820E4F1
Unk_0820E4F1:
    .string "BoucFeu{END}"

    .global Unk_0820E4F9
Unk_0820E4F9:
    .string "Faux{END}"

    .global Unk_0820E4FE
Unk_0820E4FE:
    .string "PetBouc{END}"

    .global Unk_0820E506
Unk_0820E506:
    .string "EcuFer{END}"

    .global Unk_0820E50D
Unk_0820E50D:
    .string "EcuMét{END}"

    .global Unk_0820E514
Unk_0820E514:
    .string "Faux{END}"

    .global Unk_0820E519
Unk_0820E519:
    .string "Poignet{END}"

    .global Unk_0820E521
Unk_0820E521:
    .string "BoucGl{END}"

    .global Unk_0820E528
Unk_0820E528:
    .string "BoucPro{END}"

    .global Unk_0820E530
Unk_0820E530:
    .string "BracAmr{END}"

    .global Unk_0820E538
Unk_0820E538:
    .string "BracVent{END}"

    .global Unk_0820E541
Unk_0820E541:
    .string "AnnRubis{END}"

    .global Unk_0820E54A
Unk_0820E54A:
    .string "Faux{END}"

    .global Unk_0820E54F
Unk_0820E54F:
    .string "BracNoir{END}"

    .global Unk_0820E558
Unk_0820E558:
    .string "Faux{END}"

    .global Unk_0820E55D
Unk_0820E55D:
    .string "BoucMyst{END}"

    .global Unk_0820E566
Unk_0820E566:
    .string "Gant{END}"

    .global Unk_0820E56B
Unk_0820E56B:
    .string "Faux{END}"

    .global Unk_0820E570
Unk_0820E570:
    .string "PiègeGar{END}"

    .global Unk_0820E579
Unk_0820E579:
    .string "BoucLèg{END}"

    .global Unk_0820E581
Unk_0820E581:
    .string "AnnMag{END}"

    .global Unk_0820E588
Unk_0820E588:
    .string "Bandage{END}"

    .global Unk_0820E590
Unk_0820E590:
    .string "Faux{END}"

    .global Unk_0820E595
Unk_0820E595:
    .string "BracArg{END}"

    .global Unk_0820E59D
Unk_0820E59D:
    .string "Faux{END}"

    .global Unk_0820E5A2
Unk_0820E5A2:
    .string "BoucFrd{END}"

    .global Unk_0820E5AA
Unk_0820E5AA:
    .string "GantChas{END}"

    .global Unk_0820E5B3
Unk_0820E5B3:
    .string "BoucMasq{END}"

    .global Unk_0820E5BC
Unk_0820E5BC:
    .string "BoucDrag{END}"

    .global Unk_0820E5C5
Unk_0820E5C5:
    .string "Faux{END}"

    .global Unk_0820E5CA
Unk_0820E5CA:
    .string "BoucLave{END}"

    .global Unk_0820E5D3
Unk_0820E5D3:
    .string "Faux{END}"

    .global Unk_0820E5D8
Unk_0820E5D8:
    .string "CasqDaim{END}"

    .global Unk_0820E5E1
Unk_0820E5E1:
    .string "Viseur{END}"

    .global Unk_0820E5E8
Unk_0820E5E8:
    .string "Bandeau{END}"

    .global Unk_0820E5F0
Unk_0820E5F0:
    .string "Tiare{END}"

    .global Unk_0820E5F6
Unk_0820E5F6:
    .string "BndChaîn{END}"

    .global Unk_0820E5FF
Unk_0820E5FF:
    .string "TiareOr{END}"

    .global Unk_0820E607
Unk_0820E607:
    .string "CasqEcho{END}"

    .global Unk_0820E610
Unk_0820E610:
    .string "MasqFer{END}"

    .global Unk_0820E618
Unk_0820E618:
    .string "Faux{END}"

    .global Unk_0820E61D
Unk_0820E61D:
    .string "Faux{END}"

    .global Unk_0820E622
Unk_0820E622:
    .string "CasqPier{END}"

    .global Unk_0820E62B
Unk_0820E62B:
    .string "CasqOr{END}"

    .global Unk_0820E632
Unk_0820E632:
    .string "MasFacia{END}"

    .global Unk_0820E63B
Unk_0820E63B:
    .string "CasAgil{END}"

    .global Unk_0820E643
Unk_0820E643:
    .string "JolieCsq{END}"

    .global Unk_0820E64C
Unk_0820E64C:
    .string "SfMyst{END}"

    .global Unk_0820E653
Unk_0820E653:
    .string "CasqPlng{END}"

    .global Unk_0820E65C
Unk_0820E65C:
    .string "MasqGaia{END}"

    .global Unk_0820E665
Unk_0820E665:
    .string "CouvreCh{END}"

    .global Unk_0820E66E
Unk_0820E66E:
    .string "CasqMaud{END}"

    .global Unk_0820E677
Unk_0820E677:
    .string "CasCoqui{END}"

    .global Unk_0820E680
Unk_0820E680:
    .string "CasqPail{END}"

    .global Unk_0820E689
Unk_0820E689:
    .string "CasqFer{END}"

    .global Unk_0820E691
Unk_0820E691:
    .string "Faux{END}"

    .global Unk_0820E696
Unk_0820E696:
    .string "CasqMaré{END}"

    .global Unk_0820E69F
Unk_0820E69F:
    .string "CasqCrân{END}"

    .global Unk_0820E6A8
Unk_0820E6A8:
    .string "CasqPuis{END}"

    .global Unk_0820E6B1
Unk_0820E6B1:
    .string "Domino{END}"

    .global Unk_0820E6B8
Unk_0820E6B8:
    .string "CasCorn{END}"

    .global Unk_0820E6C0
Unk_0820E6C0:
    .string "Bandana{END}"

    .global Unk_0820E6C8
Unk_0820E6C8:
    .string "Turban{END}"

    .global Unk_0820E6CF
Unk_0820E6CF:
    .string "Faux{END}"

    .global Unk_0820E6D4
Unk_0820E6D4:
    .string "CasqAmr{END}"

    .global Unk_0820E6DC
Unk_0820E6DC:
    .string "Faux{END}"

    .global Unk_0820E6E1
Unk_0820E6E1:
    .string "Faux{END}"

    .global Unk_0820E6E6
Unk_0820E6E6:
    .string "Faux{END}"

    .global Unk_0820E6EB
Unk_0820E6EB:
    .string "CasqBrnz{END}"

    .global Unk_0820E6F4
Unk_0820E6F4:
    .string "CasqSp{END}"

    .global Unk_0820E6FB
Unk_0820E6FB:
    .string "CasqSol{END}"

    .global Unk_0820E703
Unk_0820E703:
    .string "CasqLoup{END}"

    .global Unk_0820E70C
Unk_0820E70C:
    .string "CasqGl{END}"

    .global Unk_0820E713
Unk_0820E713:
    .string "Faux{END}"

    .global Unk_0820E718
Unk_0820E718:
    .string "Faux{END}"

    .global Unk_0820E71D
Unk_0820E71D:
    .string "Faux{END}"

    .global Unk_0820E722
Unk_0820E722:
    .string "CasqEtoi{END}"

    .global Unk_0820E72B
Unk_0820E72B:
    .string "Faux{END}"

    .global Unk_0820E730
Unk_0820E730:
    .string "AnnCrâne{END}"

    .global Unk_0820E739
Unk_0820E739:
    .string "BoucCiel{END}"

    .global Unk_0820E742
Unk_0820E742:
    .string "Faux{END}"

    .global Unk_0820E747
Unk_0820E747:
    .string "Faux{END}"

    .global Unk_0820E74C
Unk_0820E74C:
    .string "CasqDrag{END}"

    .global Unk_0820E755
Unk_0820E755:
    .string "ArmDrag{END}"

    .global Unk_0820E75D
Unk_0820E75D:
    .string "AnnIntel{END}"

    .global Unk_0820E766
Unk_0820E766:
    .string "AnnRêve{END}"

