    .global Unk_0820D0AD
Unk_0820D0AD:
    .string "Gren{END}"

    .global Unk_0820D0B2
Unk_0820D0B2:
    .string "Chev{END}"

    .global Unk_0820D0B7
Unk_0820D0B7:
    .string "Mag{END}"

    .global Unk_0820D0BB
Unk_0820D0BB:
    .string "Mag{END}"

    .global Unk_0820D0BF
Unk_0820D0BF:
    .string "Mag{END}"

    .global Unk_0820D0C3
Unk_0820D0C3:
    .string "Puce{END}"

    .global Unk_0820D0C8
Unk_0820D0C8:
    .string "Oiseau{END}"

    .global Unk_0820D0CF
Unk_0820D0CF:
    .string "Perch{END}"

    .global Unk_0820D0D5
Unk_0820D0D5:
    .string "Triste{END}"

    .global Unk_0820D0DC
Unk_0820D0DC:
    .string "Bec{END}"

    .global Unk_0820D0E0
Unk_0820D0E0:
    .string "Frisse{END}"

    .global Unk_0820D0E7
Unk_0820D0E7:
    .string "Zard{END}"

    .global Unk_0820D0EC
Unk_0820D0EC:
    .string "Mort{END}"

    .global Unk_0820D0F1
Unk_0820D0F1:
    .string "Mortéa{END}"

    .global Unk_0820D0F8
Unk_0820D0F8:
    .string "Serre{END}"

    .global Unk_0820D0FE
Unk_0820D0FE:
    .string "Bain{END}"

    .global Unk_0820D103
Unk_0820D103:
    .string "Général{END}"

    .global Unk_0820D10B
Unk_0820D10B:
    .string "Gremlin{END}"

    .global Unk_0820D113
Unk_0820D113:
    .string "Follet{END}"

    .global Unk_0820D11A
Unk_0820D11A:
    .string "Pog{END}"

    .global Unk_0820D11E
Unk_0820D11E:
    .string "Zombi{END}"

    .global Unk_0820D124
Unk_0820D124:
    .string "Vase{END}"

    .global Unk_0820D129
Unk_0820D129:
    .string "CavS{END}"

    .global Unk_0820D12E
Unk_0820D12E:
    .string "Blob{END}"

    .global Unk_0820D133
Unk_0820D133:
    .string "Lancier{END}"

    .global Unk_0820D13B
Unk_0820D13B:
    .string "Archer{END}"

    .global Unk_0820D142
Unk_0820D142:
    .string "Ruga{END}"

    .global Unk_0820D147
Unk_0820D147:
    .string "CochGuer{END}"

    .global Unk_0820D150
Unk_0820D150:
    .string "BlobAme{END}"

    .global Unk_0820D158
Unk_0820D158:
    .string "Bulla{END}"

    .global Unk_0820D15E
Unk_0820D15E:
    .string "Cafard{END}"

    .global Unk_0820D165
Unk_0820D165:
    .string "MoucheG{END}"

    .global Unk_0820D16D
Unk_0820D16D:
    .string "Espoeil{END}"

    .global Unk_0820D175
Unk_0820D175:
    .string "Octo{END}"

    .global Unk_0820D17A
Unk_0820D17A:
    .string "Poulpe{END}"

    .global Unk_0820D181
Unk_0820D181:
    .string "VerSab{END}"

    .global Unk_0820D188
Unk_0820D188:
    .string "Nuage{END}"

    .global Unk_0820D18E
Unk_0820D18E:
    .string "Scorp{END}"

    .global Unk_0820D194
Unk_0820D194:
    .string "Mage{END}"

    .global Unk_0820D199
Unk_0820D199:
    .string "Gratte{END}"

    .global Unk_0820D1A0
Unk_0820D1A0:
    .string "TirArc{END}"

    .global Unk_0820D1A7
Unk_0820D1A7:
    .string "Mouche{END}"

    .global Unk_0820D1AE
Unk_0820D1AE:
    .string "fantas{END}"

    .global Unk_0820D1B5
Unk_0820D1B5:
    .string "Créon{END}"

    .global Unk_0820D1BB
Unk_0820D1BB:
    .string "Chev{END}"

    .global Unk_0820D1C0
Unk_0820D1C0:
    .string "Mothro{END}"

    .global Unk_0820D1C7
Unk_0820D1C7:
    .string "Mote{END}"

    .global Unk_0820D1CC
Unk_0820D1CC:
    .string "Soldat{END}"

    .global Unk_0820D1D3
Unk_0820D1D3:
    .string "Tristev{END}"

    .global Unk_0820D1DB
Unk_0820D1DB:
    .string "Pinceur{END}"

    .global Unk_0820D1E3
Unk_0820D1E3:
    .string "VaseX{END}"

    .global Unk_0820D1E9
Unk_0820D1E9:
    .string "Brüm{END}"

    .global Unk_0820D1EE
Unk_0820D1EE:
    .string "VaseR{END}"

    .global Unk_0820D1F4
Unk_0820D1F4:
    .string "Poisse{END}"

    .global Unk_0820D1FB
Unk_0820D1FB:
    .string "PoissCh{END}"

    .global Unk_0820D203
Unk_0820D203:
    .string "Nain{END}"

    .global Unk_0820D208
Unk_0820D208:
    .string "Tronc{END}"

    .global Unk_0820D20E
Unk_0820D20E:
    .string "NSable{END}"

    .global Unk_0820D215
Unk_0820D215:
    .string "Tentac{END}"

    .global Unk_0820D21C
Unk_0820D21C:
    .string "ScorpM{END}"

    .global Unk_0820D223
Unk_0820D223:
    .string "RugaX{END}"

    .global Unk_0820D229
Unk_0820D229:
    .string "LancierX{END}"

    .global Unk_0820D232
Unk_0820D232:
    .string "ArcherX{END}"

    .global Unk_0820D23A
Unk_0820D23A:
    .string "AmePeine{END}"

    .global Unk_0820D243
Unk_0820D243:
    .string "RugaX{END}"

    .global Unk_0820D249
Unk_0820D249:
    .string "FleurX{END}"

    .global Unk_0820D250
Unk_0820D250:
    .string "CrapCor{END}"

    .global Unk_0820D258
Unk_0820D258:
    .string "Mote{END}"

    .global Unk_0820D25D
Unk_0820D25D:
    .string "Cerl{END}"

    .global Unk_0820D262
Unk_0820D262:
    .string "Mothro{END}"

    .global Unk_0820D269
Unk_0820D269:
    .string "InsP{END}"

    .global Unk_0820D26E
Unk_0820D26E:
    .string "Chimère{END}"

    .global Unk_0820D276
Unk_0820D276:
    .string "Thalle{END}"

    .global Unk_0820D27D
Unk_0820D27D:
    .string "Volant{END}"

    .global Unk_0820D284
Unk_0820D284:
    .string "Cafard{END}"

    .global Unk_0820D28B
Unk_0820D28B:
    .string "Phénix{END}"

    .global Unk_0820D292
Unk_0820D292:
    .string "Mortéo{END}"

    .global Unk_0820D299
Unk_0820D299:
    .string "Sorcier{END}"

    .global Unk_0820D2A1
Unk_0820D2A1:
    .string "Crapaud{END}"

    .global Unk_0820D2A9
Unk_0820D2A9:
    .string "Roublard{END}"

    .global Unk_0820D2B2
Unk_0820D2B2:
    .string "Goda{END}"

    .global Unk_0820D2B7
Unk_0820D2B7:
    .string "Zog{END}"

    .global Unk_0820D2BB
Unk_0820D2BB:
    .string "Jade{END}"

    .global Unk_0820D2C0
Unk_0820D2C0:
    .string "Déesse{END}"

    .global Unk_0820D2C7
Unk_0820D2C7:
    .string "Déesse{END}"

    .global Unk_0820D2CE
Unk_0820D2CE:
    .string "Sara{END}"

    .global Unk_0820D2D3
Unk_0820D2D3:
    .string "MageGuerre{END}"

    .global Unk_0820D2DE
Unk_0820D2DE:
    .string "Zoom{END}"

    .global Unk_0820D2E3
Unk_0820D2E3:
    .string "Gargouille{END}"

    .global Unk_0820D2EE
Unk_0820D2EE:
    .string "ChevG{END}"

    .global Unk_0820D2F4
Unk_0820D2F4:
    .string "Ombre{END}"

    .global Unk_0820D2FA
Unk_0820D2FA:
    .string "AmePeineX{END}"

    .global Unk_0820D304
Unk_0820D304:
    .string "Araignée{END}"

    .global Unk_0820D30D
Unk_0820D30D:
    .string "Foyer{END}"

    .global Unk_0820D313
Unk_0820D313:
    .string "Golem{END}"

    .global Unk_0820D319
Unk_0820D319:
    .string "Coffre{END}"

    .global Unk_0820D320
Unk_0820D320:
    .string "Déesse{END}"

    .global Unk_0820D327
Unk_0820D327:
    .string "PuceD{END}"

    .global Unk_0820D32D
Unk_0820D32D:
    .string "Crabe{END}"

    .global Unk_0820D333
Unk_0820D333:
    .string "Fleur{END}"

    .global Unk_0820D339
Unk_0820D339:
    .string "VaseG{END}"

    .global Unk_0820D33F
Unk_0820D33F:
    .string "VaseM{END}"

    .global Unk_0820D345
Unk_0820D345:
    .string "Bourdon{END}"

    .global Unk_0820D34D
Unk_0820D34D:
    .string "Rampant{END}"

    .global Unk_0820D355
Unk_0820D355:
    .string "Ruga{END}"

    .global Unk_0820D35A
Unk_0820D35A:
    .string "Ronk{END}"

    .global Unk_0820D35F
Unk_0820D35F:
    .string "PoisChX{END}"

    .global Unk_0820D367
Unk_0820D367:
    .string "FoyerX{END}"

    .global Unk_0820D36E
Unk_0820D36E:
    .string "BlobAmeX{END}"

    .global Unk_0820D377
Unk_0820D377:
    .string "Nautile{END}"

    .global Unk_0820D37F
Unk_0820D37F:
    .string "Veuve{END}"

    .global Unk_0820D385
Unk_0820D385:
    .string "PuceM{END}"

    .global Unk_0820D38B
Unk_0820D38B:
    .string "RampantX{END}"

    .global Unk_0820D394
Unk_0820D394:
    .string "Mimique{END}"

    .global Unk_0820D39C
Unk_0820D39C:
    .string "CochGuerX{END}"

    .global Unk_0820D3A6
Unk_0820D3A6:
    .string "TêteFeu{END}"

    .global Unk_0820D3AE
Unk_0820D3AE:
    .string "Brute{END}"

    .global Unk_0820D3B4
Unk_0820D3B4:
    .string "Griffe{END}"

    .global Unk_0820D3BB
Unk_0820D3BB:
    .string "PinceurX{END}"

    .global Unk_0820D3C4
Unk_0820D3C4:
    .string "CréonX{END}"

    .global Unk_0820D3CB
Unk_0820D3CB:
    .string "Bain{END}"

    .global Unk_0820D3D0
Unk_0820D3D0:
    .string "CavD{END}"

    .global Unk_0820D3D5
Unk_0820D3D5:
    .string "Goule{END}"

    .global Unk_0820D3DB
Unk_0820D3DB:
    .string "Cactus{END}"

    .global Unk_0820D3E2
Unk_0820D3E2:
    .string "CactusX{END}"

    .global Unk_0820D3EA
Unk_0820D3EA:
    .string "UCI{END}"

    .global Unk_0820D3EE
Unk_0820D3EE:
    .string "Entité{END}"

    .global Unk_0820D3F5
Unk_0820D3F5:
    .string "ChevD{END}"

