    .global Unk_0820C9D8
Unk_0820C9D8:
    .string "Lorsque la Famille du Dragon\n"
    .string "était à son apogée,\n"
    .string "la déesse du Désir apparut.\n"
    .string "\n"
    .string "Cette déesse, du nom de Tyr,\n"
    .string "accordait des souhaits, et\n"
    .string "les Dragons se sont \n"
    .string "affrontés pour en bénéficier.{END}"

    .global Unk_0820CA91
Unk_0820CA91:
    .string "Tyr encouragea les combats,\n"
    .string "spectatrice de l'escalade du\n"
    .string "conflit entre les Dragons.\n"
    .string "\n"
    .string "Quand le monde fut aux\n"
    .string "portes de la destruction,\n"
    .string "un guerrier apparu.{END}"

    .global Unk_0820CB2B
Unk_0820CB2B:
    .string "Aidé de ses 7 compagnons,\n"
    .string "il affronta et vainquit Tyr,\n"
    .string "qu'il enferma grâce à 6 clés\n"
    .string "\n"
    .string "Ces “Clés de la Déesse“\n"
    .string "furent par la suite\n"
    .string "éparpillées et cachées.{END}"

    .global Unk_0820CBC4
Unk_0820CBC4:
    .string "Les Dragons de Lumière\n"
    .string "ramenèrent le calme\n"
    .string "et la paix revint.{END}"

    .global Unk_0820CC02
Unk_0820CC02:
    .string "Les gens vivent et meurent,\n"
    .string "innombrables comme les\n"
    .string "étoiles fugaces\n"
    .string "telle l'écume qui apparaît\n"
    .string "au faîte des vagues.{END}"

    .global Unk_0820CC75
Unk_0820CC75:
    .string "Pourquoi venons-nous en\n"
    .string "ce monde s'il nous\n"
    .string "faut le quitter si\n"
    .string "rapidement ?{END}"

    .global Unk_0820CCC0
Unk_0820CCC0:
    .string "A l'échelle cosmique, la\n"
    .string "vie humaine ne dure pas plus\n"
    .string "qu'un battement de cil.{END}"

    .global Unk_0820CD0E
Unk_0820CD0E:
    .string "Le Clan du Dragon fonda\n"
    .string "un puissant empire puis\n"
    .string "s'effondra, disparaissant\n"
    .string "aussi vite qu'une comète.{END}"

    .global Unk_0820CD72
Unk_0820CD72:
    .string "Durant leur court règne,\n"
    .string "les Dragons se livrèrent des\n"
    .string "combats vides de sens,\n"
    .string "en quête de rêves qui\n"
    .string "l'étaient tout autant.{END}"

    .global Unk_0820CDEC
Unk_0820CDEC:
    .string "Et aujourd'hui, émerge une\n"
    .string "force inquiétante qui semble\n"
    .string "vouloir perpétrer le cycle.{END}"

    .global Unk_0820CE40
Unk_0820CE40:
    .string "Cette nouvelle menace\n"
    .string "a pour nom clan des Dragons\n"
    .string "Noirs.{END}"

    .global Unk_0820CE79
Unk_0820CE79:
    .string "Oubliant que les Dragons\n"
    .string "ont failli ravager la\n"
    .string "terre entière,{END}"

    .global Unk_0820CEB7
Unk_0820CEB7:
    .string "les Dragons Noirs plongent\n"
    .string "une nouvelle fois le\n"
    .string "monde dans le chaos.{END}"

    .global Unk_0820CEFC
Unk_0820CEFC:
    .string "Faisant usage de pouvoirs\n"
    .string "obtenus d'une mystérieuse\n"
    .string "déesse, ils partent à\n"
    .string "la conquête du globe.{END}"

    .global Unk_0820CF5C
Unk_0820CF5C:
    .string "Qui est cette puissance des\n"
    .string "ténèbres qui accorde leurs\n"
    .string "voeux aux forces du mal ?{END}"

    .global Unk_0820CFAD
Unk_0820CFAD:
    .string "Les Dragons de Lumière\n"
    .string "reviendront-ils pour ramener\n"
    .string "la paix une fois encore ?{END}"

    .global Unk_0820CFFB
Unk_0820CFFB:
    .string "La progression des Dragons\n"
    .string "Noirs est implacable.{END}"

    .global Unk_0820D02C
Unk_0820D02C:
    .string "Avant que le monde ne tombe\n"
    .string "entre leurs mains,{END}"

    .global Unk_0820D05B
Unk_0820D05B:
    .string "Avant que la déesse ne\n"
    .string "revienne à la vie,{END}"

    .global Unk_0820D085
Unk_0820D085:
    .string "les Dragons de Lumière\n"
    .string "doivent réagir !{END}"

