    .global Unk_0820DD59
Unk_0820DD59:
    .string "70 GP{END}"

    .global Unk_0820DD5F
Unk_0820DD5F:
    .string "150 GP{END}"

    .global Unk_0820DD66
Unk_0820DD66:
    .string "300 GP{END}"

    .global Unk_0820DD6D
Unk_0820DD6D:
    .string "650 GP{END}"

    .global Unk_0820DD74
Unk_0820DD74:
    .string "900 GP{END}"

    .global Unk_0820DD7B
Unk_0820DD7B:
    .string "1200 GP{END}"

    .global Unk_0820DD83
Unk_0820DD83:
    .string "2000 GP{END}"

    .global Unk_0820DD8B
Unk_0820DD8B:
    .string "3000 GP{END}"

    .global Unk_0820DD93
Unk_0820DD93:
    .string "Herbe{END}"

    .global Unk_0820DD99
Unk_0820DD99:
    .string "Soin{END}"

    .global Unk_0820DD9E
Unk_0820DD9E:
    .string "Fourmi{END}"

    .global Unk_0820DDA5
Unk_0820DDA5:
    .string "Gland{END}"

    .global Unk_0820DDAB
Unk_0820DDAB:
    .string "Déjec{END}"

    .global Unk_0820DDB1
Unk_0820DDB1:
    .string "Larme{END}"

    .global Unk_0820DDB7
Unk_0820DDB7:
    .string "Charme{END}"

    .global Unk_0820DDBE
Unk_0820DDBE:
    .string "Vie2{END}"

    .global Unk_0820DDC3
Unk_0820DDC3:
    .string "Bille1{END}"

    .global Unk_0820DDCA
Unk_0820DDCA:
    .string "Bille2{END}"

    .global Unk_0820DDD1
Unk_0820DDD1:
    .string "Bille3{END}"

    .global Unk_0820DDD8
Unk_0820DDD8:
    .string "Moust{END}"

    .global Unk_0820DDDE
Unk_0820DDDE:
    .string "Ver{END}"

    .global Unk_0820DDE2
Unk_0820DDE2:
    .string "Ver2{END}"

    .global Unk_0820DDE7
Unk_0820DDE7:
    .string "Crev{END}"

    .global Unk_0820DDEC
Unk_0820DDEC:
    .string "Oursin{END}"

    .global Unk_0820DDF3
Unk_0820DDF3:
    .string "Coquill{END}"

    .global Unk_0820DDFB
Unk_0820DDFB:
    .string "Pomme{END}"

    .global Unk_0820DE01
Unk_0820DE01:
    .string "ProtA{END}"

    .global Unk_0820DE07
Unk_0820DE07:
    .string "Bois{END}"

    .global Unk_0820DE0C
Unk_0820DE0C:
    .string "ViandeB{END}"

    .global Unk_0820DE14
Unk_0820DE14:
    .string "Vie{END}"

    .global Unk_0820DE18
Unk_0820DE18:
    .string "Ongles{END}"

    .global Unk_0820DE1F
Unk_0820DE1F:
    .string "Viande{END}"

    .global Unk_0820DE26
Unk_0820DE26:
    .string "StnB{END}"

    .global Unk_0820DE2B
Unk_0820DE2B:
    .string "StnF{END}"

    .global Unk_0820DE30
Unk_0820DE30:
    .string "StnC{END}"

    .global Unk_0820DE35
Unk_0820DE35:
    .string "Fumée{END}"

    .global Unk_0820DE3B
Unk_0820DE3B:
    .string "BaiserN{END}"

    .global Unk_0820DE43
Unk_0820DE43:
    .string "Soins2{END}"

    .global Unk_0820DE4A
Unk_0820DE4A:
    .string "ProtB{END}"

    .global Unk_0820DE50
Unk_0820DE50:
    .string "Echarp{END}"

    .global Unk_0820DE57
Unk_0820DE57:
    .string "PtnW{END}"

    .global Unk_0820DE5C
Unk_0820DE5C:
    .string "PtnS{END}"

    .global Unk_0820DE61
Unk_0820DE61:
    .string "Sablier{END}"

    .global Unk_0820DE69
Unk_0820DE69:
    .string "InsExp{END}"

    .global Unk_0820DE70
Unk_0820DE70:
    .string "Table{END}"

    .global Unk_0820DE76
Unk_0820DE76:
    .string "MonteCh{END}"

    .global Unk_0820DE7E
Unk_0820DE7E:
    .string "CléE{END}"

    .global Unk_0820DE83
Unk_0820DE83:
    .string "EauCal{END}"

    .global Unk_0820DE8A
Unk_0820DE8A:
    .string "Carros{END}"

    .global Unk_0820DE91
Unk_0820DE91:
    .string "Bloc{END}"

    .global Unk_0820DE96
Unk_0820DE96:
    .string "PtnA{END}"

    .global Unk_0820DE9B
Unk_0820DE9B:
    .string "PtnL{END}"

    .global Unk_0820DEA0
Unk_0820DEA0:
    .string "PtnV{END}"

    .global Unk_0820DEA5
Unk_0820DEA5:
    .string "AmeNr{END}"

    .global Unk_0820DEAB
Unk_0820DEAB:
    .string "Télép{END}"

    .global Unk_0820DEB1
Unk_0820DEB1:
    .string "Placéb{END}"

    .global Unk_0820DEB8
Unk_0820DEB8:
    .string "Remède{END}"

    .global Unk_0820DEBF
Unk_0820DEBF:
    .string "Jarre{END}"

    .global Unk_0820DEC5
Unk_0820DEC5:
    .string "Scie{END}"

    .global Unk_0820DECA
Unk_0820DECA:
    .string "Tablette{END}"

    .global Unk_0820DED3
Unk_0820DED3:
    .string "Anneau{END}"

    .global Unk_0820DEDA
Unk_0820DEDA:
    .string "Jarre{0x1A}{END}"

    .global Unk_0820DEE1
Unk_0820DEE1:
    .string "CléRoi{END}"

    .global Unk_0820DEE8
Unk_0820DEE8:
    .string "Papier{END}"

    .global Unk_0820DEEF
Unk_0820DEEF:
    .string "Voeu{END}"

    .global Unk_0820DEF4
Unk_0820DEF4:
    .string "Bourse{END}"

    .global Unk_0820DEFB
Unk_0820DEFB:
    .string "Poudre{END}"

    .global Unk_0820DF02
Unk_0820DF02:
    .string "CléL{END}"

    .global Unk_0820DF07
Unk_0820DF07:
    .string "CléN{END}"

    .global Unk_0820DF0C
Unk_0820DF0C:
    .string "Miroir{END}"

    .global Unk_0820DF13
Unk_0820DF13:
    .string "Livre{END}"

    .global Unk_0820DF19
Unk_0820DF19:
    .string "Sardine{END}"

    .global Unk_0820DF21
Unk_0820DF21:
    .string "Maqureau{END}"

    .global Unk_0820DF2A
Unk_0820DF2A:
    .string "Sole{END}"

    .global Unk_0820DF2F
Unk_0820DF2F:
    .string "Truite{END}"

    .global Unk_0820DF36
Unk_0820DF36:
    .string "Ecrev{END}"

    .global Unk_0820DF3C
Unk_0820DF3C:
    .string "Pince{END}"

    .global Unk_0820DF42
Unk_0820DF42:
    .string "Thon{END}"

    .global Unk_0820DF47
Unk_0820DF47:
    .string "PBulle{END}"

    .global Unk_0820DF4E
Unk_0820DF4E:
    .string "Canne1{END}"

    .global Unk_0820DF55
Unk_0820DF55:
    .string "Canne2{END}"

    .global Unk_0820DF5C
Unk_0820DF5C:
    .string "Canne3{END}"

    .global Unk_0820DF63
Unk_0820DF63:
    .string "Canne4{END}"

    .global Unk_0820DF6A
Unk_0820DF6A:
    .string "Canne5{END}"

    .global Unk_0820DF71
Unk_0820DF71:
    .string "Fer{END}"

    .global Unk_0820DF75
Unk_0820DF75:
    .string "Clé{END}"

    .global Unk_0820DF79
Unk_0820DF79:
    .string "Vitamn{END}"

    .global Unk_0820DF80
Unk_0820DF80:
    .string "Statue{END}"

    .global Unk_0820DF87
Unk_0820DF87:
    .string "VOeuf{END}"

    .global Unk_0820DF8D
Unk_0820DF8D:
    .string "Biens{END}"

    .global Unk_0820DF93
Unk_0820DF93:
    .string "Oeuf{END}"

    .global Unk_0820DF98
Unk_0820DF98:
    .string "Sphère{END}"

    .global Unk_0820DF9F
Unk_0820DF9F:
    .string "Brnchies{END}"

    .global Unk_0820DFA8
Unk_0820DFA8:
    .string "Ling{END}"

    .global Unk_0820DFAD
Unk_0820DFAD:
    .string "Glaçon{END}"

    .global Unk_0820DFB4
Unk_0820DFB4:
    .string "Fifre{END}"

    .global Unk_0820DFBA
Unk_0820DFBA:
    .string "Passe{END}"

    .global Unk_0820DFC0
Unk_0820DFC0:
    .string "PiècesC{END}"

    .global Unk_0820DFC8
Unk_0820DFC8:
    .string "Pièces{END}"

    .global Unk_0820DFCF
Unk_0820DFCF:
    .string "CoeurDr{END}"

    .global Unk_0820DFD7
Unk_0820DFD7:
    .string "Carte{END}"

    .global Unk_0820DFDD
Unk_0820DFDD:
    .string "Liste{END}"

    .global Unk_0820DFE3
Unk_0820DFE3:
    .string "Kézako{END}"

    .global Unk_0820DFEA
Unk_0820DFEA:
    .string "Note1{END}"

    .global Unk_0820DFF0
Unk_0820DFF0:
    .string "Note2{END}"

    .global Unk_0820DFF6
Unk_0820DFF6:
    .string "GrifG{END}"

    .global Unk_0820DFFC
Unk_0820DFFC:
    .string "CléTps{END}"

    .global Unk_0820E003
Unk_0820E003:
    .string "Boomg{END}"

    .global Unk_0820E009
Unk_0820E009:
    .string "CléCiel{END}"

    .global Unk_0820E011
Unk_0820E011:
    .string "Capuch{END}"

    .global Unk_0820E018
Unk_0820E018:
    .string "Travrsin{END}"

    .global Unk_0820E021
Unk_0820E021:
    .string "Maestro{END}"

    .global Unk_0820E029
Unk_0820E029:
    .string "Mouche{END}"

    .global Unk_0820E030
Unk_0820E030:
    .string "Huile{END}"

    .global Unk_0820E036
Unk_0820E036:
    .string "SoinsM{END}"

    .global Unk_0820E03D
Unk_0820E03D:
    .string "Melon{END}"

    .global Unk_0820E043
Unk_0820E043:
    .string "Fruit{END}"

    .global Unk_0820E049
Unk_0820E049:
    .string "Poisson{END}"

    .global Unk_0820E051
Unk_0820E051:
    .string "Racine{END}"

    .global Unk_0820E058
Unk_0820E058:
    .string "NoixCoc{END}"

    .global Unk_0820E060
Unk_0820E060:
    .string "BoisB{END}"

    .global Unk_0820E066
Unk_0820E066:
    .string "Frtfiant{END}"

    .global Unk_0820E06F
Unk_0820E06F:
    .string "Herbe X9{END}"

    .global Unk_0820E078
Unk_0820E078:
    .string "FourmiX9{END}"

    .global Unk_0820E081
Unk_0820E081:
    .string "Larme X9{END}"

    .global Unk_0820E08A
Unk_0820E08A:
    .string "CharmeX9{END}"

    .global Unk_0820E093
Unk_0820E093:
    .string "Soin  X9{END}"

    .global Unk_0820E09C
Unk_0820E09C:
    .string "Gland X9{END}"

