    .global Unk_0820DAF5
Unk_0820DAF5:
    .string "Où ?{END}"

    .global Unk_0820DAFA
Unk_0820DAFA:
    .string "Drogen{END}"

    .global Unk_0820DB01
Unk_0820DB01:
    .string "Nanaï{END}"

    .global Unk_0820DB07
Unk_0820DB07:
    .string "Winlan{END}"

    .global Unk_0820DB0E
Unk_0820DB0E:
    .string "Roméro{END}"

    .global Unk_0820DB15
Unk_0820DB15:
    .string "Gust{END}"

    .global Unk_0820DB1A
Unk_0820DB1A:
    .string "Camlon{END}"

    .global Unk_0820DB21
Unk_0820DB21:
    .string "Nada{END}"

    .global Unk_0820DB26
Unk_0820DB26:
    .string "Tantar{END}"

    .global Unk_0820DB2D
Unk_0820DB2D:
    .string "Tuntar{END}"

    .global Unk_0820DB34
Unk_0820DB34:
    .string "Agua{END}"

    .global Unk_0820DB39
Unk_0820DB39:
    .string "Auria{END}"

    .global Unk_0820DB3F
Unk_0820DB3F:
    .string "Tryste{END}"

    .global Unk_0820DB46
Unk_0820DB46:
    .string "Arad{END}"

    .global Unk_0820DB4B
Unk_0820DB4B:
    .string "Printemps{END}"

    .global Unk_0820DB55
Unk_0820DB55:
    .string "Tunlan{END}"

    .global Unk_0820DB5C
Unk_0820DB5C:
    .string "Gant{END}"

    .global Unk_0820DB61
Unk_0820DB61:
    .string "Scande{END}"

    .global Unk_0820DB68
Unk_0820DB68:
    .string "Carmen{END}"

    .global Unk_0820DB6F
Unk_0820DB6F:
    .string "Gramor{END}"

    .global Unk_0820DB76
Unk_0820DB76:
    .string "Wisdon{END}"

    .global Unk_0820DB7D
Unk_0820DB7D:
    .string "Karma{END}"

    .global Unk_0820DB83
Unk_0820DB83:
    .string "Prima{END}"

    .global Unk_0820DB89
Unk_0820DB89:
    .string "Crypte{END}"

    .global Unk_0820DB90
Unk_0820DB90:
    .string "Nabal{END}"

    .global Unk_0820DB96
Unk_0820DB96:
    .string "Tock{END}"

    .global Unk_0820DB9B
Unk_0820DB9B:
    .string "Cyme{END}"

    .global Unk_0820DBA0
Unk_0820DBA0:
    .string "Obélisque{END}"

    .global Unk_0820DBAA
Unk_0820DBAA:
    .string "Pagode{END}"

    .global Unk_0820DBB1
Unk_0820DBB1:
    .string "Chapelle Drag{END}"

    .global Unk_0820DBBF
Unk_0820DBBF:
    .string "Temple Drag{END}"

    .global Unk_0820DBCB
Unk_0820DBCB:
    .string "Bois de Ramui{END}"

    .global Unk_0820DBD9
Unk_0820DBD9:
    .string "Grotte Aura{END}"

    .global Unk_0820DBE5
Unk_0820DBE5:
    .string "Forêt triste{END}"

    .global Unk_0820DBF2
Unk_0820DBF2:
    .string "Temple Gaia{END}"

    .global Unk_0820DBFE
Unk_0820DBFE:
    .string "Grotte Lac{END}"

    .global Unk_0820DC09
Unk_0820DC09:
    .string "Chapelle Lac{END}"

    .global Unk_0820DC16
Unk_0820DC16:
    .string "Caverne Cap{END}"

    .global Unk_0820DC22
Unk_0820DC22:
    .string "Caverne Aise{END}"

    .global Unk_0820DC2F
Unk_0820DC2F:
    .string "Tristebois{END}"

    .global Unk_0820DC3A
Unk_0820DC3A:
    .string "Fortin Drg N{END}"

    .global Unk_0820DC47
Unk_0820DC47:
    .string "Base secrète{END}"

    .global Unk_0820DC54
Unk_0820DC54:
    .string "Géant{END}"

    .global Unk_0820DC5A
Unk_0820DC5A:
    .string "Navire Drg N{END}"

    .global Unk_0820DC67
Unk_0820DC67:
    .string "Caverne L&N{END}"

    .global Unk_0820DC73
Unk_0820DC73:
    .string "Fortin caché{END}"

    .global Unk_0820DC80
Unk_0820DC80:
    .string "Tour L&N{END}"

    .global Unk_0820DC89
Unk_0820DC89:
    .string "Volcan marin{END}"

    .global Unk_0820DC96
Unk_0820DC96:
    .string "Tour Diable{END}"

    .global Unk_0820DCA2
Unk_0820DCA2:
    .string "Pays sauvage{END}"

    .global Unk_0820DCAF
Unk_0820DCAF:
    .string "Tour Marais{END}"

    .global Unk_0820DCBB
Unk_0820DCBB:
    .string "Bois Fées{END}"

    .global Unk_0820DCC5
Unk_0820DCC5:
    .string "Ville Marais{END}"

    .global Unk_0820DCD2
Unk_0820DCD2:
    .string "Labo{END}"

    .global Unk_0820DCD7
Unk_0820DCD7:
    .string "Trou souris{END}"

    .global Unk_0820DCE3
Unk_0820DCE3:
    .string "Caverne gren{END}"

    .global Unk_0820DCF0
Unk_0820DCF0:
    .string "Grotte du sud{END}"

    .global Unk_0820DCFE
Unk_0820DCFE:
    .string "Château sud{END}"

    .global Unk_0820DD0A
Unk_0820DD0A:
    .string "Ville onirik{END}"

    .global Unk_0820DD17
Unk_0820DD17:
    .string "Maison sage{END}"

    .global Unk_0820DD23
Unk_0820DD23:
    .string "Maison femme{END}"

    .global Unk_0820DD30
Unk_0820DD30:
    .string "Grotte désert{END}"

    .global Unk_0820DD3E
Unk_0820DD3E:
    .string "Grotte Hiver{END}"

    .global Unk_0820DD4B
Unk_0820DD4B:
    .string "Salle secrète{END}"

