    .global Unk_0820E823
Unk_0820E823:
    .string "Soins1{END}"

    .global Unk_0820E82A
Unk_0820E82A:
    .string "Vig{END}"

    .global Unk_0820E82E
Unk_0820E82E:
    .string "Inactif{END}"

    .global Unk_0820E836
Unk_0820E836:
    .string "AugmCh{END}"

    .global Unk_0820E83D
Unk_0820E83D:
    .string "AugmAtt{END}"

    .global Unk_0820E845
Unk_0820E845:
    .string "Soins2{END}"

    .global Unk_0820E84C
Unk_0820E84C:
    .string "Immob{END}"

    .global Unk_0820E852
Unk_0820E852:
    .string "AugmAg{END}"

    .global Unk_0820E859
Unk_0820E859:
    .string "Zom1{END}"

    .global Unk_0820E85E
Unk_0820E85E:
    .string "Soins3{END}"

    .global Unk_0820E865
Unk_0820E865:
    .string "Renouv{END}"

    .global Unk_0820E86C
Unk_0820E86C:
    .string "Guéris{END}"

    .global Unk_0820E873
Unk_0820E873:
    .string "Boucl{END}"

    .global Unk_0820E879
Unk_0820E879:
    .string "Soins4{END}"

    .global Unk_0820E880
Unk_0820E880:
    .string "Zom2{END}"

    .global Unk_0820E885
Unk_0820E885:
    .string "VigX{END}"

    .global Unk_0820E88A
Unk_0820E88A:
    .string "Chut{END}"

    .global Unk_0820E88F
Unk_0820E88F:
    .string "Dissipe{END}"

    .global Unk_0820E897
Unk_0820E897:
    .string "RenouvX{END}"

    .global Unk_0820E89F
Unk_0820E89F:
    .string "SoinsX{END}"

    .global Unk_0820E8A6
Unk_0820E8A6:
    .string "Mur{END}"

    .global Unk_0820E8AA
Unk_0820E8AA:
    .string "ZomX{END}"

    .global Unk_0820E8AF
Unk_0820E8AF:
    .string "Lueur{END}"

    .global Unk_0820E8B5
Unk_0820E8B5:
    .string "Etincel{END}"

    .global Unk_0820E8BD
Unk_0820E8BD:
    .string "Froid{END}"

    .global Unk_0820E8C3
Unk_0820E8C3:
    .string "35{END}"

    .global Unk_0820E8C6
Unk_0820E8C6:
    .string "Para{END}"

    .global Unk_0820E8CB
Unk_0820E8CB:
    .string "Draine{END}"

    .global Unk_0820E8D2
Unk_0820E8D2:
    .string "Frotte{END}"

    .global Unk_0820E8D9
Unk_0820E8D9:
    .string "Flamme{END}"

    .global Unk_0820E8E0
Unk_0820E8E0:
    .string "Grille{END}"

    .global Unk_0820E8E7
Unk_0820E8E7:
    .string "Givre{END}"

    .global Unk_0820E8ED
Unk_0820E8ED:
    .string "55{END}"

    .global Unk_0820E8F0
Unk_0820E8F0:
    .string "BouleFeu{END}"

    .global Unk_0820E8F9
Unk_0820E8F9:
    .string "Orage{END}"

    .global Unk_0820E8FF
Unk_0820E8FF:
    .string "Gel{END}"

    .global Unk_0820E903
Unk_0820E903:
    .string "95{END}"

    .global Unk_0820E906
Unk_0820E906:
    .string "Vent{END}"

    .global Unk_0820E90B
Unk_0820E90B:
    .string "Glace{END}"

    .global Unk_0820E911
Unk_0820E911:
    .string "Carbon{END}"

    .global Unk_0820E918
Unk_0820E918:
    .string "GlaceX{END}"

    .global Unk_0820E91F
Unk_0820E91F:
    .string "FeuX{END}"

    .global Unk_0820E924
Unk_0820E924:
    .string "EclairX{END}"

    .global Unk_0820E92C
Unk_0820E92C:
    .string "Absorbe{END}"

    .global Unk_0820E934
Unk_0820E934:
    .string "???1{END}"

    .global Unk_0820E939
Unk_0820E939:
    .string "Comète{END}"

    .global Unk_0820E940
Unk_0820E940:
    .string "???2{END}"

    .global Unk_0820E945
Unk_0820E945:
    .string "???3{END}"

    .global Unk_0820E94A
Unk_0820E94A:
    .string "???4{END}"

    .global Unk_0820E94F
Unk_0820E94F:
    .string "???5{END}"

    .global Unk_0820E954
Unk_0820E954:
    .string "???6{END}"

    .global Unk_0820E959
Unk_0820E959:
    .string "???7{END}"

    .global Unk_0820E95E
Unk_0820E95E:
    .string "Soins1{END}"

    .global Unk_0820E965
Unk_0820E965:
    .string "RenouvX{END}"

    .global Unk_0820E96D
Unk_0820E96D:
    .string "Edd{END}"

    .global Unk_0820E971
Unk_0820E971:
    .string "EddX{END}"

    .global Unk_0820E976
Unk_0820E976:
    .string "Eco{END}"

    .global Unk_0820E97A
Unk_0820E97A:
    .string "EcoX{END}"

    .global Unk_0820E97F
Unk_0820E97F:
    .string "???8{END}"

    .global Unk_0820E984
Unk_0820E984:
    .string "???9{END}"

    .global Unk_0820E989
Unk_0820E989:
    .string "???10{END}"

    .global Unk_0820E98F
Unk_0820E98F:
    .string "???12{END}"

    .global Unk_0820E995
Unk_0820E995:
    .string "???13{END}"

    .global Unk_0820E99B
Unk_0820E99B:
    .string "???14{END}"

    .global Unk_0820E9A1
Unk_0820E9A1:
    .string "???15{END}"

    .global Unk_0820E9A7
Unk_0820E9A7:
    .string "???16{END}"

    .global Unk_0820E9AD
Unk_0820E9AD:
    .string "???17{END}"

    .global Unk_0820E9B3
Unk_0820E9B3:
    .string "ZomX{END}"

    .global Unk_0820E9B8
Unk_0820E9B8:
    .string "???18{END}"

    .global Unk_0820E9BE
Unk_0820E9BE:
    .string "???19{END}"

    .global Unk_0820E9C4
Unk_0820E9C4:
    .string "Bombe{END}"

    .global Unk_0820E9CA
Unk_0820E9CA:
    .string "Boum{END}"

    .global Unk_0820E9CF
Unk_0820E9CF:
    .string "Télép{END}"

    .global Unk_0820E9D5
Unk_0820E9D5:
    .string "Fuite{END}"

    .global Unk_0820E9DB
Unk_0820E9DB:
    .string "Explos{END}"

    .global Unk_0820E9E2
Unk_0820E9E2:
    .string "Sortie{END}"

    .global Unk_0820E9E9
Unk_0820E9E9:
    .string "Nova{END}"

    .global Unk_0820E9EE
Unk_0820E9EE:
    .string "NovaX{END}"

    .global Unk_0820E9F4
Unk_0820E9F4:
    .string "???20{END}"

    .global Unk_0820E9FA
Unk_0820E9FA:
    .string "???21{END}"

