    .global Unk_0820D3FB
Unk_0820D3FB:
    .string "Rend 50 PV{END}"

    .global Unk_0820D406
Unk_0820D406:
    .string "Améliore la défense temp.{END}"

    .global Unk_0820D420
Unk_0820D420:
    .string "Ralentit l'ennemi{END}"

    .global Unk_0820D432
Unk_0820D432:
    .string "Augmente la chance temp.{END}"

    .global Unk_0820D44B
Unk_0820D44B:
    .string "Améliore l'attaque temp.{END}"

    .global Unk_0820D464
Unk_0820D464:
    .string "Rend 100 PV{END}"

    .global Unk_0820D470
Unk_0820D470:
    .string "Immobilise l'ennemi{END}"

    .global Unk_0820D484
Unk_0820D484:
    .string "Augmente l'agilité temp.{END}"

    .global Unk_0820D49D
Unk_0820D49D:
    .string "Ange Niv 1 un seul ennemi{END}"

    .global Unk_0820D4B7
Unk_0820D4B7:
    .string "Rend 250 PV{END}"

    .global Unk_0820D4C3
Unk_0820D4C3:
    .string "Soigne l'étourdissement 1 PV{END}"

    .global Unk_0820D4E0
Unk_0820D4E0:
    .string "Soigne tout état anormal{END}"

    .global Unk_0820D4F9
Unk_0820D4F9:
    .string "Réduit les dégâts magiques{END}"

    .global Unk_0820D514
Unk_0820D514:
    .string "Rend tous les PV{END}"

    .global Unk_0820D525
Unk_0820D525:
    .string "Ange Niv 2 un seul ennemi{END}"

    .global Unk_0820D53F
Unk_0820D53F:
    .string "Améliore la défense de tous{END}"

    .global Unk_0820D55B
Unk_0820D55B:
    .string "Bloque la magie ennemie temp{END}"

    .global Unk_0820D578
Unk_0820D578:
    .string "Annule une magie ennemie{END}"

    .global Unk_0820D591
Unk_0820D591:
    .string "Annule l'étourdissement{END}"

    .global Unk_0820D5A9
Unk_0820D5A9:
    .string "Rend 250 PV à tous{END}"

    .global Unk_0820D5BC
Unk_0820D5BC:
    .string "Renvoie la magie ennemie 1x{END}"

    .global Unk_0820D5D8
Unk_0820D5D8:
    .string "Ange Niv 3 groupe ennemi{END}"

    .global Unk_0820D5F1
Unk_0820D5F1:
    .string "Feu Niv 1 un seul ennemi{END}"

    .global Unk_0820D60A
Unk_0820D60A:
    .string "Tonnerre Niv 1 sur un ennemi{END}"

    .global Unk_0820D627
Unk_0820D627:
    .string "Glace Niv 1 sur un ennemi{END}"

    .global Unk_0820D641
Unk_0820D641:
    .string "Secousse Niv 1 sur un ennemi{END}"

    .global Unk_0820D65E
Unk_0820D65E:
    .string "Arrête le temps pour l'ennemi{END}"

    .global Unk_0820D67C
Unk_0820D67C:
    .string "Absorbe les PV de l'ennemi{END}"

    .global Unk_0820D697
Unk_0820D697:
    .string "Peine de mort un seul ennemi{END}"

    .global Unk_0820D6B4
Unk_0820D6B4:
    .string "Feu Niv 2 sur un ennemi{END}"

    .global Unk_0820D6CC
Unk_0820D6CC:
    .string "Tonnerre Niv 2 sur un ennemi{END}"

    .global Unk_0820D6E9
Unk_0820D6E9:
    .string "Glace Niv 2 sur un ennemi{END}"

    .global Unk_0820D703
Unk_0820D703:
    .string "Secousse Niv 2 groupe ennemi{END}"

    .global Unk_0820D720
Unk_0820D720:
    .string "Feu Niv 3 sur un ennemi{END}"

    .global Unk_0820D738
Unk_0820D738:
    .string "Tonnerre Niv 4 groupe ennemi{END}"

    .global Unk_0820D755
Unk_0820D755:
    .string "Glace Niv 3 groupe ennemi{END}"

    .global Unk_0820D76F
Unk_0820D76F:
    .string "Secousse Niv 3 groupe ennemi{END}"

    .global Unk_0820D78C
Unk_0820D78C:
    .string "Tonnerre Niv 5 groupe ennemi{END}"

    .global Unk_0820D7A9
Unk_0820D7A9:
    .string "Glace Niv 4 groupe ennemi{END}"

    .global Unk_0820D7C3
Unk_0820D7C3:
    .string "Feu Niv 5 groupe ennemi{END}"

    .global Unk_0820D7DB
Unk_0820D7DB:
    .string "Glace Niv 5 sur un ennemi{END}"

    .global Unk_0820D7F5
Unk_0820D7F5:
    .string "Feu Niv 4 sur un ennemi{END}"

    .global Unk_0820D80D
Unk_0820D80D:
    .string "Tonnerre Niv 3 sur un ennemi{END}"

    .global Unk_0820D82A
Unk_0820D82A:
    .string "Absorbe les PC de l'ennemi{END}"

    .global Unk_0820D845
Unk_0820D845:
    .string "Faux{END}"

    .global Unk_0820D84A
Unk_0820D84A:
    .string "Tempête de météores ennemis{END}"

    .global Unk_0820D866
Unk_0820D866:
    .string "Faux{END}"

    .global Unk_0820D86B
Unk_0820D86B:
    .string "Faux{END}"

    .global Unk_0820D870
Unk_0820D870:
    .string "Faux{END}"

    .global Unk_0820D875
Unk_0820D875:
    .string "Faux{END}"

    .global Unk_0820D87A
Unk_0820D87A:
    .string "Faux{END}"

    .global Unk_0820D87F
Unk_0820D87F:
    .string "Faux{END}"

    .global Unk_0820D884
Unk_0820D884:
    .string "Faux{END}"

    .global Unk_0820D889
Unk_0820D889:
    .string "Soigne l'étourdissement max{END}"

    .global Unk_0820D8A5
Unk_0820D8A5:
    .string "Utilisé au combat sous l'eau{END}"

    .global Unk_0820D8C2
Unk_0820D8C2:
    .string "Utilisé au combat sous l'eau{END}"

    .global Unk_0820D8DF
Unk_0820D8DF:
    .string "Utilisé au combat sous l'eau{END}"

    .global Unk_0820D8FC
Unk_0820D8FC:
    .string "Utilisé au combat sous l'eau{END}"

    .global Unk_0820D919
Unk_0820D919:
    .string "Faux{END}"

    .global Unk_0820D91E
Unk_0820D91E:
    .string "Faux{END}"

    .global Unk_0820D923
Unk_0820D923:
    .string "Faux{END}"

    .global Unk_0820D928
Unk_0820D928:
    .string "Faux{END}"

    .global Unk_0820D92D
Unk_0820D92D:
    .string "Faux{END}"

    .global Unk_0820D932
Unk_0820D932:
    .string "Faux{END}"

    .global Unk_0820D937
Unk_0820D937:
    .string "Faux{END}"

    .global Unk_0820D93C
Unk_0820D93C:
    .string "Faux{END}"

    .global Unk_0820D941
Unk_0820D941:
    .string "Faux{END}"

    .global Unk_0820D946
Unk_0820D946:
    .string "Ange Niv 3 groupe ennemi{END}"

    .global Unk_0820D95F
Unk_0820D95F:
    .string "Faux{END}"

    .global Unk_0820D964
Unk_0820D964:
    .string "Faux{END}"

    .global Unk_0820D969
Unk_0820D969:
    .string "Explosion Niv 1 un ennemi{END}"

    .global Unk_0820D983
Unk_0820D983:
    .string "Explosion Niv 2 ennemis{END}"

    .global Unk_0820D99B
Unk_0820D99B:
    .string "Téléporte en ville{END}"

    .global Unk_0820D9AE
Unk_0820D9AE:
    .string "Permet de fuir le combat{END}"

    .global Unk_0820D9C7
Unk_0820D9C7:
    .string "Explosion Niv 3 un ennemi{END}"

    .global Unk_0820D9E1
Unk_0820D9E1:
    .string "S'échapper des souterrains{END}"

    .global Unk_0820D9FC
Unk_0820D9FC:
    .string "Explosion Niv 4 ennemis{END}"

    .global Unk_0820DA14
Unk_0820DA14:
    .string "Explosion Niv 5 un emnnemi{END}"

    .global Unk_0820DA2F
Unk_0820DA2F:
    .string "Faux{END}"

    .global Unk_0820DA34
Unk_0820DA34:
    .string "Faux{END}"

    .global Unk_0820DA39
Unk_0820DA39:
    .string "Creuse pour fuir le combat{END}"

    .global Unk_0820DA54
Unk_0820DA54:
    .string "Utilisé au combat{END}"

    .global Unk_0820DA66
Unk_0820DA66:
    .string "Les personnages fusionnent{END}"

    .global Unk_0820DA81
Unk_0820DA81:
    .string "Disponible sous l'eau{END}"

    .global Unk_0820DA97
Unk_0820DA97:
    .string "Disponible sur terre{END}"

    .global Unk_0820DAAC
Unk_0820DAAC:
    .string "Les personnages fusionnent{END}"

    .global Unk_0820DAC7
Unk_0820DAC7:
    .string "Défusionne les personnages{END}"

    .global Unk_0820DAE2
Unk_0820DAE2:
    .string "Rend forme humaine{END}"

