    .global Unk_0820E0A5
Unk_0820E0A5:
    .string "Couteau{END}"

    .global Unk_0820E0AD
Unk_0820E0AD:
    .string "EpBronz{END}"

    .global Unk_0820E0B5
Unk_0820E0B5:
    .string "Sabre{END}"

    .global Unk_0820E0BB
Unk_0820E0BB:
    .string "Faux{END}"

    .global Unk_0820E0C0
Unk_0820E0C0:
    .string "EpLong{END}"

    .global Unk_0820E0C7
Unk_0820E0C7:
    .string "EpDrag{END}"

    .global Unk_0820E0CE
Unk_0820E0CE:
    .string "EpPuis{END}"

    .global Unk_0820E0D5
Unk_0820E0D5:
    .string "EpAilée{END}"

    .global Unk_0820E0DD
Unk_0820E0DD:
    .string "EpEmp{END}"

    .global Unk_0820E0E3
Unk_0820E0E3:
    .string "EpCass{END}"

    .global Unk_0820E0EA
Unk_0820E0EA:
    .string "Faux{END}"

    .global Unk_0820E0EF
Unk_0820E0EF:
    .string "EpFeu{END}"

    .global Unk_0820E0F5
Unk_0820E0F5:
    .string "Faucille{END}"

    .global Unk_0820E0FE
Unk_0820E0FE:
    .string "EpLarge{END}"

    .global Unk_0820E106
Unk_0820E106:
    .string "EpMyst{END}"

    .global Unk_0820E10D
Unk_0820E10D:
    .string "ArmeSp{END}"

    .global Unk_0820E114
Unk_0820E114:
    .string "RapCour{END}"

    .global Unk_0820E11C
Unk_0820E11C:
    .string "Rapière{END}"

    .global Unk_0820E124
Unk_0820E124:
    .string "RapFer{END}"

    .global Unk_0820E12B
Unk_0820E12B:
    .string "RapEmpoi{END}"

    .global Unk_0820E134
Unk_0820E134:
    .string "RapLèg{END}"

    .global Unk_0820E13B
Unk_0820E13B:
    .string "Faux{END}"

    .global Unk_0820E140
Unk_0820E140:
    .string "RapFeu{END}"

    .global Unk_0820E147
Unk_0820E147:
    .string "RapAilée{END}"

    .global Unk_0820E150
Unk_0820E150:
    .string "RapBron{END}"

    .global Unk_0820E158
Unk_0820E158:
    .string "RapMal{END}"

    .global Unk_0820E15F
Unk_0820E15F:
    .string "RapTonn{END}"

    .global Unk_0820E167
Unk_0820E167:
    .string "Faux{END}"

    .global Unk_0820E16C
Unk_0820E16C:
    .string "RapLoi{END}"

    .global Unk_0820E173
Unk_0820E173:
    .string "RapPuiss{END}"

    .global Unk_0820E17C
Unk_0820E17C:
    .string "MartFer{END}"

    .global Unk_0820E184
Unk_0820E184:
    .string "MartEpn{END}"

    .global Unk_0820E18C
Unk_0820E18C:
    .string "Gourdin{END}"

    .global Unk_0820E194
Unk_0820E194:
    .string "MartG{END}"

    .global Unk_0820E19A
Unk_0820E19A:
    .string "MartFeu{END}"

    .global Unk_0820E1A2
Unk_0820E1A2:
    .string "Faux{END}"

    .global Unk_0820E1A7
Unk_0820E1A7:
    .string "MartRage{END}"

    .global Unk_0820E1B0
Unk_0820E1B0:
    .string "Faux{END}"

    .global Unk_0820E1B5
Unk_0820E1B5:
    .string "Maillet{END}"

    .global Unk_0820E1BD
Unk_0820E1BD:
    .string "MartEtoi{END}"

    .global Unk_0820E1C6
Unk_0820E1C6:
    .string "Bâton{END}"

    .global Unk_0820E1CC
Unk_0820E1CC:
    .string "Canne{END}"

    .global Unk_0820E1D2
Unk_0820E1D2:
    .string "CanneOs{END}"

    .global Unk_0820E1DA
Unk_0820E1DA:
    .string "CanneMal{END}"

    .global Unk_0820E1E3
Unk_0820E1E3:
    .string "Faux{END}"

    .global Unk_0820E1E8
Unk_0820E1E8:
    .string "CanneGl{END}"

    .global Unk_0820E1F0
Unk_0820E1F0:
    .string "Faux{END}"

    .global Unk_0820E1F5
Unk_0820E1F5:
    .string "CanneBr{END}"

    .global Unk_0820E1FD
Unk_0820E1FD:
    .string "Faux{END}"

    .global Unk_0820E202
Unk_0820E202:
    .string "GrBâton{END}"

    .global Unk_0820E20A
Unk_0820E20A:
    .string "Pique{END}"

    .global Unk_0820E210
Unk_0820E210:
    .string "Javeline{END}"

    .global Unk_0820E219
Unk_0820E219:
    .string "VLance{END}"

    .global Unk_0820E220
Unk_0820E220:
    .string "LanHér{END}"

    .global Unk_0820E227
Unk_0820E227:
    .string "Trident{END}"

    .global Unk_0820E22F
Unk_0820E22F:
    .string "Faux{END}"

    .global Unk_0820E234
Unk_0820E234:
    .string "Dormeuse{END}"

    .global Unk_0820E23D
Unk_0820E23D:
    .string "Faux{END}"

    .global Unk_0820E242
Unk_0820E242:
    .string "ArbCreus{END}"

    .global Unk_0820E24B
Unk_0820E24B:
    .string "ArbRouil{END}"

    .global Unk_0820E254
Unk_0820E254:
    .string "ArbFer{END}"

    .global Unk_0820E25B
Unk_0820E25B:
    .string "ArbGl{END}"

    .global Unk_0820E261
Unk_0820E261:
    .string "Faux{END}"

    .global Unk_0820E266
Unk_0820E266:
    .string "ArbMyst{END}"

    .global Unk_0820E26E
Unk_0820E26E:
    .string "Faux{END}"

    .global Unk_0820E273
Unk_0820E273:
    .string "DagLanc{END}"

    .global Unk_0820E27B
Unk_0820E27B:
    .string "Dague{END}"

    .global Unk_0820E281
Unk_0820E281:
    .string "Dard{END}"

    .global Unk_0820E286
Unk_0820E286:
    .string "TriDag{END}"

    .global Unk_0820E28D
Unk_0820E28D:
    .string "DagPuis{END}"

    .global Unk_0820E295
Unk_0820E295:
    .string "DagFeu{END}"

    .global Unk_0820E29C
Unk_0820E29C:
    .string "DagArg{END}"

    .global Unk_0820E2A3
Unk_0820E2A3:
    .string "Faux{END}"

    .global Unk_0820E2A8
Unk_0820E2A8:
    .string "Faux{END}"

    .global Unk_0820E2AD
Unk_0820E2AD:
    .string "DagGl{END}"

    .global Unk_0820E2B3
Unk_0820E2B3:
    .string "Faux{END}"

    .global Unk_0820E2B8
Unk_0820E2B8:
    .string "DagNr{END}"

    .global Unk_0820E2BE
Unk_0820E2BE:
    .string "Faux{END}"

    .global Unk_0820E2C3
Unk_0820E2C3:
    .string "ArcBronz{END}"

    .global Unk_0820E2CC
Unk_0820E2CC:
    .string "ArcCour{END}"

    .global Unk_0820E2D4
Unk_0820E2D4:
    .string "ArcLong{END}"

    .global Unk_0820E2DC
Unk_0820E2DC:
    .string "ArcAcier{END}"

    .global Unk_0820E2E5
Unk_0820E2E5:
    .string "ArcEmpoi{END}"

    .global Unk_0820E2EE
Unk_0820E2EE:
    .string "ArcAcéré{END}"

    .global Unk_0820E2F7
Unk_0820E2F7:
    .string "ArcLune{END}"

    .global Unk_0820E2FF
Unk_0820E2FF:
    .string "ArcJade{END}"

    .global Unk_0820E307
Unk_0820E307:
    .string "TriArc{END}"

    .global Unk_0820E30E
Unk_0820E30E:
    .string "Faux{END}"

    .global Unk_0820E313
Unk_0820E313:
    .string "Faux{END}"

    .global Unk_0820E318
Unk_0820E318:
    .string "Faux{END}"

    .global Unk_0820E31D
Unk_0820E31D:
    .string "ArcNain{END}"

    .global Unk_0820E325
Unk_0820E325:
    .string "ArcHéros{END}"

    .global Unk_0820E32E
Unk_0820E32E:
    .string "Faux{END}"

    .global Unk_0820E333
Unk_0820E333:
    .string "Boomrg{END}"

    .global Unk_0820E33A
Unk_0820E33A:
    .string "Fleuret{END}"

    .global Unk_0820E342
Unk_0820E342:
    .string "Trirang{END}"

