    .global Unk_08216654
Unk_08216654:
    .string "ATT{END}"

    .global Unk_08216658
Unk_08216658:
    .string "SORT{END}"

    .global Unk_0821665D
Unk_0821665D:
    .string "OBJ{END}"

    .global Unk_08216661
Unk_08216661:
    .string "CHNG{END}"

    .global Unk_08216666
Unk_08216666:
    .string "A{END}"

    .global Unk_08216668
Unk_08216668:
    .string "U{END}"

    .global Unk_0821666A
Unk_0821666A:
    .string "T{END}"

    .global Unk_0821666C
Unk_0821666C:
    .string "O{END}"

    .global Unk_0821666E
Unk_0821666E:
    .string "V{END}"

    .global Unk_08216670
Unk_08216670:
    .string "A{END}"

    .global Unk_08216672
Unk_08216672:
    .string " {END}"

    .global Unk_08216674
Unk_08216674:
    .string " {END}"

    .global Unk_08216676
Unk_08216676:
    .string "{0x15}{END}"

    .global Unk_08216678
Unk_08216678:
    .string "ATTK{END}"

    .global Unk_0821667D
Unk_0821667D:
    .string "SPEL{END}"

    .global Unk_08216682
Unk_08216682:
    .string "ITEM{END}"

    .global Unk_08216687
Unk_08216687:
    .string "CHNG{END}"

    .global Unk_0821668C
Unk_0821668C:
    .string "A{END}"

    .global Unk_0821668E
Unk_0821668E:
    .string "U{END}"

    .global Unk_08216690
Unk_08216690:
    .string "T{END}"

    .global Unk_08216692
Unk_08216692:
    .string "O{END}"

    .global Unk_08216694
Unk_08216694:
    .string "R{END}"

    .global Unk_08216696
Unk_08216696:
    .string "U{END}"

    .global Unk_08216698
Unk_08216698:
    .string "N{END}"

    .global Unk_0821669A
Unk_0821669A:
    .string " {END}"

    .global Unk_0821669C
Unk_0821669C:
    .string "{0x15}{END}"

    .global Unk_0821669E
Unk_0821669E:
    .string "ANGR{END}"

    .global Unk_082166A3
Unk_082166A3:
    .string "ZAUB{END}"

    .global Unk_082166A8
Unk_082166A8:
    .string "OBJK{END}"

    .global Unk_082166AD
Unk_082166AD:
    .string "POS{END}"

    .global Unk_082166B1
Unk_082166B1:
    .string "A{END}"

    .global Unk_082166B3
Unk_082166B3:
    .string "U{END}"

    .global Unk_082166B5
Unk_082166B5:
    .string "T{END}"

    .global Unk_082166B7
Unk_082166B7:
    .string "O{END}"

    .global Unk_082166B9
Unk_082166B9:
    .string "G{END}"

    .global Unk_082166BB
Unk_082166BB:
    .string "E{END}"

    .global Unk_082166BD
Unk_082166BD:
    .string "H{END}"

    .global Unk_082166BF
Unk_082166BF:
    .string " {END}"

    .global Unk_082166C1
Unk_082166C1:
    .string "{0x15}{END}"

    .global Unk_082166C3
Unk_082166C3:
    .string "SWCH{END}"

    .global Unk_082166C8
Unk_082166C8:
    .string "TSCH{END}"

    .global Unk_082166CD
Unk_082166CD:
    .string "POS{END}"

    .global Unk_082166D1
Unk_082166D1:
    .string "DFND{END}"

    .global Unk_082166D6
Unk_082166D6:
    .string "VERT{END}"

    .global Unk_082166DB
Unk_082166DB:
    .string "DEF{END}"

    .global Unk_082166DF
Unk_082166DF:
    .string "HP1 {END}"

    .global Unk_082166E4
Unk_082166E4:
    .string "HP1 {END}"

    .global Unk_082166E9
Unk_082166E9:
    .string "PV1 {END}"

    .global Unk_082166EE
Unk_082166EE:
    .string "DUMP{END}"

    .global Unk_082166F3
Unk_082166F3:
    .string "DUMP{END}"

    .global Unk_082166F8
Unk_082166F8:
    .string "LACH{END}"

    .global Unk_082166FD
Unk_082166FD:
    .string "HPMX{END}"

    .global Unk_08216702
Unk_08216702:
    .string "HPMX{END}"

    .global Unk_08216707
Unk_08216707:
    .string "PVMX{END}"

    .global Unk_0821670C
Unk_0821670C:
    .string "Fail{END}"

    .global Unk_08216711
Unk_08216711:
    .string "Miss{END}"

    .global Unk_08216716
Unk_08216716:
    .string "Cntr{END}"

    .global Unk_0821671B
Unk_0821671B:
    .string "Slam{END}"

    .global Unk_08216720
Unk_08216720:
    .string "Cont{END}"

    .global Unk_08216725
Unk_08216725:
    .string "Ech{END}"

    .global Unk_08216729
Unk_08216729:
    .string "Raté{END}"

    .global Unk_0821672E
Unk_0821672E:
    .string "Cntr{END}"

    .global Unk_08216733
Unk_08216733:
    .string "Yah!{END}"

    .global Unk_08216738
Unk_08216738:
    .string "Cont{END}"

    .global Unk_0821673D
Unk_0821673D:
    .string "Fehl{END}"

    .global Unk_08216742
Unk_08216742:
    .string "Verf{END}"

    .global Unk_08216747
Unk_08216747:
    .string "Kntr{END}"

    .global Unk_0821674C
Unk_0821674C:
    .string "Slam{END}"

    .global Unk_08216751
Unk_08216751:
    .string "Ver{END}"

    .global Unk_08216755
Unk_08216755:
    .string " Used in battle.{END}"

    .global Unk_08216766
Unk_08216766:
    .string "Im Kampf benutzt.{END}"

    .global Unk_08216778
Unk_08216778:
    .string "Utilisé au combat.{END}"

    .global Unk_0821678B
Unk_0821678B:
    .string "AP{END}"

    .global Unk_0821678E
Unk_0821678E:
    .string "AP{END}"

    .global Unk_08216791
Unk_08216791:
    .string "PC{END}"

    .global Unk_08216794
Unk_08216794:
    .string "/{END}"

    .global Unk_08216796
Unk_08216796:
    .string "Spells are not available.{END}"

    .global Unk_082167B0
Unk_082167B0:
    .string "Sorts indisponibles.{END}"

    .global Unk_082167C5
Unk_082167C5:
    .string "Zauber nicht verfügbar. {END}"

