    .global Unk_08185398
Unk_08185398:
    .string "BREATH OF FIRE{END}"

    .global Unk_081853A7
Unk_081853A7:
    .string "PRODUCED STAFF{END}"

    .global Unk_081853B6
Unk_081853B6:
    .string "PLANNER{END}"

    .global Unk_081853BE
Unk_081853BE:
    .string "Bamboo{END}"

    .global Unk_081853C5
Unk_081853C5:
    .string "Botunori{END}"

    .global Unk_081853CE
Unk_081853CE:
    .string "Pukchi{END}"

    .global Unk_081853D5
Unk_081853D5:
    .string "Makoto{END}"

    .global Unk_081853DC
Unk_081853DC:
    .string "SCROLL STAFF{END}"

    .global Unk_081853E9
Unk_081853E9:
    .string "Don{END}"

    .global Unk_081853ED
Unk_081853ED:
    .string "Banndy{END}"

    .global Unk_081853F4
Unk_081853F4:
    .string "Scr. Spirit{END}"

    .global Unk_08185400
Unk_08185400:
    .string "U-King{END}"

    .global Unk_08185407
Unk_08185407:
    .string "Tuck-K{END}"

    .global Unk_0818540E
Unk_0818540E:
    .string "OBJECT STAFF{END}"

    .global Unk_0818541B
Unk_0818541B:
    .string "Inuffkin{END}"

    .global Unk_08185424
Unk_08185424:
    .string "Fishman{END}"

    .global Unk_0818542C
Unk_0818542C:
    .string "Simiz{END}"

    .global Unk_08185432
Unk_08185432:
    .string "Zura-Zura{END}"

    .global Unk_0818543C
Unk_0818543C:
    .string "Mats{END}"

    .global Unk_08185441
Unk_08185441:
    .string "MUSIC COMPOSER{END}"

    .global Unk_08185450
Unk_08185450:
    .string "Bun-Bun{END}"

    .global Unk_08185458
Unk_08185458:
    .string "Mari{END}"

    .global Unk_0818545D
Unk_0818545D:
    .string "O-Jaring{END}"

    .global Unk_08185466
Unk_08185466:
    .string "Pii♪{END}"

    .global Unk_0818546B
Unk_0818546B:
    .string "SOUND EFFECTS{END}"

    .global Unk_08185479
Unk_08185479:
    .string "Any{END}"

    .global Unk_0818547D
Unk_0818547D:
    .string "Elf{END}"

    .global Unk_08185481
Unk_08185481:
    .string "SOUND PROGRAMMER{END}"

    .global Unk_08185492
Unk_08185492:
    .string "Oyabun{END}"

    .global Unk_08185499
Unk_08185499:
    .string "Ikebon{END}"

    .global Unk_081854A0
Unk_081854A0:
    .string "GAME PROGRAMMER{END}"

    .global Unk_081854B0
Unk_081854B0:
    .string "Kanecon{END}"

    .global Unk_081854B8
Unk_081854B8:
    .string "Noriko{END}"

    .global Unk_081854BF
Unk_081854BF:
    .string "Sun Chan{END}"

    .global Unk_081854C8
Unk_081854C8:
    .string "Sleeper{END}"

    .global Unk_081854D0
Unk_081854D0:
    .string "Shu{END}"

    .global Unk_081854D4
Unk_081854D4:
    .string "SPECIAL THANKS{END}"

    .global Unk_081854E3
Unk_081854E3:
    .string "Bone{END}"

    .global Unk_081854E8
Unk_081854E8:
    .string "QUETZAL{END}"

    .global Unk_081854F0
Unk_081854F0:
    .string "Kazuki{END}"

    .global Unk_081854F7
Unk_081854F7:
    .string "No.19{END}"

    .global Unk_081854FD
Unk_081854FD:
    .string "Tatuya{END}"

    .global Unk_08185504
Unk_08185504:
    .string "カプコンしゃいんのみなさん{END}"

    .global Unk_08185512
Unk_08185512:
    .string "おつかれさまでした{END}"

    .global Unk_0818551C
Unk_0818551C:
    .string "ALL CAPCOM STAFF{END}"

    .global Unk_0818552D
Unk_0818552D:
    .string "    FIGHTERS{END}"

    .global Unk_0818553A
Unk_0818553A:
    .string "and...{END}"

    .global Unk_08185541
Unk_08185541:
    .string "   You{END}"

    .global Unk_08185548
Unk_08185548:
    .string "Thanks for playing!{END}"

    .global Unk_0818555C
Unk_0818555C:
    .string "...and{END}"
