    .global Unk_0820C925
Unk_0820C925:
    .string "Fwd{END}"

    .global Unk_0820C929
Unk_0820C929:
    .string "Bck{END}"

    .global Unk_0820C92D
Unk_0820C92D:
    .string "End{END}"

    .global Unk_0820C931
Unk_0820C931:
    .string "Vwts{END}"

    .global Unk_0820C936
Unk_0820C936:
    .string "Zrck{END}"

    .global Unk_0820C93B
Unk_0820C93B:
    .string "Ende{END}"

    .global Unk_0820C940
Unk_0820C940:
    .string "Av{END}"

    .global Unk_0820C943
Unk_0820C943:
    .string "Rtr{END}"

    .global Unk_0820C947
Unk_0820C947:
    .string "Fin{END}"
