    .global Unk_0820B3DE
Unk_0820B3DE:
    .string "OK to discard?       Yes No{END}"

    .global Unk_0820B3FA
Unk_0820B3FA:
    .string "Use whose spell?{END}"

    .global Unk_0820B40B
Unk_0820B40B:
    .string "Use on whom?{END}"

    .global Unk_0820B418
Unk_0820B418:
    .string "Change whose equipment?{END}"

    .global Unk_0820B430
Unk_0820B430:
    .string "View whose status?{END}"

    .global Unk_0820B443
Unk_0820B443:
    .string "Sort items?          Yes No{END}"

    .global Unk_0820B45F
Unk_0820B45F:
    .string "Select an item to switch.{END}"

    .global Unk_0820B479
Unk_0820B479:
    .string "With which item?{END}"

    .global Unk_0820B48A
Unk_0820B48A:
    .string "USE{END}"

    .global Unk_0820B48E
Unk_0820B48E:
    .string "DSCD{END}"

    .global Unk_0820B493
Unk_0820B493:
    .string "CHNG{END}"

    .global Unk_0820B498
Unk_0820B498:
    .string "SORT{END}"

    .global Unk_0820B49D
Unk_0820B49D:
    .string "Use an item.{END}"

    .global Unk_0820B4AA
Unk_0820B4AA:
    .string "Discard an item.{END}"

    .global Unk_0820B4BB
Unk_0820B4BB:
    .string "Switch items.{END}"

    .global Unk_0820B4C9
Unk_0820B4C9:
    .string "Sort items.{END}"

    .global Unk_0820B4D5
Unk_0820B4D5:
    .string "View vital items.{END}"

    .global Unk_0820B4E7
Unk_0820B4E7:
    .string "ITEM{END}"

    .global Unk_0820B4EC
Unk_0820B4EC:
    .string "SPEL{END}"

    .global Unk_0820B4F1
Unk_0820B4F1:
    .string "EQIP{END}"

    .global Unk_0820B4F6
Unk_0820B4F6:
    .string "SWCH{END}"

    .global Unk_0820B4FB
Unk_0820B4FB:
    .string "CHNG{END}"

    .global Unk_0820B500
Unk_0820B500:
    .string "END{END}"

    .global Unk_0820B504
Unk_0820B504:
    .string "Change which character?{END}"

    .global Unk_0820B51C
Unk_0820B51C:
    .string "With which character?{END}"

    .global Unk_0820B532
Unk_0820B532:
    .string "Dig{END}"

    .global Unk_0820B536
Unk_0820B536:
    .string "Select an item to discard.{END}"

    .global Unk_0820B551
Unk_0820B551:
    .string "NONE{END}"

    .global Unk_0820B556
Unk_0820B556:
    .string "REMOVE{END}"

    .global Unk_0820B55D
Unk_0820B55D:
    .string "       "

    .global Unk_0820B564
Unk_0820B564:
    .string "  "

    .global Unk_0820B566
Unk_0820B566:
    .string "  "

    .global Unk_0820B568
Unk_0820B568:
    .string " "

    .global Unk_0820B569
Unk_0820B569:
    .string "   {END}"

    .global Unk_0820B56D
Unk_0820B56D:
    .string "AP{END}"

    .global Unk_0820B570
Unk_0820B570:
    .string "/{END}"

    .global Unk_0820B572
Unk_0820B572:
    .string "AP{END}"

    .global Unk_0820B575
Unk_0820B575:
    .string "Switch whose line?{END}"

    .global Unk_0820B588
Unk_0820B588:
    .string "Quick Save the game?{END}"

    .global Unk_0820B59D
Unk_0820B59D:
    .string "{END}"

    .global Unk_0820B59E
Unk_0820B59E:
    .string "WARNING: OK to overwrite{END}"

    .global Unk_0820B5B7
Unk_0820B5B7:
    .string "the existing data{END}"

    .global Unk_0820B5C9
Unk_0820B5C9:
    .string "?{END}"

    .global Unk_0820B5CB
Unk_0820B5CB:
    .string "Quick Save successfully{END}"

    .global Unk_0820B5E3
Unk_0820B5E3:
    .string "completed.{END}"

    .global Unk_0820B5EE
Unk_0820B5EE:
    .string "Yes{END}"

    .global Unk_0820B5F2
Unk_0820B5F2:
    .string " No{END}"

    .global Unk_0820B5F6
Unk_0820B5F6:
    .string "Push A Button for details.{END}"

    .global Unk_0820B611
Unk_0820B611:
    .string "Which item?{END}"

    .global Unk_0820B61D
Unk_0820B61D:
    .string "ERROR!: SAVE FAILED.{END}"

    .global Unk_0820B632
Unk_0820B632:
    .string "AP{END}"

    .global Unk_0820B635
Unk_0820B635:
    .string "/{END}"

    .global Unk_0820B637
Unk_0820B637:
    .string "AP{END}"

    .global Unk_0820B63A
Unk_0820B63A:
    .string "Verwerfen OK?         Ja Nein{END}"

    .global Unk_0820B658
Unk_0820B658:
    .string "Wessen Zauber benutzen?{END}"

    .global Unk_0820B670
Unk_0820B670:
    .string "Wer soll benutzen?{END}"

    .global Unk_0820B683
Unk_0820B683:
    .string "Wessen Ausrüstung ändern?{END}"

    .global Unk_0820B69D
Unk_0820B69D:
    .string "Wessen Status anzeigen?{END}"

    .global Unk_0820B6B5
Unk_0820B6B5:
    .string "Objekte sortieren?    Ja Nein{END}"

    .global Unk_0820B6D3
Unk_0820B6D3:
    .string "Zu tauschendes Objekt:.{END}"

    .global Unk_0820B6EB
Unk_0820B6EB:
    .string "Mit welchem Objekt?{END}"

    .global Unk_0820B6FF
Unk_0820B6FF:
    .string "BNTZ{END}"

    .global Unk_0820B704
Unk_0820B704:
    .string "WEGW{END}"

    .global Unk_0820B709
Unk_0820B709:
    .string "TSCH{END}"

    .global Unk_0820B70E
Unk_0820B70E:
    .string "SORT{END}"

    .global Unk_0820B713
Unk_0820B713:
    .string "Ein Objekt benutzen.{END}"

    .global Unk_0820B728
Unk_0820B728:
    .string "Ein Objekt wegwerfen.{END}"

    .global Unk_0820B73E
Unk_0820B73E:
    .string "Objekte tauschen.{END}"

    .global Unk_0820B750
Unk_0820B750:
    .string "Objekte sortieren.{END}"

    .global Unk_0820B763
Unk_0820B763:
    .string "Wichtige Objekte zeigen.{END}"

    .global Unk_0820B77C
Unk_0820B77C:
    .string "OBJ{END}"

    .global Unk_0820B780
Unk_0820B780:
    .string "ZAUB{END}"

    .global Unk_0820B785
Unk_0820B785:
    .string "AUSR{END}"

    .global Unk_0820B78A
Unk_0820B78A:
    .string "TSCH{END}"

    .global Unk_0820B78F
Unk_0820B78F:
    .string "POS{END}"

    .global Unk_0820B793
Unk_0820B793:
    .string "ENDE{END}"

    .global Unk_0820B798
Unk_0820B798:
    .string "Wessen Position ändern?{END}"

    .global Unk_0820B7B0
Unk_0820B7B0:
    .string "Tauschen mit?{END}"

    .global Unk_0820B7BE
Unk_0820B7BE:
    .string "Graben{END}"

    .global Unk_0820B7C5
Unk_0820B7C5:
    .string "Zu verwerfendes Objekt:.{END}"

    .global Unk_0820B7DE
Unk_0820B7DE:
    .string "KEINS{END}"

    .global Unk_0820B7E4
Unk_0820B7E4:
    .string "ENTF{END}"

    .global Unk_0820B7E9
Unk_0820B7E9:
    .string "Wessen Reihe?{END}"

    .global Unk_0820B7F7
Unk_0820B7F7:
    .string "Spiel schnellspeichern?{END}"

    .global Unk_0820B80F
Unk_0820B80F:
    .string "{END}"

    .global Unk_0820B810
Unk_0820B810:
    .string "WARNUNG: OK um existierende{END}"

    .global Unk_0820B82C
Unk_0820B82C:
    .string "Daten zu überschreiben{END}"

    .global Unk_0820B843
Unk_0820B843:
    .string "?{END}"

    .global Unk_0820B845
Unk_0820B845:
    .string "Speichern erfolgreich{END}"

    .global Unk_0820B85B
Unk_0820B85B:
    .string "beendet{END}"

    .global Unk_0820B863
Unk_0820B863:
    .string "Ja.{END}"

    .global Unk_0820B867
Unk_0820B867:
    .string "Nein{END}"

    .global Unk_0820B86C
Unk_0820B86C:
    .string "A-Knopf für Details.{END}"

    .global Unk_0820B881
Unk_0820B881:
    .string "Welches Objekt?{END}"

    .global Unk_0820B891
Unk_0820B891:
    .string "PA{END}"

    .global Unk_0820B894
Unk_0820B894:
    .string "/{END}"

    .global Unk_0820B896
Unk_0820B896:
    .string "PA{END}"

    .global Unk_0820B899
Unk_0820B899:
    .string "S'en débarrasser ?   Oui Non{END}"

    .global Unk_0820B8B6
Unk_0820B8B6:
    .string "Quel personnage ?{END}"

    .global Unk_0820B8C8
Unk_0820B8C8:
    .string "Sur quel personnage ?{END}"

    .global Unk_0820B8DE
Unk_0820B8DE:
    .string "Changer quel équipement ?{END}"

    .global Unk_0820B8F8
Unk_0820B8F8:
    .string "Quel personnage ?{END}"

    .global Unk_0820B90A
Unk_0820B90A:
    .string "Ranger objets ?      Oui Non{END}"

    .global Unk_0820B927
Unk_0820B927:
    .string "Echanger quel objet ?{END}"

    .global Unk_0820B93D
Unk_0820B93D:
    .string "Avec quel objet ?{END}"

    .global Unk_0820B94F
Unk_0820B94F:
    .string "UTIL{END}"

    .global Unk_0820B954
Unk_0820B954:
    .string "POUB{END}"

    .global Unk_0820B959
Unk_0820B959:
    .string "CHNG{END}"

    .global Unk_0820B95E
Unk_0820B95E:
    .string "RANG{END}"

    .global Unk_0820B963
Unk_0820B963:
    .string "Utiliser un objet.{END}"

    .global Unk_0820B976
Unk_0820B976:
    .string "Se débarrasser d'un objet.{END}"

    .global Unk_0820B991
Unk_0820B991:
    .string "Echanger un objet{END}"

    .global Unk_0820B9A3
Unk_0820B9A3:
    .string "Ranger les objets.{END}"

    .global Unk_0820B9B6
Unk_0820B9B6:
    .string "Voir les objets vitaux.{END}"

    .global Unk_0820B9CE
Unk_0820B9CE:
    .string "OBJ{END}"

    .global Unk_0820B9D2
Unk_0820B9D2:
    .string "SORT{END}"

    .global Unk_0820B9D7
Unk_0820B9D7:
    .string "EQIP{END}"

    .global Unk_0820B9DC
Unk_0820B9DC:
    .string "POS{END}"

    .global Unk_0820B9E0
Unk_0820B9E0:
    .string "CHNG{END}"

    .global Unk_0820B9E5
Unk_0820B9E5:
    .string "FIN{END}"

    .global Unk_0820B9E9
Unk_0820B9E9:
    .string "Changer quel personnage ?{END}"

    .global Unk_0820BA03
Unk_0820BA03:
    .string "Avec quel personnage ?{END}"

    .global Unk_0820BA1A
Unk_0820BA1A:
    .string "Creuser{END}"

    .global Unk_0820BA22
Unk_0820BA22:
    .string "Jeter quel objet ?{END}"

    .global Unk_0820BA35
Unk_0820BA35:
    .string "AUCUN{END}"

    .global Unk_0820BA3B
Unk_0820BA3B:
    .string "OTER{END}"

    .global Unk_0820BA40
Unk_0820BA40:
    .string "Echanger quelle position ?{END}"

    .global Unk_0820BA5B
Unk_0820BA5B:
    .string "Faire une sauvegarde{END}"

    .global Unk_0820BA70
Unk_0820BA70:
    .string "rapide ?{END}"

    .global Unk_0820BA79
Unk_0820BA79:
    .string "AVERTISSEMENT : OK pour{END}"

    .global Unk_0820BA91
Unk_0820BA91:
    .string "écrasement des données {END}"

    .global Unk_0820BAA9
Unk_0820BAA9:
    .string "existantes ?{END}"

    .global Unk_0820BAB6
Unk_0820BAB6:
    .string "Sauvegarde rapide{END}"

    .global Unk_0820BAC8
Unk_0820BAC8:
    .string "réussie.{END}"

    .global Unk_0820BAD1
Unk_0820BAD1:
    .string "Oui{END}"

    .global Unk_0820BAD5
Unk_0820BAD5:
    .string "Non{END}"

    .global Unk_0820BAD9
Unk_0820BAD9:
    .string "Bouton A pour plus d'infos{END}"

    .global Unk_0820BAF4
Unk_0820BAF4:
    .string "Quel objet ?{END}"

    .global Unk_0820BB01
Unk_0820BB01:
    .string "{0x8A}Einhändig{END}"

    .global Unk_0820BB0C
Unk_0820BB0C:
    .string "{0x8A}Zweihändig{END}"

    .global Unk_0820BB18
Unk_0820BB18:
    .string "{0x83}ETC{END}"

    .global Unk_0820BB1D
Unk_0820BB1D:
    .string "{0x83}HLM{END}"

    .global Unk_0820BB22
Unk_0820BB22:
    .string "{0x83}RST{END}"

    .global Unk_0820BB27
Unk_0820BB27:
    .string "{0x83}SCH{END}"

    .global Unk_0820BB2C
Unk_0820BB2C:
    .string "{0x83}WAF{END}"

    .global Unk_0820BB31
Unk_0820BB31:
    .string "FEHLER!: SPEICHERFEHLER.{END}"

    .global Unk_0820BB4A
Unk_0820BB4A:
    .string "{0x8A}Une main{END}"

    .global Unk_0820BB54
Unk_0820BB54:
    .string "{0x8A}Deux mains{END}"

    .global Unk_0820BB60
Unk_0820BB60:
    .string "{0x83}ETC{END}"

    .global Unk_0820BB65
Unk_0820BB65:
    .string "{0x83}CAS{END}"

    .global Unk_0820BB6A
Unk_0820BB6A:
    .string "{0x83}HAB{END}"

    .global Unk_0820BB6F
Unk_0820BB6F:
    .string "{0x83}BOU{END}"

    .global Unk_0820BB74
Unk_0820BB74:
    .string "{0x83}ARM{END}"

    .global Unk_0820BB79
Unk_0820BB79:
    .string "ERREUR : ECHEC DE SAUVEGARDE !.{END}"

    .global Unk_0820BB99
Unk_0820BB99:
    .string "{0x8A}One handed{END}"

    .global Unk_0820BBA5
Unk_0820BBA5:
    .string "{0x8A}Two handed{END}"

    .global Unk_0820BBB1
Unk_0820BBB1:
    .string "{0x83}ETC{END}"

    .global Unk_0820BBB6
Unk_0820BBB6:
    .string "{0x83}HLM{END}"

    .global Unk_0820BBBB
Unk_0820BBBB:
    .string "{0x83}ARM{END}"

    .global Unk_0820BBC0
Unk_0820BBC0:
    .string "{0x83}SHD{END}"

    .global Unk_0820BBC5
Unk_0820BBC5:
    .string "{0x83}WPN{END}"

    .global Unk_0820BBCA
Unk_0820BBCA:
    .string "{END}"

    .global Unk_0820BBCB
Unk_0820BBCB:
    .string "{END}"

