    .global Unk_08188380
Unk_08188380:
    .string "Empty{END}"

    .global Unk_08188386
Unk_08188386:
    .string "No equip{END}"

    .global Unk_0818838F
Unk_0818838F:
    .string "No item to trade in.{END}"

    .global Unk_081883A4
Unk_081883A4:
    .string "I buy {END}"

    .global Unk_081883AB
Unk_081883AB:
    .string " for {END}"

    .global Unk_081883B1
Unk_081883B1:
    .string "GP.{END}"

    .global Unk_081883B5
Unk_081883B5:
    .string "I can't trade it in.{END}"

    .global Unk_081883CA
Unk_081883CA:
    .string "We don't trade in {END}"

    .global Unk_081883DD
Unk_081883DD:
    .string ".{END}"

    .global Unk_081883DF
Unk_081883DF:
    .string "No item space available.{END}"

    .global Unk_081883F8
Unk_081883F8:
    .string "Item  Coin{END}"

    .global Unk_08188403
Unk_08188403:
    .string "Dpst  Draw{END}"

    .global Unk_0818840E
Unk_0818840E:
    .string "Cash:{END}"

    .global Unk_08188414
Unk_08188414:
    .string "In Bank:{END}"

    .global Unk_0818841D
Unk_0818841D:
    .string "Deposit:{END}"

    .global Unk_08188426
Unk_08188426:
    .string "Withdraw:{END}"

    .global Unk_08188430
Unk_08188430:
    .string "Whose name will you change?{END}"

    .global Unk_0818844C
Unk_0818844C:
    .string "You can't sell this.{END}"

    .global Unk_08188461
Unk_08188461:
    .string "OK to trade in?       Yes No{END}"

    .global Unk_0818847E
Unk_0818847E:
    .string "How many?{END}"

    .global Unk_08188488
Unk_08188488:
    .string "OK to sell?          Yes No{END}"

    .global Unk_081884A4
Unk_081884A4:
    .string "Use D-pad to change.{END}"

    .global Unk_081884B9
Unk_081884B9:
    .string "Money overflows. OK?  Yes No{END}"

    .global Unk_081884D6
Unk_081884D6:
    .string "Buy{END}"

    .global Unk_081884DA
Unk_081884DA:
    .string "Sell{END}"

    .global Unk_081884DF
Unk_081884DF:
    .string "Exit{END}"

    .global Unk_081884E4
Unk_081884E4:
    .string "Trde{END}"

    .global Unk_081884E9
Unk_081884E9:
    .string "What will you do?{END}"

    .global Unk_081884FB
Unk_081884FB:
    .string "Not enough money.{END}"

    .global Unk_0818850D
Unk_0818850D:
    .string "You can't carry any more.{END}"

    .global Unk_08188527
Unk_08188527:
    .string "You can't sell it.{END}"

    .global Unk_0818853A
Unk_0818853A:
    .string "N/A for your party members.{END}"

    .global Unk_08188556
Unk_08188556:
    .string "How much will you withdraw?{END}"

    .global Unk_08188572
Unk_08188572:
    .string "How much will you deposit?{END}"

    .global Unk_0818858D
Unk_0818858D:
    .string "Libre{END}"

    .global Unk_08188593
Unk_08188593:
    .string "Néant{END}"

    .global Unk_08188599
Unk_08188599:
    .string "Pas d'objet à échanger.{END}"

    .global Unk_081885B1
Unk_081885B1:
    .string "J'achète {END}"

    .global Unk_081885BB
Unk_081885BB:
    .string " pour {END}"

    .global Unk_081885C2
Unk_081885C2:
    .string "PO.{END}"

    .global Unk_081885C6
Unk_081885C6:
    .string "Je ne peux échanger.{END}"

    .global Unk_081885DB
Unk_081885DB:
    .string "Nous n'échangeons pas {END}"

    .global Unk_081885F2
Unk_081885F2:
    .string "Pas d'espace.{END}"

    .global Unk_08188600
Unk_08188600:
    .string "Obj.  PO{END}"

    .global Unk_08188609
Unk_08188609:
    .string "Dépô  Retr{END}"

    .global Unk_08188614
Unk_08188614:
    .string "Argent :{END}"

    .global Unk_0818861D
Unk_0818861D:
    .string "A la banque{END}"

    .global Unk_08188629
Unk_08188629:
    .string "Dépôt :{END}"

    .global Unk_08188631
Unk_08188631:
    .string "Retrait :{END}"

    .global Unk_0818863B
Unk_0818863B:
    .string "Changer quel nom ?{END}"

    .global Unk_0818864E
Unk_0818864E:
    .string "Impossible à vendre{END}"

    .global Unk_08188662
Unk_08188662:
    .string "OK pour échange ?    Oui Non{END}"

    .global Unk_0818867F
Unk_0818867F:
    .string "Combien ?{END}"

    .global Unk_08188689
Unk_08188689:
    .string "OK pour vente ?      Oui Non{END}"

    .global Unk_081886A6
Unk_081886A6:
    .string "Changer au Pavé Multi{END}"

    .global Unk_081886BC
Unk_081886BC:
    .string "OK pour dépassement d'argent ?  Oui Non{END}"

    .global Unk_081886E4
Unk_081886E4:
    .string "Ach.{END}"

    .global Unk_081886E9
Unk_081886E9:
    .string "Ven.{END}"

    .global Unk_081886EE
Unk_081886EE:
    .string "Fin{END}"

    .global Unk_081886F2
Unk_081886F2:
    .string "Troc{END}"

    .global Unk_081886F7
Unk_081886F7:
    .string "Que voulez-vous faire ?{END}"

    .global Unk_0818870F
Unk_0818870F:
    .string "Pas assez d'argent.{END}"

    .global Unk_08188723
Unk_08188723:
    .string "Impossible de porter plus{END}"

    .global Unk_0818873D
Unk_0818873D:
    .string "Vous ne pouvez pas vendre ceci{END}"

    .global Unk_0818875C
Unk_0818875C:
    .string "Ne s'applique pas aux membres du groupe.{END}"

    .global Unk_08188785
Unk_08188785:
    .string "Combien voulez-vous retirer ?{END}"

    .global Unk_081887A3
Unk_081887A3:
    .string "Combien voulez-vous déposer ?{END}"

    .global Unk_081887C1
Unk_081887C1:
    .string "Leer{END}"

    .global Unk_081887C6
Unk_081887C6:
    .string "K.Ausr.{END}"

    .global Unk_081887CE
Unk_081887CE:
    .string "Kein Tauschobj. in.{END}"

    .global Unk_081887E2
Unk_081887E2:
    .string "Kaufe {END}"

    .global Unk_081887E9
Unk_081887E9:
    .string " für {END}"

    .global Unk_081887EF
Unk_081887EF:
    .string "G.{END}"

    .global Unk_081887F2
Unk_081887F2:
    .string "Ich tausche nicht:{END}"

    .global Unk_08188805
Unk_08188805:
    .string "Wir handeln nicht in: {END}"

    .global Unk_0818881C
Unk_0818881C:
    .string "Kein Platz für Objekt.{END}"

    .global Unk_08188833
Unk_08188833:
    .string "Obj   Münz{END}"

    .global Unk_0818883E
Unk_0818883E:
    .string "Einl  Abh{END}"

    .global Unk_08188848
Unk_08188848:
    .string "Bar:{END}"

    .global Unk_0818884D
Unk_0818884D:
    .string "In Bank:{END}"

    .global Unk_08188856
Unk_08188856:
    .string "Einz.:{END}"

    .global Unk_0818885D
Unk_0818885D:
    .string "Abh.:{END}"

    .global Unk_08188863
Unk_08188863:
    .string "Wessen Namen ändern?{END}"

    .global Unk_08188878
Unk_08188878:
    .string "Nicht verkäuflich.{END}"

    .global Unk_0818888B
Unk_0818888B:
    .string "Handeln OK?          Ja Nein{END}"

    .global Unk_081888A8
Unk_081888A8:
    .string "Wie viel{END}"

    .global Unk_081888B1
Unk_081888B1:
    .string "Verkauf OK?          Ja Nein{END}"

    .global Unk_081888CE
Unk_081888CE:
    .string "StKrz zum Ändern.{END}"

    .global Unk_081888E0
Unk_081888E0:
    .string "Geldüberlauf OK?  Ja  Nein{END}"

    .global Unk_081888FB
Unk_081888FB:
    .string "Kauf{END}"

    .global Unk_08188900
Unk_08188900:
    .string "Verk{END}"

    .global Unk_08188905
Unk_08188905:
    .string "Ende{END}"

    .global Unk_0818890A
Unk_0818890A:
    .string "Hndl{END}"

    .global Unk_0818890F
Unk_0818890F:
    .string "Was möchtest du tun?{END}"

    .global Unk_08188924
Unk_08188924:
    .string "Nicht genug Geld.{END}"

    .global Unk_08188936
Unk_08188936:
    .string "Kann nicht mehr tragen{END}"

    .global Unk_0818894D
Unk_0818894D:
    .string "Nicht verkaufbar{END}"

    .global Unk_0818895E
Unk_0818895E:
    .string "NV für Gruppenmitglieder.{END}"

    .global Unk_08188978
Unk_08188978:
    .string "Wie viel abholen?{END}"

    .global Unk_0818898A
Unk_0818898A:
    .string "Wie viel einlegen?{END}"

    .global Unk_0818899D
Unk_0818899D:
    .string "G{END}"

    .global Unk_0818899F
Unk_0818899F:
    .string "PO{END}"

    .global Unk_081889A2
Unk_081889A2:
    .string "G{END}"

    .global Unk_081889A4
Unk_081889A4:
    .string "{END}"

    .global Unk_081889A5
Unk_081889A5:
    .byte 1

    .global Unk_081889A6
Unk_081889A6:
    .string "{END}"
