    .global Unk_08218AF8
Unk_08218AF8:
    .string "{0x13}{0x01} grinned fearlessly."

    .global Unk_08218B0E
Unk_08218B0E:
    .string "{0x11}{0x01} sourit sans peur."

    .global Unk_08218B22
Unk_08218B22:
    .string "{0x11}{0x01} grinst furchtlos."

    .global Unk_08218B36
Unk_08218B36:
    .string "{CODE7 0x01} got up."

    .global Unk_08218B40
Unk_08218B40:
    .string "{ITEM 0x01} est debout."

    .global Unk_08218B4E
Unk_08218B4E:
    .string "{0x11}{0x01} steht wieder auf."

    .global Unk_08218B62
Unk_08218B62:
    .string "{0x0E}{0x01} seems alright."

    .global Unk_08218B73
Unk_08218B73:
    .string "{0x11}{0x01} a l'air en forme."

    .global Unk_08218B87
Unk_08218B87:
    .string "{ITEM 0x01} scheint OK."

    .global Unk_08218B95
Unk_08218B95:
    .string "{DEFENSE 0x01} began crying."

    .global Unk_08218BA5
Unk_08218BA5:
    .string "{CODE7 0x01} pleure."

    .global Unk_08218BAF
Unk_08218BAF:
    .string "{STRING 0x01} heult auf."

    .global Unk_08218BBC
Unk_08218BBC:
    .string "{CODE8 0x01} got mad!"

    .global Unk_08218BC7
Unk_08218BC7:
    .string "{0x0E}{0x01} est en colère!"

    .global Unk_08218BD8
Unk_08218BD8:
    .string "{WEAPON 0x01} dreht durch!"

    .global Unk_08218BE7
Unk_08218BE7:
    .string "{DEFENSE 0x01} is intrigued."

    .global Unk_08218BF7
Unk_08218BF7:
    .string "{DEFENSE 0x01} est intrigué."

    .global Unk_08218C07
Unk_08218C07:
    .string "{0x12}{0x01} ist unbeeindruckt."

    .global Unk_08218C1C
Unk_08218C1C:
    .string "{CODE8 0x37}o effect"

    .global Unk_08218C26
Unk_08218C26:
    .string "{STRING 0x2A}ucun effet"

    .global Unk_08218C32
Unk_08218C32:
    .string "{STRING 0x34}ein Effekt"

    .global Unk_08218C3E
Unk_08218C3E:
    .string "{CODE7 0x2A}rrrrgh!"

    .global Unk_08218C47
Unk_08218C47:
    .string "{CODE8 0x2A}aaaaaah!"

    .global Unk_08218C51
Unk_08218C51:
    .string "{CODE7 0x2A}rrrrgh!{END}"

    @Unreferenced string
    .global Unk_08218C5B
Unk_08218C5B:
    .string "{END}"

    .align 2
    .global Unk_08218C5C
Unk_08218C5C:
    .word Unk_08218AF8 @ 0 / 0x0
    .word Unk_08218B36 @ 1 / 0x1
    .word Unk_08218B62 @ 2 / 0x2
    .word Unk_08218B95 @ 3 / 0x3
    .word Unk_08218BBC @ 4 / 0x4
    .word Unk_08218BE7 @ 5 / 0x5
    .word Unk_08218C1C @ 6 / 0x6
    .word Unk_08218C3E @ 7 / 0x7
    
    .align 2
    .global Unk_08218C7C
Unk_08218C7C:
    .word Unk_08218B0E @ 0 / 0x0
    .word Unk_08218B40 @ 1 / 0x1
    .word Unk_08218B73 @ 2 / 0x2
    .word Unk_08218BA5 @ 3 / 0x3
    .word Unk_08218BC7 @ 4 / 0x4
    .word Unk_08218BF7 @ 5 / 0x5
    .word Unk_08218C26 @ 6 / 0x6
    .word Unk_08218C47 @ 7 / 0x7
    
    .align 2
    .global Unk_08218C9C
Unk_08218C9C:
    .word Unk_08218B22 @ 0 / 0x0
    .word Unk_08218B4E @ 1 / 0x1
    .word Unk_08218B87 @ 2 / 0x2
    .word Unk_08218BAF @ 3 / 0x3
    .word Unk_08218BD8 @ 4 / 0x4
    .word Unk_08218C07 @ 5 / 0x5
    .word Unk_08218C32 @ 6 / 0x6
    .word Unk_08218C51 @ 7 / 0x7
