    .global Unk_08215C98
Unk_08215C98:
    .string "/{END}"

    .global Unk_08215C9A
Unk_08215C9A:
    .string "ATTACK{END}"

    .global Unk_08215CA1
Unk_08215CA1:
    .string "DEFENSE{END}"

    .global Unk_08215CA9
Unk_08215CA9:
    .string "ACTIVE{END}"

    .global Unk_08215CB0
Unk_08215CB0:
    .string "INTLGCE{END}"

    .global Unk_08215CB8
Unk_08215CB8:
    .string "FATE{END}"

    .global Unk_08215CBD
Unk_08215CBD:
    .string "MAG DEF{END}"

    .global Unk_08215CC5
Unk_08215CC5:
    .string "MAG DEF{END}"

    .global Unk_08215CCD
Unk_08215CCD:
    .string "WPN{END}"

    .global Unk_08215CD1
Unk_08215CD1:
    .string "SHD{END}"

    .global Unk_08215CD5
Unk_08215CD5:
    .string "ARM{END}"

    .global Unk_08215CD9
Unk_08215CD9:
    .string "HLM{END}"

    .global Unk_08215CDD
Unk_08215CDD:
    .string "ETC{END}"

    .global Unk_08215CE1
Unk_08215CE1:
    .string "Revert{END}"

    .global Unk_08215CE8
Unk_08215CE8:
    .string "STRNGTH{END}"

    .global Unk_08215CF0
Unk_08215CF0:
    .string "VIGOR{END}"

    .global Unk_08215CF6
Unk_08215CF6:
    .string "AGILITY{END}"

    .global Unk_08215CFE
Unk_08215CFE:
    .string "WISDOM{END}"

    .global Unk_08215D05
Unk_08215D05:
    .string "LUCK{END}"

    .global Unk_08215D0A
Unk_08215D0A:
    .string " Psn{END}"

    .global Unk_08215D0F
Unk_08215D0F:
    .string " Zom{END}"

    .global Unk_08215D14
Unk_08215D14:
    .string " Crs{END}"

    .global Unk_08215D19
Unk_08215D19:
    .string "Fuse{END}"

    .global Unk_08215D1E
Unk_08215D1E:
    .string "Crs Psn{END}"

    .global Unk_08215D26
Unk_08215D26:
    .string "Crs Zom{END}"

    .global Unk_08215D2E
Unk_08215D2E:
    .string "Psn Zom{END}"

    .global Unk_08215D36
Unk_08215D36:
    .string "Stun{END}"

    .global Unk_08215D3B
Unk_08215D3B:
    .string "N/A{END}"

    .global Unk_08215D3F
Unk_08215D3F:
    .string "/{END}"

    .global Unk_08215D41
Unk_08215D41:
    .string "ANGRFF{END}"

    .global Unk_08215D48
Unk_08215D48:
    .string "VERTEID{END}"

    .global Unk_08215D50
Unk_08215D50:
    .string "AKTIV{END}"

    .global Unk_08215D56
Unk_08215D56:
    .string "INTLGNZ{END}"

    .global Unk_08215D5E
Unk_08215D5E:
    .string "CHRSMA{END}"

    .global Unk_08215D65
Unk_08215D65:
    .string "MAG.RES.{END}"

    .global Unk_08215D6E
Unk_08215D6E:
    .string "MAG VER{END}"

    .global Unk_08215D76
Unk_08215D76:
    .string "WFF{END}"

    .global Unk_08215D7A
Unk_08215D7A:
    .string "SHD{END}"

    .global Unk_08215D7E
Unk_08215D7E:
    .string "RST{END}"

    .global Unk_08215D82
Unk_08215D82:
    .string "HLM{END}"

    .global Unk_08215D86
Unk_08215D86:
    .string "SON{END}"

    .global Unk_08215D8A
Unk_08215D8A:
    .string "Umkehr{END}"

    .global Unk_08215D91
Unk_08215D91:
    .string "STÄRKE{END}"

    .global Unk_08215D98
Unk_08215D98:
    .string "ENRGIE{END}"

    .global Unk_08215D9F
Unk_08215D9F:
    .string "AGILIT{END}"

    .global Unk_08215DA6
Unk_08215DA6:
    .string "WEISHT{END}"

    .global Unk_08215DAD
Unk_08215DAD:
    .string "GLÜCK{END}"

    .global Unk_08215DB3
Unk_08215DB3:
    .string " Gft{END}"

    .global Unk_08215DB8
Unk_08215DB8:
    .string " Zom{END}"

    .global Unk_08215DBD
Unk_08215DBD:
    .string " Vfl{END}"

    .global Unk_08215DC2
Unk_08215DC2:
    .string "Fus{END}"

    .global Unk_08215DC6
Unk_08215DC6:
    .string "Vfl Gft{END}"

    .global Unk_08215DCE
Unk_08215DCE:
    .string "Vfl Zom{END}"

    .global Unk_08215DD6
Unk_08215DD6:
    .string "Gft Zom{END}"

    .global Unk_08215DDE
Unk_08215DDE:
    .string "Btbt{END}"

    .global Unk_08215DE3
Unk_08215DE3:
    .string "N/V{END}"

    .global Unk_08215DE7
Unk_08215DE7:
    .string "/{END}"

    .global Unk_08215DE9
Unk_08215DE9:
    .string "ATTAQUE{END}"

    .global Unk_08215DF1
Unk_08215DF1:
    .string "DEFENSE{END}"

    .global Unk_08215DF9
Unk_08215DF9:
    .string "ACTIVE{END}"

    .global Unk_08215E00
Unk_08215E00:
    .string "INTEL{END}"

    .global Unk_08215E06
Unk_08215E06:
    .string "DESTIN{END}"

    .global Unk_08215E0D
Unk_08215E0D:
    .string "DEF MAG{END}"

    .global Unk_08215E15
Unk_08215E15:
    .string "DEF MAG{END}"

    .global Unk_08215E1D
Unk_08215E1D:
    .string "ARM{END}"

    .global Unk_08215E21
Unk_08215E21:
    .string "BOU{END}"

    .global Unk_08215E25
Unk_08215E25:
    .string "HAB{END}"

    .global Unk_08215E29
Unk_08215E29:
    .string "CAS{END}"

    .global Unk_08215E2D
Unk_08215E2D:
    .string "ETC{END}"

    .global Unk_08215E31
Unk_08215E31:
    .string "Inverser{END}"

    .global Unk_08215E3A
Unk_08215E3A:
    .string "FORCE{END}"

    .global Unk_08215E40
Unk_08215E40:
    .string "VIGUEUR{END}"

    .global Unk_08215E48
Unk_08215E48:
    .string "AGILITE{END}"

    .global Unk_08215E50
Unk_08215E50:
    .string "SAGESSE{END}"

    .global Unk_08215E58
Unk_08215E58:
    .string "CHANCE{END}"

    .global Unk_08215E5F
Unk_08215E5F:
    .string " Psn{END}"

    .global Unk_08215E64
Unk_08215E64:
    .string " Zom{END}"

    .global Unk_08215E69
Unk_08215E69:
    .string " Crs{END}"

    .global Unk_08215E6E
Unk_08215E6E:
    .string "Fus{END}"

    .global Unk_08215E72
Unk_08215E72:
    .string "Crs Psn{END}"

    .global Unk_08215E7A
Unk_08215E7A:
    .string "Crs Zom{END}"

    .global Unk_08215E82
Unk_08215E82:
    .string "Psn Zom{END}"

    .global Unk_08215E8A
Unk_08215E8A:
    .string "Etourd{END}"

    .global Unk_08215E91
Unk_08215E91:
    .string "Non Ap{END}"

