    .global Unk_08183140
Unk_08183140:
    .string "LANGUAGE{END}"

    .global Unk_08183149
Unk_08183149:
    .string "LANGUE{END}"

    .global Unk_08183150
Unk_08183150:
    .string "SPRACHE{END}"

    .global Unk_08183158
Unk_08183158:
    .string "English{END}"

    .global Unk_08183160
Unk_08183160:
    .string "Français{END}"

    .global Unk_08183169
Unk_08183169:
    .string "Deutsch{END}"

    .global Unk_08183171
Unk_08183171:
    .string "OK to delete the data{END}"

    .global Unk_08183187
Unk_08183187:
    .string "?{END}"

    .global Unk_08183189
Unk_08183189:
    .string "YES  NO{END}"

    .global Unk_08183191
Unk_08183191:
    .string "Yes{END}"

    .global Unk_08183195
Unk_08183195:
    .string " No{END}"

    .global Unk_08183199
Unk_08183199:
    .string "cù{END}"

    .global Unk_0818319C
Unk_0818319C:
    .string "ccù{END}"

    .global Unk_081831A0
Unk_081831A0:
    .string "EXCHANGE{END}"

    .global Unk_081831A9
Unk_081831A9:
    .string "WARNING: Save Data{END}"

    .global Unk_081831BC
Unk_081831BC:
    .string " already exists.{END}"

    .global Unk_081831CD
Unk_081831CD:
    .string "WARNING: Starting the{END}"

    .global Unk_081831E3
Unk_081831E3:
    .string "game from the Quick Save{END}"

    .global Unk_081831FC
Unk_081831FC:
    .string "point will delete the{END}"

    .global Unk_08183212
Unk_08183212:
    .string "data.{END}"

    .global Unk_08183218
Unk_08183218:
    .string "Start the game from the{END}"

    .global Unk_08183230
Unk_08183230:
    .string "Quick Save point?{END}"

    .global Unk_08183242
Unk_08183242:
    .string "{END}"

    .global Unk_08183243
Unk_08183243:
    .string "Unfortunately, the saved{END}"

    .global Unk_0818325C
Unk_0818325C:
    .string "data has been erased.{END}"

    .global Unk_08183272
Unk_08183272:
    .string "SCENARIO{END}"

    .global Unk_0818327B
Unk_0818327B:
    .string "GAME START{END}"

    .global Unk_08183286
Unk_08183286:
    .string "NEW GAME{END}"

    .global Unk_0818328F
Unk_0818328F:
    .string "COPY{END}"

    .global Unk_08183294
Unk_08183294:
    .string "ERASE{END}"

    .global Unk_0818329A
Unk_0818329A:
    .string "No.{END}"

    .global Unk_0818329E
Unk_0818329E:
    .string "Blank{END}"

    .global Unk_081832A4
Unk_081832A4:
    .string "Text Speed{END}"

    .global Unk_081832AF
Unk_081832AF:
    .string "Dash{END}"

    .global Unk_081832B4
Unk_081832B4:
    .string "{0xA3}{0x9B}{0xC6}{0xDF}{END}"

    .global Unk_081832B9
Unk_081832B9:
    .string "Music{END}"

    .global Unk_081832BF
Unk_081832BF:
    .string "END{END}"

    .global Unk_081832C3
Unk_081832C3:
    .string "Fast{END}"

    .global Unk_081832C8
Unk_081832C8:
    .string "Nrml{END}"

    .global Unk_081832CD
Unk_081832CD:
    .string "Slow{END}"

    .global Unk_081832D2
Unk_081832D2:
    .string "Nrml{END}"

    .global Unk_081832D7
Unk_081832D7:
    .string "Auto{END}"

    .global Unk_081832DC
Unk_081832DC:
    .string "{0xA5}{0xAB}{0xC2}{0x9D}{END}"

    .global Unk_081832E1
Unk_081832E1:
    .string "{0xBB}{0xB1}{0xBF}{0xC1}{END}"

    .global Unk_081832E6
Unk_081832E6:
    .string "ON{END}"

    .global Unk_081832E9
Unk_081832E9:
    .string "OFF{END}"

    .global Unk_081832ED
Unk_081832ED:
    .string "{0x7F}   {END}"

    .global Unk_081832F2
Unk_081832F2:
    .string "{END}"

    .global Unk_081832F3
Unk_081832F3:
    .string "{END}"

    .global Unk_081832F4
Unk_081832F4:
    .string "{END}"

    .global Unk_081832F5
Unk_081832F5:
    .string " {0x7F}  {END}"

    .global Unk_081832FA
Unk_081832FA:
    .string "{END}"

    .global Unk_081832FB
Unk_081832FB:
    .string "{END}"

    .global Unk_081832FC
Unk_081832FC:
    .string "{END}"

    .global Unk_081832FD
Unk_081832FD:
    .string "  {0x7F} {END}"

    .global Unk_08183302
Unk_08183302:
    .string "{END}"

    .global Unk_08183303
Unk_08183303:
    .string "{END}"

    .global Unk_08183304
Unk_08183304:
    .string "{END}"

    .global Unk_08183305
Unk_08183305:
    .string "   {0x7F}{END}"

    .global Unk_0818330A
Unk_0818330A:
    .string "{END}"

    .global Unk_0818330B
Unk_0818330B:
    .string "{END}"

    .global Unk_0818330C
Unk_0818330C:
    .string "{END}"

    .global Unk_0818330D
Unk_0818330D:
    .string "Daten löschen OK {END}"

    .global Unk_0818331F
Unk_0818331F:
    .string "?{END}"

    .global Unk_08183321
Unk_08183321:
    .string "JA NEIN{END}"

    .global Unk_08183329
Unk_08183329:
    .string "Ja{END}"

    .global Unk_0818332C
Unk_0818332C:
    .string "Nein{END}"

    .global Unk_08183331
Unk_08183331:
    .string "AUSTAUSCH{END}"

    .global Unk_0818333B
Unk_0818333B:
    .string "WARNUNG: Daten {END}"

    .global Unk_0818334B
Unk_0818334B:
    .string "existieren bereits.{END}"

    .global Unk_0818335F
Unk_0818335F:
    .string "WARNUNG: Alte{END}"

    .global Unk_0818336D
Unk_0818336D:
    .string "Daten werden{END}"

    .global Unk_0818337A
Unk_0818337A:
    .string "gelöscht!{END}"

    .global Unk_08183384
Unk_08183384:
    .string "{END}"

    .global Unk_08183385
Unk_08183385:
    .string "Quick-Save{END}"

    .global Unk_08183390
Unk_08183390:
    .string "starten?{END}"

    .global Unk_08183399
Unk_08183399:
    .string "{END}"

    .global Unk_0818339A
Unk_0818339A:
    .string "Die gespeicherten Daten{END}"

    .global Unk_081833B2
Unk_081833B2:
    .string "wurden gelöscht{END}"

    .global Unk_081833C2
Unk_081833C2:
    .string "SZENARIO{END}"

    .global Unk_081833CB
Unk_081833CB:
    .string "SPIELSTART{END}"

    .global Unk_081833D6
Unk_081833D6:
    .string "NEUES SPIEL{END}"

    .global Unk_081833E2
Unk_081833E2:
    .string "KOPIE{END}"

    .global Unk_081833E8
Unk_081833E8:
    .string "LÖSCHEN{END}"

    .global Unk_081833F0
Unk_081833F0:
    .string "Nr.{END}"

    .global Unk_081833F4
Unk_081833F4:
    .string "Leer{END}"

    .global Unk_081833F9
Unk_081833F9:
    .string "Texttempo{END}"

    .global Unk_08183403
Unk_08183403:
    .string "Renn{END}"

    .global Unk_08183408
Unk_08183408:
    .string "Musik{END}"

    .global Unk_0818340E
Unk_0818340E:
    .string "ENDE{END}"

    .global Unk_08183413
Unk_08183413:
    .string "shnl{END}"

    .global Unk_08183418
Unk_08183418:
    .string "Nrml{END}"

    .global Unk_0818341D
Unk_0818341D:
    .string "Lngs{END}"

    .global Unk_08183422
Unk_08183422:
    .string "Nrml{END}"

    .global Unk_08183427
Unk_08183427:
    .string "Auto{END}"

    .global Unk_0818342C
Unk_0818342C:
    .string "AN{END}"

    .global Unk_0818342F
Unk_0818342F:
    .string "AUS{END}"

    .global Unk_08183433
Unk_08183433:
    .string "OK pour effacer{END}"

    .global Unk_08183443
Unk_08183443:
    .string "?{END}"

    .global Unk_08183445
Unk_08183445:
    .string "OUI  NON{END}"

    .global Unk_0818344E
Unk_0818344E:
    .string "Oui{END}"

    .global Unk_08183452
Unk_08183452:
    .string "Non{END}"

    .global Unk_08183456
Unk_08183456:
    .string "ECHANGER{END}"

    .global Unk_0818345F
Unk_0818345F:
    .string "AVERTISSEMENT: les données de{END}"

    .global Unk_0818347D
Unk_0818347D:
    .string " existent déjà.{END}"

    .global Unk_0818348D
Unk_0818348D:
    .string "AVERTISSEMENT : démarrer{END}"

    .global Unk_081834A6
Unk_081834A6:
    .string "la partie au point{END}"

    .global Unk_081834B9
Unk_081834B9:
    .string "de sauvegarde rapide {END}"

    .global Unk_081834CF
Unk_081834CF:
    .string "effacera les données.{END}"

    .global Unk_081834E5
Unk_081834E5:
    .string "Démarrer la partie à {END}"

    .global Unk_081834FB
Unk_081834FB:
    .string "partir du point de {END}"

    .global Unk_0818350F
Unk_0818350F:
    .string "sauvegarde rapide ?{END}"

    .global Unk_08183523
Unk_08183523:
    .string "Hélas, les données{END}"

    .global Unk_08183536
Unk_08183536:
    .string "sauvegardées ont été effacées.{END}"

    .global Unk_08183555
Unk_08183555:
    .string "SCENARIO{END}"

    .global Unk_0818355E
Unk_0818355E:
    .string "LANCER JEU{END}"

    .global Unk_08183569
Unk_08183569:
    .string "NOUV PARTIE{END}"

    .global Unk_08183575
Unk_08183575:
    .string "COPIER{END}"

    .global Unk_0818357C
Unk_0818357C:
    .string "EFFACER{END}"

    .global Unk_08183584
Unk_08183584:
    .string "No.{END}"

    .global Unk_08183588
Unk_08183588:
    .string "Vide{END}"

    .global Unk_0818358D
Unk_0818358D:
    .string "Texte{END}"

    .global Unk_08183593
Unk_08183593:
    .string "Courir{END}"

    .global Unk_0818359A
Unk_0818359A:
    .string "Musique{END}"

    .global Unk_081835A2
Unk_081835A2:
    .string "Fin{END}"

    .global Unk_081835A6
Unk_081835A6:
    .string "Rapd{END}"

    .global Unk_081835AB
Unk_081835AB:
    .string "Nrml{END}"

    .global Unk_081835B0
Unk_081835B0:
    .string "Lent{END}"

    .global Unk_081835B5
Unk_081835B5:
    .string "Nrml{END}"

    .global Unk_081835BA
Unk_081835BA:
    .string "Auto{END}"

    .global Unk_081835BF
Unk_081835BF:
    .string "Oui{END}"

    .global Unk_081835C3
Unk_081835C3:
    .string "Non{END}"

