    .global Unk_08213888
Unk_08213888:
    .string "Robe{END}"

    .global Unk_0821388D
Unk_0821388D:
    .string "SuedeCP{END}"

    .global Unk_08213895
Unk_08213895:
    .string "Dress{END}"

    .global Unk_0821389B
Unk_0821389B:
    .string "MetalAR{END}"

    .global Unk_082138A3
Unk_082138A3:
    .string "SilkGN{END}"

    .global Unk_082138AA
Unk_082138AA:
    .string "Cloth{END}"

    .global Unk_082138B0
Unk_082138B0:
    .string "LightCL{END}"

    .global Unk_082138B8
Unk_082138B8:
    .string "Gown{END}"

    .global Unk_082138BD
Unk_082138BD:
    .string "ArmPad{END}"

    .global Unk_082138C4
Unk_082138C4:
    .string "WolfSkin{END}"

    .global Unk_082138CD
Unk_082138CD:
    .string "RangerVT{END}"

    .global Unk_082138D6
Unk_082138D6:
    .string "BronzAR{END}"

    .global Unk_082138DE
Unk_082138DE:
    .string "PlateAR{END}"

    .global Unk_082138E6
Unk_082138E6:
    .string "Dummy{END}"

    .global Unk_082138EC
Unk_082138EC:
    .string "FlameAR{END}"

    .global Unk_082138F4
Unk_082138F4:
    .string "PrisnCL{END}"

    .global Unk_082138FC
Unk_082138FC:
    .string "S.Armor{END}"

    .global Unk_08213904
Unk_08213904:
    .string "IcyAR{END}"

    .global Unk_0821390A
Unk_0821390A:
    .string "WorldML{END}"

    .global Unk_08213912
Unk_08213912:
    .string "Dummy{END}"

    .global Unk_08213918
Unk_08213918:
    .string "SpineCL{END}"

    .global Unk_08213920
Unk_08213920:
    .string "ThiefCL{END}"

    .global Unk_08213928
Unk_08213928:
    .string "EvilRB{END}"

    .global Unk_0821392F
Unk_0821392F:
    .string "SuedeGN{END}"

    .global Unk_08213937
Unk_08213937:
    .string "SuedeAR{END}"

    .global Unk_0821393F
Unk_0821393F:
    .string "ChainML{END}"

    .global Unk_08213947
Unk_08213947:
    .string "IronML{END}"

    .global Unk_0821394E
Unk_0821394E:
    .string "WoolRB{END}"

    .global Unk_08213955
Unk_08213955:
    .string "SuedeRB{END}"

    .global Unk_0821395D
Unk_0821395D:
    .string "LifeAR{END}"

    .global Unk_08213964
Unk_08213964:
    .string "PowerAR{END}"

    .global Unk_0821396C
Unk_0821396C:
    .string "QuartzAR{END}"

    .global Unk_08213975
Unk_08213975:
    .string "AngleAR{END}"

    .global Unk_0821397D
Unk_0821397D:
    .string "Dummy{END}"

    .global Unk_08213983
Unk_08213983:
    .string "GuruCT{END}"

    .global Unk_0821398A
Unk_0821398A:
    .string "Dummy{END}"

    .global Unk_08213990
Unk_08213990:
    .string "Dummy{END}"

    .global Unk_08213996
Unk_08213996:
    .string "WorldAR{END}"

    .global Unk_0821399E
Unk_0821399E:
    .string "SageML{END}"

    .global Unk_082139A5
Unk_082139A5:
    .string "Dummy{END}"

    .global Unk_082139AB
Unk_082139AB:
    .string "MystRB{END}"

    .global Unk_082139B2
Unk_082139B2:
    .string "EarthRB{END}"

    .global Unk_082139BA
Unk_082139BA:
    .string "Dummy{END}"

    .global Unk_082139C0
Unk_082139C0:
    .string "AgileAR{END}"

    .global Unk_082139C8
Unk_082139C8:
    .string "Dummy{END}"

    .global Unk_082139CE
Unk_082139CE:
    .string "HuntCL{END}"

    .global Unk_082139D5
Unk_082139D5:
    .string "ClearCL{END}"

    .global Unk_082139DD
Unk_082139DD:
    .string "Dummy{END}"

    .global Unk_082139E3
Unk_082139E3:
    .string "WoodSH{END}"

    .global Unk_082139EA
Unk_082139EA:
    .string "Gauntlet{END}"

    .global Unk_082139F3
Unk_082139F3:
    .string "SuedeSH{END}"

    .global Unk_082139FB
Unk_082139FB:
    .string "GuardSH{END}"

    .global Unk_08213A03
Unk_08213A03:
    .string "Bracelet{END}"

    .global Unk_08213A0C
Unk_08213A0C:
    .string "IronSH{END}"

    .global Unk_08213A13
Unk_08213A13:
    .string "BronzSH{END}"

    .global Unk_08213A1B
Unk_08213A1B:
    .string "MetalSH{END}"

    .global Unk_08213A23
Unk_08213A23:
    .string "FlameSH{END}"

    .global Unk_08213A2B
Unk_08213A2B:
    .string "Dummy{END}"

    .global Unk_08213A31
Unk_08213A31:
    .string "S.Shld{END}"

    .global Unk_08213A38
Unk_08213A38:
    .string "IronSL{END}"

    .global Unk_08213A3F
Unk_08213A3F:
    .string "MetalSL{END}"

    .global Unk_08213A47
Unk_08213A47:
    .string "Dummy{END}"

    .global Unk_08213A4D
Unk_08213A4D:
    .string "Wrist{END}"

    .global Unk_08213A53
Unk_08213A53:
    .string "IcySH{END}"

    .global Unk_08213A59
Unk_08213A59:
    .string "ProSH{END}"

    .global Unk_08213A5F
Unk_08213A5F:
    .string "LoveBR{END}"

    .global Unk_08213A66
Unk_08213A66:
    .string "WindBR{END}"

    .global Unk_08213A6D
Unk_08213A6D:
    .string "RubyRG{END}"

    .global Unk_08213A74
Unk_08213A74:
    .string "Dummy{END}"

    .global Unk_08213A7A
Unk_08213A7A:
    .string "DarkBR{END}"

    .global Unk_08213A81
Unk_08213A81:
    .string "Dummy{END}"

    .global Unk_08213A87
Unk_08213A87:
    .string "MystSH{END}"

    .global Unk_08213A8E
Unk_08213A8E:
    .string "Glove{END}"

    .global Unk_08213A94
Unk_08213A94:
    .string "Dummy{END}"

    .global Unk_08213A9A
Unk_08213A9A:
    .string "TrapGrd{END}"

    .global Unk_08213AA2
Unk_08213AA2:
    .string "LightSH{END}"

    .global Unk_08213AAA
Unk_08213AAA:
    .string "MagicRG{END}"

    .global Unk_08213AB2
Unk_08213AB2:
    .string "Bandage{END}"

    .global Unk_08213ABA
Unk_08213ABA:
    .string "Dummy{END}"

    .global Unk_08213AC0
Unk_08213AC0:
    .string "SilverBR{END}"

    .global Unk_08213AC9
Unk_08213AC9:
    .string "Dummy{END}"

    .global Unk_08213ACF
Unk_08213ACF:
    .string "ColdSH{END}"

    .global Unk_08213AD6
Unk_08213AD6:
    .string "HuntGL{END}"

    .global Unk_08213ADD
Unk_08213ADD:
    .string "MaskSH{END}"

    .global Unk_08213AE4
Unk_08213AE4:
    .string "DragonSH{END}"

    .global Unk_08213AED
Unk_08213AED:
    .string "Dummy{END}"

    .global Unk_08213AF3
Unk_08213AF3:
    .string "LavaSH{END}"

    .global Unk_08213AFA
Unk_08213AFA:
    .string "Dummy{END}"

    .global Unk_08213B00
Unk_08213B00:
    .string "SuedeHT{END}"

    .global Unk_08213B08
Unk_08213B08:
    .string "Visor{END}"

    .global Unk_08213B0E
Unk_08213B0E:
    .string "HairBand{END}"

    .global Unk_08213B17
Unk_08213B17:
    .string "Tiara{END}"

    .global Unk_08213B1D
Unk_08213B1D:
    .string "ChainHT{END}"

    .global Unk_08213B25
Unk_08213B25:
    .string "G.Tiara{END}"

    .global Unk_08213B2D
Unk_08213B2D:
    .string "EchoHT{END}"

    .global Unk_08213B34
Unk_08213B34:
    .string "IronMask{END}"

    .global Unk_08213B3D
Unk_08213B3D:
    .string "Dummy{END}"

    .global Unk_08213B43
Unk_08213B43:
    .string "Dummy{END}"

    .global Unk_08213B49
Unk_08213B49:
    .string "StoneHT{END}"

    .global Unk_08213B51
Unk_08213B51:
    .string "GoldHT{END}"

    .global Unk_08213B58
Unk_08213B58:
    .string "FaceMask{END}"

    .global Unk_08213B61
Unk_08213B61:
    .string "AgileHT{END}"

    .global Unk_08213B69
Unk_08213B69:
    .string "NiceHT{END}"

    .global Unk_08213B70
Unk_08213B70:
    .string "MystSF{END}"

    .global Unk_08213B77
Unk_08213B77:
    .string "DivingHT{END}"

    .global Unk_08213B80
Unk_08213B80:
    .string "GaiaMask{END}"

    .global Unk_08213B89
Unk_08213B89:
    .string "HeadGear{END}"

    .global Unk_08213B92
Unk_08213B92:
    .string "CursedHT{END}"

    .global Unk_08213B9B
Unk_08213B9B:
    .string "ShellHT{END}"

    .global Unk_08213BA3
Unk_08213BA3:
    .string "StrawHT{END}"

    .global Unk_08213BAB
Unk_08213BAB:
    .string "IronHT{END}"

    .global Unk_08213BB2
Unk_08213BB2:
    .string "Dummy{END}"

    .global Unk_08213BB8
Unk_08213BB8:
    .string "TideHT{END}"

    .global Unk_08213BBF
Unk_08213BBF:
    .string "SkullHT{END}"

    .global Unk_08213BC7
Unk_08213BC7:
    .string "PowerHT{END}"

    .global Unk_08213BCF
Unk_08213BCF:
    .string "Domino{END}"

    .global Unk_08213BD6
Unk_08213BD6:
    .string "HornHT{END}"

    .global Unk_08213BDD
Unk_08213BDD:
    .string "Bandana{END}"

    .global Unk_08213BE5
Unk_08213BE5:
    .string "Turban{END}"

    .global Unk_08213BEC
Unk_08213BEC:
    .string "Dummy{END}"

    .global Unk_08213BF2
Unk_08213BF2:
    .string "LoveHT{END}"

    .global Unk_08213BF9
Unk_08213BF9:
    .string "Dummy{END}"

    .global Unk_08213BFF
Unk_08213BFF:
    .string "Dummy{END}"

    .global Unk_08213C05
Unk_08213C05:
    .string "Dummy{END}"

    .global Unk_08213C0B
Unk_08213C0B:
    .string "BronzHT{END}"

    .global Unk_08213C13
Unk_08213C13:
    .string "S.Helm{END}"

    .global Unk_08213C1A
Unk_08213C1A:
    .string "SunHT{END}"

    .global Unk_08213C20
Unk_08213C20:
    .string "WolfHT{END}"

    .global Unk_08213C27
Unk_08213C27:
    .string "IcyHT{END}"

    .global Unk_08213C2D
Unk_08213C2D:
    .string "Dummy{END}"

    .global Unk_08213C33
Unk_08213C33:
    .string "Dummy{END}"

    .global Unk_08213C39
Unk_08213C39:
    .string "Dummy{END}"

    .global Unk_08213C3F
Unk_08213C3F:
    .string "StarSH{END}"

    .global Unk_08213C46
Unk_08213C46:
    .string "Dummy{END}"

    .global Unk_08213C4C
Unk_08213C4C:
    .string "SkullRG{END}"

    .global Unk_08213C54
Unk_08213C54:
    .string "SkySH{END}"

    .global Unk_08213C5A
Unk_08213C5A:
    .string "Dummy{END}"

    .global Unk_08213C60
Unk_08213C60:
    .string "Dummy{END}"

    .global Unk_08213C66
Unk_08213C66:
    .string "DragonHT{END}"

    .global Unk_08213C6F
Unk_08213C6F:
    .string "DragonAR{END}"

    .global Unk_08213C78
Unk_08213C78:
    .string "SmartRG{END}"

    .global Unk_08213C80
Unk_08213C80:
    .string "DreamRG{END}"

    .align 2
    .global Unk_08213C88
Unk_08213C88:
    .word Unk_08213888 @ 0 / 0x0
    .word Unk_0821388D @ 1 / 0x1
    .word Unk_08213895 @ 2 / 0x2
    .word Unk_0821389B @ 3 / 0x3
    .word Unk_082138A3 @ 4 / 0x4
    .word Unk_082138AA @ 5 / 0x5
    .word Unk_082138B0 @ 6 / 0x6
    .word Unk_082138B8 @ 7 / 0x7
    .word Unk_082138BD @ 8 / 0x8
    .word Unk_082138C4 @ 9 / 0x9
    .word Unk_082138CD @ 10 / 0xA
    .word Unk_082138D6 @ 11 / 0xB
    .word Unk_082138DE @ 12 / 0xC
    .word Unk_082138E6 @ 13 / 0xD
    .word Unk_082138EC @ 14 / 0xE
    .word Unk_082138F4 @ 15 / 0xF
    .word Unk_082138FC @ 16 / 0x10
    .word Unk_08213904 @ 17 / 0x11
    .word Unk_0821390A @ 18 / 0x12
    .word Unk_08213912 @ 19 / 0x13
    .word Unk_08213918 @ 20 / 0x14
    .word Unk_08213920 @ 21 / 0x15
    .word Unk_08213928 @ 22 / 0x16
    .word Unk_0821392F @ 23 / 0x17
    .word Unk_08213937 @ 24 / 0x18
    .word Unk_0821393F @ 25 / 0x19
    .word Unk_08213947 @ 26 / 0x1A
    .word Unk_0821394E @ 27 / 0x1B
    .word Unk_08213955 @ 28 / 0x1C
    .word Unk_0821395D @ 29 / 0x1D
    .word Unk_08213964 @ 30 / 0x1E
    .word Unk_0821396C @ 31 / 0x1F
    .word Unk_08213975 @ 32 / 0x20
    .word Unk_0821397D @ 33 / 0x21
    .word Unk_08213983 @ 34 / 0x22
    .word Unk_0821398A @ 35 / 0x23
    .word Unk_08213990 @ 36 / 0x24
    .word Unk_08213996 @ 37 / 0x25
    .word Unk_0821399E @ 38 / 0x26
    .word Unk_082139A5 @ 39 / 0x27
    .word Unk_082139AB @ 40 / 0x28
    .word Unk_082139B2 @ 41 / 0x29
    .word Unk_082139BA @ 42 / 0x2A
    .word Unk_082139C0 @ 43 / 0x2B
    .word Unk_082139C8 @ 44 / 0x2C
    .word Unk_082139CE @ 45 / 0x2D
    .word Unk_082139D5 @ 46 / 0x2E
    .word Unk_082139DD @ 47 / 0x2F
    .word Unk_082139E3 @ 48 / 0x30
    .word Unk_082139EA @ 49 / 0x31
    .word Unk_082139F3 @ 50 / 0x32
    .word Unk_082139FB @ 51 / 0x33
    .word Unk_08213A03 @ 52 / 0x34
    .word Unk_08213A0C @ 53 / 0x35
    .word Unk_08213A13 @ 54 / 0x36
    .word Unk_08213A1B @ 55 / 0x37
    .word Unk_08213A23 @ 56 / 0x38
    .word Unk_08213A2B @ 57 / 0x39
    .word Unk_08213A31 @ 58 / 0x3A
    .word Unk_08213A38 @ 59 / 0x3B
    .word Unk_08213A3F @ 60 / 0x3C
    .word Unk_08213A47 @ 61 / 0x3D
    .word Unk_08213A4D @ 62 / 0x3E
    .word Unk_08213A53 @ 63 / 0x3F
    .word Unk_08213A59 @ 64 / 0x40
    .word Unk_08213A5F @ 65 / 0x41
    .word Unk_08213A66 @ 66 / 0x42
    .word Unk_08213A6D @ 67 / 0x43
    .word Unk_08213A74 @ 68 / 0x44
    .word Unk_08213A7A @ 69 / 0x45
    .word Unk_08213A81 @ 70 / 0x46
    .word Unk_08213A87 @ 71 / 0x47
    .word Unk_08213A8E @ 72 / 0x48
    .word Unk_08213A94 @ 73 / 0x49
    .word Unk_08213A9A @ 74 / 0x4A
    .word Unk_08213AA2 @ 75 / 0x4B
    .word Unk_08213AAA @ 76 / 0x4C
    .word Unk_08213AB2 @ 77 / 0x4D
    .word Unk_08213ABA @ 78 / 0x4E
    .word Unk_08213AC0 @ 79 / 0x4F
    .word Unk_08213AC9 @ 80 / 0x50
    .word Unk_08213ACF @ 81 / 0x51
    .word Unk_08213AD6 @ 82 / 0x52
    .word Unk_08213ADD @ 83 / 0x53
    .word Unk_08213AE4 @ 84 / 0x54
    .word Unk_08213AED @ 85 / 0x55
    .word Unk_08213AF3 @ 86 / 0x56
    .word Unk_08213AFA @ 87 / 0x57
    .word Unk_08213B00 @ 88 / 0x58
    .word Unk_08213B08 @ 89 / 0x59
    .word Unk_08213B0E @ 90 / 0x5A
    .word Unk_08213B17 @ 91 / 0x5B
    .word Unk_08213B1D @ 92 / 0x5C
    .word Unk_08213B25 @ 93 / 0x5D
    .word Unk_08213B2D @ 94 / 0x5E
    .word Unk_08213B34 @ 95 / 0x5F
    .word Unk_08213B3D @ 96 / 0x60
    .word Unk_08213B43 @ 97 / 0x61
    .word Unk_08213B49 @ 98 / 0x62
    .word Unk_08213B51 @ 99 / 0x63
    .word Unk_08213B58 @ 100 / 0x64
    .word Unk_08213B61 @ 101 / 0x65
    .word Unk_08213B69 @ 102 / 0x66
    .word Unk_08213B70 @ 103 / 0x67
    .word Unk_08213B77 @ 104 / 0x68
    .word Unk_08213B80 @ 105 / 0x69
    .word Unk_08213B89 @ 106 / 0x6A
    .word Unk_08213B92 @ 107 / 0x6B
    .word Unk_08213B9B @ 108 / 0x6C
    .word Unk_08213BA3 @ 109 / 0x6D
    .word Unk_08213BAB @ 110 / 0x6E
    .word Unk_08213BB2 @ 111 / 0x6F
    .word Unk_08213BB8 @ 112 / 0x70
    .word Unk_08213BBF @ 113 / 0x71
    .word Unk_08213BC7 @ 114 / 0x72
    .word Unk_08213BCF @ 115 / 0x73
    .word Unk_08213BD6 @ 116 / 0x74
    .word Unk_08213BDD @ 117 / 0x75
    .word Unk_08213BE5 @ 118 / 0x76
    .word Unk_08213BEC @ 119 / 0x77
    .word Unk_08213BF2 @ 120 / 0x78
    .word Unk_08213BF9 @ 121 / 0x79
    .word Unk_08213BFF @ 122 / 0x7A
    .word Unk_08213C05 @ 123 / 0x7B
    .word Unk_08213C0B @ 124 / 0x7C
    .word Unk_08213C13 @ 125 / 0x7D
    .word Unk_08213C1A @ 126 / 0x7E
    .word Unk_08213C20 @ 127 / 0x7F
    .word Unk_08213C27 @ 128 / 0x80
    .word Unk_08213C2D @ 129 / 0x81
    .word Unk_08213C33 @ 130 / 0x82
    .word Unk_08213C39 @ 131 / 0x83
    .word Unk_08213C3F @ 132 / 0x84
    .word Unk_08213C46 @ 133 / 0x85
    .word Unk_08213C4C @ 134 / 0x86
    .word Unk_08213C54 @ 135 / 0x87
    .word Unk_08213C5A @ 136 / 0x88
    .word Unk_08213C60 @ 137 / 0x89
    .word Unk_08213C66 @ 138 / 0x8A
    .word Unk_08213C6F @ 139 / 0x8B
    .word Unk_08213C78 @ 140 / 0x8C
    .word Unk_08213C80 @ 141 / 0x8D
