    .global Unk_08211E4C
Unk_08211E4C:
    .string "Frog{END}"

    .global Unk_08211E51
Unk_08211E51:
    .string "Knight{END}"

    .global Unk_08211E58
Unk_08211E58:
    .string "Wizard{END}"

    .global Unk_08211E5F
Unk_08211E5F:
    .string "Wizard{END}"

    .global Unk_08211E66
Unk_08211E66:
    .string "Wizard{END}"

    .global Unk_08211E6D
Unk_08211E6D:
    .string "Flea{END}"

    .global Unk_08211E72
Unk_08211E72:
    .string "Avian{END}"

    .global Unk_08211E78
Unk_08211E78:
    .string "Stool{END}"

    .global Unk_08211E7E
Unk_08211E7E:
    .string "Gloom{END}"

    .global Unk_08211E84
Unk_08211E84:
    .string "Beak{END}"

    .global Unk_08211E89
Unk_08211E89:
    .string "Creep{END}"

    .global Unk_08211E8F
Unk_08211E8F:
    .string "Zard{END}"

    .global Unk_08211E94
Unk_08211E94:
    .string "Morte{END}"

    .global Unk_08211E9A
Unk_08211E9A:
    .string "Mortea{END}"

    .global Unk_08211EA1
Unk_08211EA1:
    .string "Talon{END}"

    .global Unk_08211EA7
Unk_08211EA7:
    .string "Bain{END}"

    .global Unk_08211EAC
Unk_08211EAC:
    .string "General{END}"

    .global Unk_08211EB4
Unk_08211EB4:
    .string "Gremlin{END}"

    .global Unk_08211EBC
Unk_08211EBC:
    .string "Wisp{END}"

    .global Unk_08211EC1
Unk_08211EC1:
    .string "Pog{END}"

    .global Unk_08211EC5
Unk_08211EC5:
    .string "Zombie{END}"

    .global Unk_08211ECC
Unk_08211ECC:
    .string "Slime{END}"

    .global Unk_08211ED2
Unk_08211ED2:
    .string "S.Rider{END}"

    .global Unk_08211EDA
Unk_08211EDA:
    .string "Blurb{END}"

    .global Unk_08211EE0
Unk_08211EE0:
    .string "Lancer{END}"

    .global Unk_08211EE7
Unk_08211EE7:
    .string "Bowman{END}"

    .global Unk_08211EEE
Unk_08211EEE:
    .string "Ruga{END}"

    .global Unk_08211EF3
Unk_08211EF3:
    .string "WarHog{END}"

    .global Unk_08211EFA
Unk_08211EFA:
    .string "Ameblob{END}"

    .global Unk_08211F02
Unk_08211F02:
    .string "Bulla{END}"

    .global Unk_08211F08
Unk_08211F08:
    .string "Roach{END}"

    .global Unk_08211F0E
Unk_08211F0E:
    .string "G.Fly{END}"

    .global Unk_08211F14
Unk_08211F14:
    .string "EyeSpy{END}"

    .global Unk_08211F1B
Unk_08211F1B:
    .string "Octo{END}"

    .global Unk_08211F20
Unk_08211F20:
    .string "Squid{END}"

    .global Unk_08211F26
Unk_08211F26:
    .string "SandWorm{END}"

    .global Unk_08211F2F
Unk_08211F2F:
    .string "Cloud{END}"

    .global Unk_08211F35
Unk_08211F35:
    .string "Scorp{END}"

    .global Unk_08211F3B
Unk_08211F3B:
    .string "Mage{END}"

    .global Unk_08211F40
Unk_08211F40:
    .string "Prickle{END}"

    .global Unk_08211F48
Unk_08211F48:
    .string "Archer{END}"

    .global Unk_08211F4F
Unk_08211F4F:
    .string "Fly{END}"

    .global Unk_08211F53
Unk_08211F53:
    .string "SpearMan{END}"

    .global Unk_08211F5C
Unk_08211F5C:
    .string "Creon{END}"

    .global Unk_08211F62
Unk_08211F62:
    .string "Knight{END}"

    .global Unk_08211F69
Unk_08211F69:
    .string "Mothro{END}"

    .global Unk_08211F70
Unk_08211F70:
    .string "Mote{END}"

    .global Unk_08211F75
Unk_08211F75:
    .string "Soldier{END}"

    .global Unk_08211F7D
Unk_08211F7D:
    .string "GrimFowl{END}"

    .global Unk_08211F86
Unk_08211F86:
    .string "Pincher{END}"

    .global Unk_08211F8E
Unk_08211F8E:
    .string "SlimeX{END}"

    .global Unk_08211F95
Unk_08211F95:
    .string "Myst{END}"

    .global Unk_08211F9A
Unk_08211F9A:
    .string "R.Slime{END}"

    .global Unk_08211FA2
Unk_08211FA2:
    .string "Fishy{END}"

    .global Unk_08211FA8
Unk_08211FA8:
    .string "DogFish{END}"

    .global Unk_08211FB0
Unk_08211FB0:
    .string "Midget{END}"

    .global Unk_08211FB7
Unk_08211FB7:
    .string "Tronk{END}"

    .global Unk_08211FBD
Unk_08211FBD:
    .string "SandClod{END}"

    .global Unk_08211FC6
Unk_08211FC6:
    .string "Tentacle{END}"

    .global Unk_08211FCF
Unk_08211FCF:
    .string "M.Scorp{END}"

    .global Unk_08211FD7
Unk_08211FD7:
    .string "RugaX{END}"

    .global Unk_08211FDD
Unk_08211FDD:
    .string "LancerX{END}"

    .global Unk_08211FE5
Unk_08211FE5:
    .string "BowManX{END}"

    .global Unk_08211FED
Unk_08211FED:
    .string "Wraith{END}"

    .global Unk_08211FF4
Unk_08211FF4:
    .string "RugaX{END}"

    .global Unk_08211FFA
Unk_08211FFA:
    .string "FlowerX{END}"

    .global Unk_08212002
Unk_08212002:
    .string "HornToad{END}"

    .global Unk_0821200B
Unk_0821200B:
    .string "Mote{END}"

    .global Unk_08212010
Unk_08212010:
    .string "Cerl{END}"

    .global Unk_08212015
Unk_08212015:
    .string "Mothro{END}"

    .global Unk_0821201C
Unk_0821201C:
    .string "P.Bug{END}"

    .global Unk_08212022
Unk_08212022:
    .string "Chimera{END}"

    .global Unk_0821202A
Unk_0821202A:
    .string "Fungus{END}"

    .global Unk_08212031
Unk_08212031:
    .string "Chopper{END}"

    .global Unk_08212039
Unk_08212039:
    .string "K.Roach{END}"

    .global Unk_08212041
Unk_08212041:
    .string "Phoenix{END}"

    .global Unk_08212049
Unk_08212049:
    .string "Morteo{END}"

    .global Unk_08212050
Unk_08212050:
    .string "Sorcerer{END}"

    .global Unk_08212059
Unk_08212059:
    .string "Toad{END}"

    .global Unk_0821205E
Unk_0821205E:
    .string "Rogue{END}"

    .global Unk_08212064
Unk_08212064:
    .string "Goda{END}"

    .global Unk_08212069
Unk_08212069:
    .string "Zog{END}"

    .global Unk_0821206D
Unk_0821206D:
    .string "Jade{END}"

    .global Unk_08212072
Unk_08212072:
    .string "Goddess{END}"

    .global Unk_0821207A
Unk_0821207A:
    .string "Goddess{END}"

    .global Unk_08212082
Unk_08212082:
    .string "Sara{END}"

    .global Unk_08212087
Unk_08212087:
    .string "Warlock{END}"

    .global Unk_0821208F
Unk_0821208F:
    .string "Zoom{END}"

    .global Unk_08212094
Unk_08212094:
    .string "Gargoyle{END}"

    .global Unk_0821209D
Unk_0821209D:
    .string "G.Knight{END}"

    .global Unk_082120A6
Unk_082120A6:
    .string "Shadow{END}"

    .global Unk_082120AD
Unk_082120AD:
    .string "WraithX{END}"

    .global Unk_082120B5
Unk_082120B5:
    .string "Spider{END}"

    .global Unk_082120BC
Unk_082120BC:
    .string "Blaze{END}"

    .global Unk_082120C2
Unk_082120C2:
    .string "Golem{END}"

    .global Unk_082120C8
Unk_082120C8:
    .string "E.Chest{END}"

    .global Unk_082120D0
Unk_082120D0:
    .string "Goddess{END}"

    .global Unk_082120D8
Unk_082120D8:
    .string "D.Flea{END}"

    .global Unk_082120DF
Unk_082120DF:
    .string "Crab{END}"

    .global Unk_082120E4
Unk_082120E4:
    .string "Flower{END}"

    .global Unk_082120EB
Unk_082120EB:
    .string "G.Slime{END}"

    .global Unk_082120F3
Unk_082120F3:
    .string "M.Slime{END}"

    .global Unk_082120FB
Unk_082120FB:
    .string "Buzzer{END}"

    .global Unk_08212102
Unk_08212102:
    .string "Crawler{END}"

    .global Unk_0821210A
Unk_0821210A:
    .string "Ruga{END}"

    .global Unk_0821210F
Unk_0821210F:
    .string "Ronk{END}"

    .global Unk_08212114
Unk_08212114:
    .string "DogFishX{END}"

    .global Unk_0821211D
Unk_0821211D:
    .string "BlazeX{END}"

    .global Unk_08212124
Unk_08212124:
    .string "AmeblobX{END}"

    .global Unk_0821212D
Unk_0821212D:
    .string "Nautulis{END}"

    .global Unk_08212136
Unk_08212136:
    .string "Widow{END}"

    .global Unk_0821213C
Unk_0821213C:
    .string "M.Flea{END}"

    .global Unk_08212143
Unk_08212143:
    .string "CrawlerX{END}"

    .global Unk_0821214C
Unk_0821214C:
    .string "Mimic{END}"

    .global Unk_08212152
Unk_08212152:
    .string "WarHogX{END}"

    .global Unk_0821215A
Unk_0821215A:
    .string "FireHead{END}"

    .global Unk_08212163
Unk_08212163:
    .string "Bully{END}"

    .global Unk_08212169
Unk_08212169:
    .string "Claw{END}"

    .global Unk_0821216E
Unk_0821216E:
    .string "PincherX{END}"

    .global Unk_08212177
Unk_08212177:
    .string "CreonX{END}"

    .global Unk_0821217E
Unk_0821217E:
    .string "Bain{END}"

    .global Unk_08212183
Unk_08212183:
    .string "D.Rider{END}"

    .global Unk_0821218B
Unk_0821218B:
    .string "Ghoul{END}"

    .global Unk_08212191
Unk_08212191:
    .string "Cactus{END}"

    .global Unk_08212198
Unk_08212198:
    .string "CactusX{END}"

    .global Unk_082121A0
Unk_082121A0:
    .string "ICU{END}"

    .global Unk_082121A4
Unk_082121A4:
    .string "Entity{END}"

    .global Unk_082121AB
Unk_082121AB:
    .string "D.Knight{END}"

    .align 2
    .global Unk_082121B4
Unk_082121B4:
    .word Unk_08211E4C @ 0 / 0x0
    .word Unk_08211E51 @ 1 / 0x1
    .word Unk_08211E58 @ 2 / 0x2
    .word Unk_08211E5F @ 3 / 0x3
    .word Unk_08211E66 @ 4 / 0x4
    .word Unk_08211E6D @ 5 / 0x5
    .word Unk_08211E72 @ 6 / 0x6
    .word Unk_08211E78 @ 7 / 0x7
    .word Unk_08211E7E @ 8 / 0x8
    .word Unk_08211E84 @ 9 / 0x9
    .word Unk_08211E89 @ 10 / 0xA
    .word Unk_08211E8F @ 11 / 0xB
    .word Unk_08211E94 @ 12 / 0xC
    .word Unk_08211E9A @ 13 / 0xD
    .word Unk_08211EA1 @ 14 / 0xE
    .word Unk_08211EA7 @ 15 / 0xF
    .word Unk_08211EAC @ 16 / 0x10
    .word Unk_08211EB4 @ 17 / 0x11
    .word Unk_08211EBC @ 18 / 0x12
    .word Unk_08211EC1 @ 19 / 0x13
    .word Unk_08211EC5 @ 20 / 0x14
    .word Unk_08211ECC @ 21 / 0x15
    .word Unk_08211ED2 @ 22 / 0x16
    .word Unk_08211EDA @ 23 / 0x17
    .word Unk_08211EE0 @ 24 / 0x18
    .word Unk_08211EE7 @ 25 / 0x19
    .word Unk_08211EEE @ 26 / 0x1A
    .word Unk_08211EF3 @ 27 / 0x1B
    .word Unk_08211EFA @ 28 / 0x1C
    .word Unk_08211F02 @ 29 / 0x1D
    .word Unk_08211F08 @ 30 / 0x1E
    .word Unk_08211F0E @ 31 / 0x1F
    .word Unk_08211F14 @ 32 / 0x20
    .word Unk_08211F1B @ 33 / 0x21
    .word Unk_08211F20 @ 34 / 0x22
    .word Unk_08211F26 @ 35 / 0x23
    .word Unk_08211F2F @ 36 / 0x24
    .word Unk_08211F35 @ 37 / 0x25
    .word Unk_08211F3B @ 38 / 0x26
    .word Unk_08211F40 @ 39 / 0x27
    .word Unk_08211F48 @ 40 / 0x28
    .word Unk_08211F4F @ 41 / 0x29
    .word Unk_08211F53 @ 42 / 0x2A
    .word Unk_08211F5C @ 43 / 0x2B
    .word Unk_08211F62 @ 44 / 0x2C
    .word Unk_08211F69 @ 45 / 0x2D
    .word Unk_08211F70 @ 46 / 0x2E
    .word Unk_08211F75 @ 47 / 0x2F
    .word Unk_08211F7D @ 48 / 0x30
    .word Unk_08211F86 @ 49 / 0x31
    .word Unk_08211F8E @ 50 / 0x32
    .word Unk_08211F95 @ 51 / 0x33
    .word Unk_08211F9A @ 52 / 0x34
    .word Unk_08211FA2 @ 53 / 0x35
    .word Unk_08211FA8 @ 54 / 0x36
    .word Unk_08211FB0 @ 55 / 0x37
    .word Unk_08211FB7 @ 56 / 0x38
    .word Unk_08211FBD @ 57 / 0x39
    .word Unk_08211FC6 @ 58 / 0x3A
    .word Unk_08211FCF @ 59 / 0x3B
    .word Unk_08211FD7 @ 60 / 0x3C
    .word Unk_08211FDD @ 61 / 0x3D
    .word Unk_08211FE5 @ 62 / 0x3E
    .word Unk_08211FED @ 63 / 0x3F
    .word Unk_08211FF4 @ 64 / 0x40
    .word Unk_08211FFA @ 65 / 0x41
    .word Unk_08212002 @ 66 / 0x42
    .word Unk_0821200B @ 67 / 0x43
    .word Unk_08212010 @ 68 / 0x44
    .word Unk_08212015 @ 69 / 0x45
    .word Unk_0821201C @ 70 / 0x46
    .word Unk_08212022 @ 71 / 0x47
    .word Unk_0821202A @ 72 / 0x48
    .word Unk_08212031 @ 73 / 0x49
    .word Unk_08212039 @ 74 / 0x4A
    .word Unk_08212041 @ 75 / 0x4B
    .word Unk_08212049 @ 76 / 0x4C
    .word Unk_08212050 @ 77 / 0x4D
    .word Unk_08212059 @ 78 / 0x4E
    .word Unk_0821205E @ 79 / 0x4F
    .word Unk_08212064 @ 80 / 0x50
    .word Unk_08212069 @ 81 / 0x51
    .word Unk_0821206D @ 82 / 0x52
    .word Unk_08212072 @ 83 / 0x53
    .word Unk_0821207A @ 84 / 0x54
    .word Unk_08212082 @ 85 / 0x55
    .word Unk_08212087 @ 86 / 0x56
    .word Unk_0821208F @ 87 / 0x57
    .word Unk_08212094 @ 88 / 0x58
    .word Unk_0821209D @ 89 / 0x59
    .word Unk_082120A6 @ 90 / 0x5A
    .word Unk_082120AD @ 91 / 0x5B
    .word Unk_082120B5 @ 92 / 0x5C
    .word Unk_082120BC @ 93 / 0x5D
    .word Unk_082120C2 @ 94 / 0x5E
    .word Unk_082120C8 @ 95 / 0x5F
    .word Unk_082120D0 @ 96 / 0x60
    .word Unk_082120D8 @ 97 / 0x61
    .word Unk_082120DF @ 98 / 0x62
    .word Unk_082120E4 @ 99 / 0x63
    .word Unk_082120EB @ 100 / 0x64
    .word Unk_082120F3 @ 101 / 0x65
    .word Unk_082120FB @ 102 / 0x66
    .word Unk_08212102 @ 103 / 0x67
    .word Unk_0821210A @ 104 / 0x68
    .word Unk_0821210F @ 105 / 0x69
    .word Unk_08212114 @ 106 / 0x6A
    .word Unk_0821211D @ 107 / 0x6B
    .word Unk_08212124 @ 108 / 0x6C
    .word Unk_0821212D @ 109 / 0x6D
    .word Unk_08212136 @ 110 / 0x6E
    .word Unk_0821213C @ 111 / 0x6F
    .word Unk_08212143 @ 112 / 0x70
    .word Unk_0821214C @ 113 / 0x71
    .word Unk_08212152 @ 114 / 0x72
    .word Unk_0821215A @ 115 / 0x73
    .word Unk_08212163 @ 116 / 0x74
    .word Unk_08212169 @ 117 / 0x75
    .word Unk_0821216E @ 118 / 0x76
    .word Unk_08212177 @ 119 / 0x77
    .word Unk_0821217E @ 120 / 0x78
    .word Unk_08212183 @ 121 / 0x79
    .word Unk_0821218B @ 122 / 0x7A
    .word Unk_08212191 @ 123 / 0x7B
    .word Unk_08212198 @ 124 / 0x7C
    .word Unk_082121A0 @ 125 / 0x7D
    .word Unk_082121A4 @ 126 / 0x7E
    .word Unk_082121AB @ 127 / 0x7F
