    .global Unk_082123B4
Unk_082123B4:
    .string "Recovers HP by 50pts.{END}"

    .global Unk_082123CA
Unk_082123CA:
    .string "Briefly ups defense power.{END}"

    .global Unk_082123E5
Unk_082123E5:
    .string "Slows enemy down.{END}"

    .global Unk_082123F7
Unk_082123F7:
    .string "Briefly ups luck.{END}"

    .global Unk_08212409
Unk_08212409:
    .string "Briefly ups attack power.{END}"

    .global Unk_08212423
Unk_08212423:
    .string "Recovers HP by 100pts.{END}"

    .global Unk_0821243A
Unk_0821243A:
    .string "Holds enemy's move.{END}"

    .global Unk_0821244E
Unk_0821244E:
    .string "Briefly ups agility.{END}"

    .global Unk_08212463
Unk_08212463:
    .string "Angel LV1. Single enemy.{END}"

    .global Unk_0821247C
Unk_0821247C:
    .string "Recovers HP by 250pts.{END}"

    .global Unk_08212493
Unk_08212493:
    .string "Cures “Stun“ state HP1.{END}"

    .global Unk_082124AB
Unk_082124AB:
    .string "Cures any abnormal status.{END}"

    .global Unk_082124C6
Unk_082124C6:
    .string "Lessens damage by magic.{END}"

    .global Unk_082124DF
Unk_082124DF:
    .string "Recovers HP fully.{END}"

    .global Unk_082124F2
Unk_082124F2:
    .string "Angel LV2. Single enemy.{END}"

    .global Unk_0821250B
Unk_0821250B:
    .string "Ups party's defense power.{END}"

    .global Unk_08212526
Unk_08212526:
    .string "Briefly seals enemy's magic.{END}"

    .global Unk_08212543
Unk_08212543:
    .string "Voids enemy's magic once.{END}"

    .global Unk_0821255D
Unk_0821255D:
    .string "Cures “Stun“ state fully.{END}"

    .global Unk_08212577
Unk_08212577:
    .string "Recovers party HP by 250pts.{END}"

    .global Unk_08212594
Unk_08212594:
    .string "Reflects enemy's magic once.{END}"

    .global Unk_082125B1
Unk_082125B1:
    .string "Angel LV3. Enemy group.{END}"

    .global Unk_082125C9
Unk_082125C9:
    .string "Fire LV1. Single enemy.{END}"

    .global Unk_082125E1
Unk_082125E1:
    .string "Thunder LV1. Single enemy.{END}"

    .global Unk_082125FC
Unk_082125FC:
    .string "Ice LV1. Single enemy.{END}"

    .global Unk_08212613
Unk_08212613:
    .string "Quake LV1. Enemy group.{END}"

    .global Unk_0821262B
Unk_0821262B:
    .string "Stops enemy's time.{END}"

    .global Unk_0821263F
Unk_0821263F:
    .string "Absorbs enemy's HP.{END}"

    .global Unk_08212653
Unk_08212653:
    .string "Death penalty. Single enemy.{END}"

    .global Unk_08212670
Unk_08212670:
    .string "Fire LV2. Single enemy.{END}"

    .global Unk_08212688
Unk_08212688:
    .string "Thunder LV2. Single enemy.{END}"

    .global Unk_082126A3
Unk_082126A3:
    .string "Ice LV2. Single enemy.{END}"

    .global Unk_082126BA
Unk_082126BA:
    .string "Quake LV2. Enemy group.{END}"

    .global Unk_082126D2
Unk_082126D2:
    .string "Fire LV3. Single enemy.{END}"

    .global Unk_082126EA
Unk_082126EA:
    .string "Thunder LV4. Enemy group.{END}"

    .global Unk_08212704
Unk_08212704:
    .string "Ice LV3. Enemy group.{END}"

    .global Unk_0821271A
Unk_0821271A:
    .string "Quake LV3. Enemy group.{END}"

    .global Unk_08212732
Unk_08212732:
    .string "Thunder LV5. Enemy group.{END}"

    .global Unk_0821274C
Unk_0821274C:
    .string "Ice LV4. Enemy group.{END}"

    .global Unk_08212762
Unk_08212762:
    .string "Fire LV5. Enemy group.{END}"

    .global Unk_08212779
Unk_08212779:
    .string "Ice LV5. Single enemy.{END}"

    .global Unk_08212790
Unk_08212790:
    .string "Fire LV4. Single enemy.{END}"

    .global Unk_082127A8
Unk_082127A8:
    .string "Thunder LV3. Single enemy.{END}"

    .global Unk_082127C3
Unk_082127C3:
    .string "Absorbs enemy's AP.{END}"

    .global Unk_082127D7
Unk_082127D7:
    .string "Dummy{END}"

    .global Unk_082127DD
Unk_082127DD:
    .string "Meteor storm. Enemy group.{END}"

    .global Unk_082127F8
Unk_082127F8:
    .string "Dummy{END}"

    .global Unk_082127FE
Unk_082127FE:
    .string "Dummy{END}"

    .global Unk_08212804
Unk_08212804:
    .string "Dummy{END}"

    .global Unk_0821280A
Unk_0821280A:
    .string "Dummy{END}"

    .global Unk_08212810
Unk_08212810:
    .string "Dummy{END}"

    .global Unk_08212816
Unk_08212816:
    .string "Dummy{END}"

    .global Unk_0821281C
Unk_0821281C:
    .string "Dummy{END}"

    .global Unk_08212822
Unk_08212822:
    .string "Cures “Stun“ state fully.{END}"

    .global Unk_0821283C
Unk_0821283C:
    .string "Used under water in battle.{END}"

    .global Unk_08212858
Unk_08212858:
    .string "Used under water in battle.{END}"

    .global Unk_08212874
Unk_08212874:
    .string "Used under water in battle.{END}"

    .global Unk_08212890
Unk_08212890:
    .string "Used under water in battle.{END}"

    .global Unk_082128AC
Unk_082128AC:
    .string "Dummy{END}"

    .global Unk_082128B2
Unk_082128B2:
    .string "Dummy{END}"

    .global Unk_082128B8
Unk_082128B8:
    .string "Dummy{END}"

    .global Unk_082128BE
Unk_082128BE:
    .string "Dummy{END}"

    .global Unk_082128C4
Unk_082128C4:
    .string "Dummy{END}"

    .global Unk_082128CA
Unk_082128CA:
    .string "Dummy{END}"

    .global Unk_082128D0
Unk_082128D0:
    .string "Dummy{END}"

    .global Unk_082128D6
Unk_082128D6:
    .string "Dummy{END}"

    .global Unk_082128DC
Unk_082128DC:
    .string "Dummy{END}"

    .global Unk_082128E2
Unk_082128E2:
    .string "Angel LV3. Enemy group.{END}"

    .global Unk_082128FA
Unk_082128FA:
    .string "Dummy{END}"

    .global Unk_08212900
Unk_08212900:
    .string "Dummy{END}"

    .global Unk_08212906
Unk_08212906:
    .string "Explosion LV1. Single enemy.{END}"

    .global Unk_08212923
Unk_08212923:
    .string "Explosion LV2. Enemy group.{END}"

    .global Unk_0821293F
Unk_0821293F:
    .string "Warps to a town.{END}"

    .global Unk_08212950
Unk_08212950:
    .string "Escapes from battle.{END}"

    .global Unk_08212965
Unk_08212965:
    .string "Explosion LV3. Single enemy.{END}"

    .global Unk_08212982
Unk_08212982:
    .string "Escapes from a dungeon.{END}"

    .global Unk_0821299A
Unk_0821299A:
    .string "Explosion LV4. Enemy group.{END}"

    .global Unk_082129B6
Unk_082129B6:
    .string "Explosion LV5. Single enemy.{END}"

    .global Unk_082129D3
Unk_082129D3:
    .string "Dummy{END}"

    .global Unk_082129D9
Unk_082129D9:
    .string "Dummy{END}"

    .global Unk_082129DF
Unk_082129DF:
    .string "Digs to escape from battle.{END}"

    .global Unk_082129FB
Unk_082129FB:
    .string "Used in battle.{END}"

    .global Unk_08212A0B
Unk_08212A0B:
    .string "Characters fuse together.{END}"

    .global Unk_08212A25
Unk_08212A25:
    .string "Available under water.{END}"

    .global Unk_08212A3C
Unk_08212A3C:
    .string "Available on the ground.{END}"

    .global Unk_08212A55
Unk_08212A55:
    .string "Characters fuse together.{END}"

    .global Unk_08212A6F
Unk_08212A6F:
    .string "Releases fused characters.{END}"

    .global Unk_08212A8A
Unk_08212A8A:
    .string "Returns to human form.{END}"

    .align 2
    .global Unk_08212AA4
Unk_08212AA4:
    .word Unk_082123B4 @ 0 / 0x0
    .word Unk_082123CA @ 1 / 0x1
    .word Unk_082123E5 @ 2 / 0x2
    .word Unk_082123F7 @ 3 / 0x3
    .word Unk_08212409 @ 4 / 0x4
    .word Unk_08212423 @ 5 / 0x5
    .word Unk_0821243A @ 6 / 0x6
    .word Unk_0821244E @ 7 / 0x7
    .word Unk_08212463 @ 8 / 0x8
    .word Unk_0821247C @ 9 / 0x9
    .word Unk_08212493 @ 10 / 0xA
    .word Unk_082124AB @ 11 / 0xB
    .word Unk_082124C6 @ 12 / 0xC
    .word Unk_082124DF @ 13 / 0xD
    .word Unk_082124F2 @ 14 / 0xE
    .word Unk_0821250B @ 15 / 0xF
    .word Unk_08212526 @ 16 / 0x10
    .word Unk_08212543 @ 17 / 0x11
    .word Unk_0821255D @ 18 / 0x12
    .word Unk_08212577 @ 19 / 0x13
    .word Unk_08212594 @ 20 / 0x14
    .word Unk_082125B1 @ 21 / 0x15
    .word Unk_082125C9 @ 22 / 0x16
    .word Unk_082125E1 @ 23 / 0x17
    .word Unk_082125FC @ 24 / 0x18
    .word Unk_08212613 @ 25 / 0x19
    .word Unk_0821262B @ 26 / 0x1A
    .word Unk_0821263F @ 27 / 0x1B
    .word Unk_08212653 @ 28 / 0x1C
    .word Unk_08212670 @ 29 / 0x1D
    .word Unk_08212688 @ 30 / 0x1E
    .word Unk_082126A3 @ 31 / 0x1F
    .word Unk_082126BA @ 32 / 0x20
    .word Unk_082126D2 @ 33 / 0x21
    .word Unk_082126EA @ 34 / 0x22
    .word Unk_08212704 @ 35 / 0x23
    .word Unk_0821271A @ 36 / 0x24
    .word Unk_08212732 @ 37 / 0x25
    .word Unk_0821274C @ 38 / 0x26
    .word Unk_08212762 @ 39 / 0x27
    .word Unk_08212779 @ 40 / 0x28
    .word Unk_08212790 @ 41 / 0x29
    .word Unk_082127A8 @ 42 / 0x2A
    .word Unk_082127C3 @ 43 / 0x2B
    .word Unk_082127D7 @ 44 / 0x2C
    .word Unk_082127DD @ 45 / 0x2D
    .word Unk_082127F8 @ 46 / 0x2E
    .word Unk_082127FE @ 47 / 0x2F
    .word Unk_08212804 @ 48 / 0x30
    .word Unk_0821280A @ 49 / 0x31
    .word Unk_08212810 @ 50 / 0x32
    .word Unk_08212816 @ 51 / 0x33
    .word Unk_0821281C @ 52 / 0x34
    .word Unk_08212822 @ 53 / 0x35
    .word Unk_0821283C @ 54 / 0x36
    .word Unk_08212858 @ 55 / 0x37
    .word Unk_08212874 @ 56 / 0x38
    .word Unk_08212890 @ 57 / 0x39
    .word Unk_082128AC @ 58 / 0x3A
    .word Unk_082128B2 @ 59 / 0x3B
    .word Unk_082128B8 @ 60 / 0x3C
    .word Unk_082128BE @ 61 / 0x3D
    .word Unk_082128C4 @ 62 / 0x3E
    .word Unk_082128CA @ 63 / 0x3F
    .word Unk_082128D0 @ 64 / 0x40
    .word Unk_082128D6 @ 65 / 0x41
    .word Unk_082128DC @ 66 / 0x42
    .word Unk_082128E2 @ 67 / 0x43
    .word Unk_082128FA @ 68 / 0x44
    .word Unk_08212900 @ 69 / 0x45
    .word Unk_08212906 @ 70 / 0x46
    .word Unk_08212923 @ 71 / 0x47
    .word Unk_0821293F @ 72 / 0x48
    .word Unk_08212950 @ 73 / 0x49
    .word Unk_08212965 @ 74 / 0x4A
    .word Unk_08212982 @ 75 / 0x4B
    .word Unk_0821299A @ 76 / 0x4C
    .word Unk_082129B6 @ 77 / 0x4D
    .word Unk_082129D3 @ 78 / 0x4E
    .word Unk_082129D9 @ 79 / 0x4F
    .word Unk_082129DF @ 80 / 0x50
    .word Unk_082129FB @ 81 / 0x51
    .word Unk_08212A0B @ 82 / 0x52
    .word Unk_08212A25 @ 83 / 0x53
    .word Unk_08212A3C @ 84 / 0x54
    .word Unk_08212A55 @ 85 / 0x55
    .word Unk_08212A6F @ 86 / 0x56
    .word Unk_08212A8A @ 87 / 0x57
